{
  "hash": "6f8d20dadd21e430ca4fba4fc9e0e2f6",
  "result": {
    "engine": "knitr",
    "markdown": "# Statistical analysis with msqrob2 {#sec-basics}\n\n\nThis chapter explains the main concepts for statistical analysis of\nproteomics data using `msqrob2`. To illustrate these concepts, we will\nuse using a publicly available spike-in study with PRIDE identifier\nPXD003881 [@Shen2018-gw]. This dataset contains ground truth information about which proteins are differentially abundant, enabling us to objectively demonstrate the key aspects of differential proteomics data analysis and their implementation in `msqrob2`. This dataset has a relatively simple\nexperimental design (which does not imply that the analysis is easy),\nallowing us to assess differential abundance using a data analysis\nworkflow with a single factor for the spike-in condition. For more\nadvanced analyses with a more complex experimental design, we refer to\nour [advanced concepts chapter](#sec-advanced) and to the case studies. \n\n## Background \n\nMass spectrometry (MS)-based proteomics aims at characterising the\nproteome abundance of biological samples. A popular approach is\nlabel-free quantification (LFQ), where every sample is analysed in a\nseparate MS run. This section provides an overview of the analytical\nworkflow and its main challenges regarding data modelling.\n\n### LFQ workflow{#sec-lfq_workflow}\n\nIn a nutshell, the wetlab workflow starts with sample preparation where the\nsamples are collected, and the protein content is extracted and\ndigested into peptides. To reduce the sample complexity, the peptides\nare then separated based on physicochemical properties (mostly\nhydrophobicity) using liquid chromatography (LC). Peptides are\nthen ionised by an electrospray as they elute from the chromatographic\ncolumn. The signal over time generated by the eluting ions is called\nthe total ion chromatogram. The ions are then sent for a first round\nof MS to record their m/z distribution for the intact ions. This\nprovides an overview of the ions that elute from the column and allows\nfor further separation of the ions in the m/z space. The second round\nof MS (MS2) records the fragmented ions for a selection of ions,\ngenerally the most intense MS1 peaks^[The ion selection for MS2\ndepends on the data recorded in MS1. Therefore, this approach is\nreferred to as data dependent acquisition (DDA).]. This process is\nrepeated for every sample so that every sample is acquired in one MS\nrun. This provides the ion’s mass fingerprint. For LFQ workflows, the\naccumulated MS1 intensity over time, also known as the area under the\ncurve, around the target mass is used as a quantification measure.\nOn the other hand, the ion mass fingerprint, called the MS2 spectrum,\nenables computational identification of the corresponding peptide\nusing search engines (e.g. Andromeda has been used for this data set)\nthat will provide peptide-to-spectrum matches (PSM). The quantified\nPSM are further processed by the software (MaxQuant) to obtain a\npeptide table^[MaxQuant also computes a protein table. However, we\nfound that starting from MaxQuant's protein table leads to a decrease\nin performance. We will illustrate in this tutorial how to build the\nprotein table.], where every row corresponds to an identified peptide\nand every column contains information about the peptide and its\nquantification in one of the samples.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Overview of an LFQ-based proteomics workflow.](figs/lfq_workflow.png){width=60%}\n:::\n:::\n\n\n### Challenges{#sec-lfq_challenges}\n\nBehind this workflow lies several challenges that will affect the data\nmodelling:\n\n- MS-based proteomics does not measure proteins directly, but their \nconstituting **peptide ions**. The protein-level information needs\nto be reconstructed from the ion data. In this tutorial, we will\nstart from the peptide data, which has been constructed from the ion\ndata by MaxQuant.\n- All peptides do not ionise with the same efficiency. Poor \nionisation will lead to reduced signal as less ions will hit the\ndetector, hence leading to a huge variability in intensity among\ndifferent peptide species, even when they originate from the same\nprotein.\n- The identification step is not trivial and prone to \nerrors^[Improving peptide identification is outside the scope of\nthis tutorial]. PSM misidentification leads to the assignment of a\nquantitative values from another peptide with likely another\nionisation efficiency and relative abundance. Hence this misassigned\nvalues often lead to outliers.\n- Moreover, the ion selection for MS2 depends on its\nintensity^[Recall that only the top most intense ion peaks are send\nfor MS2]. Therefore, the chance to measure and, subsequently, \nidentify a peptide will depend on its abundance. Non identified\npeptides will lead to data missingness, which is related to the\nunderlying quantification value. This phenomenon is known as\nmissingness not at random. Next to that, many reasons can lead to\nions not being selected or identified irrespective of their \nquantification value leading to missingness that is not related to\nits quantitative value. This is referred to as missingness \ncompletely at random. The missingness issue is not negligible as we shall see upon reading the data.\n- The identification issues lead to unbalanced peptide missingness\nacross samples, and the patterns of missing values are potentially\ndifferent for every peptide, highlighting the need for an\nautomatised solution that is robust against missing values.\n- Technical variations during the experiment can lead to systematic \nfluctuations across samples. The most obvious reason is when\ndifferent sample amounts are injected into the instruments, due to\nsmall pipetting inconsistencies for instance. However, these\ndifferences lead to unwanted variation that should be discarded when\nanswering biological questions.\n\n### Experimental context{#sec-ecoli_experiment}\n\nThe samples were synthetically constructed, starting from a\ntrypsin-digested human background, hence human proteins are known to\nbe constant across samples. E. coli lysates were spiked at five\ndifferent concentrations (3%, 4.5%, 6%, 7.5% and 9% wt/wt). So the E.\ncoli proteins are known to be differentially abundant, and we know\nexactly in what amount they differ. There are four replicates per\nspike-in condition. The samples were run on an Orbitrap Fusion mass\nspectrometer. Raw data files were processed with MaxQuant (version\n1.6.1.0) using default search settings unless otherwise noted. Spectra\nwere searched against the UniProtKB/SwissProt human and E. coli\nreference proteome databases (07/06/2018), concatenated with the\ndefault Maxquant contaminant database. Carbamidomethylation of Cystein\nwas set as a fixed modification, and oxidation of Methionine and\nacetylation of the protein amino-terminus were allowed as variable\nmodifications. In silico cleavage was set to use trypsin/P, allowing\ntwo miscleavages. Match between runs was also enabled using default\nsettings. The resulting peptide-to-spectrum matches (PSMs) were\nfiltered by MaxQuant at 1% FDR.\n\nWe will start from the peptide data generated by MaxQuant and infer\nprotein-level differences between samples. To achieve this goal, we\nwill apply an `msqrob2` workflow, a data processing and modelling\nworkflow dedicated to the analysis of MS-based proteomics datasets. We\nwill demonstrate how the workflow can retrieve the spiked-in proteins\nfrom the E. coli data set, while introducing the key\nstatistical concepts of differential proteomics data analysis. Before delving\ninto the analysis, we first set the concentrations for the different\nspike-ins, and will prepare our computational environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconcentrations <- (2:6) * 1.5\nnames(concentrations) <- letters[1:5]\n```\n:::\n\n\n## Software\n\n### Load packages\n\nWe load the `msqrob2` package, along with additional packages for\ndata manipulation and visualisation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({\nlibrary(\"msqrob2\")\nlibrary(\"dplyr\")\nlibrary(\"ggplot2\")\nlibrary(\"patchwork\")\nlibrary(\"tidyr\")\n})\n```\n:::\n\n\n### Parallelisation {#sec-parallel}\n\n`msqrob2` can parallelise computations during the model estimation\nto improve speed. However, we will disable parallelisation to ensure\nthis vignette can be run regardless of hardware. Parallelisation is\ncontrolled using the `BiocParallel` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"BiocParallel\")\nregister(SerialParam())\n```\n:::\n\n\nIf you want to use `msqrob2` with parallelisation enabled and using\n4 cores, you can run the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregister(MulticoreParam(workers = 4))\n```\n:::\n\n\nBe mindful that, while parallelisation can improve speed, it will also\nconsume more RAM because part of the data will be copied multiple\ntimes over your different workers. If you experience crashes because\nyou exceeded the amount of available RAM on your machine, you should\nreduce the number of requested workers.\n\n## Data{#sec-ecoli_data}\n\nThe data were reanalysed by @Sticker2020-rl using MaxQuant and\ndeposited on `GitHub`. We here retrieve MaxQuant's `peptides.txt` for the\nE. coli study.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"BiocFileCache\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: dbplyr\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dbplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:dplyr':\n\n    ident, sql\n```\n\n\n:::\n\n```{.r .cell-code}\nbfc <- BiocFileCache()\npeptideFile <- bfcrpath(bfc,\"https://github.com/statOmics/msqrob2data/raw/refs/heads/main/dda/shen/peptides.txt\")\n```\n:::\n\n\n#### Peptide table{#sec-peptide_table}\n\nEach row in the peptide data table contains information about one\npeptide (the table below shows the first 6 rows). The columns contains\nvarious descriptors about the peptide, such as its sequence, its\ncharge, the amino acid composition, etc. Some of these columns (those\nstarting with `Intensity.`) contain the quantification values for each\nsample. The table format where the quantitative values for each sample\nare contained in a separate column is depicted as the \"wide format\", \nas opposed to the \"long format\" (eg, the [PSM table]).\n\nWe will import the data using the `fread` function of the data.table package. \nWe set the `check.names` argument equal to  `TRUE` so that all column names are \nretrieved using the `$` operator. This will result in a replacement of spaces in \nthe column names with a `.`.\nWe also use argument integer64 = \"double\" because `readQFeatures` from the \n`QFeatures` package does not process 64-bit integers correctly. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npeptides <- data.table::fread(peptideFile, check.names = TRUE, integer64 = \"double\")\nquantCols <- grep(\"Intensity[.]\", names(peptides), value = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Sequence                             |N.term.cleavage.window         |C.term.cleavage.window         |Amino.acid.before |First.amino.acid |Second.amino.acid |Second.last.amino.acid |Last.amino.acid |Amino.acid.after | A.Count| R.Count| N.Count| D.Count| C.Count| Q.Count| E.Count| G.Count| H.Count| I.Count| L.Count| K.Count| M.Count| F.Count| P.Count| S.Count| T.Count| W.Count| Y.Count| V.Count| U.Count| O.Count| Length| Missed.cleavages|      Mass|Proteins |Leading.razor.protein | Start.position| End.position|Gene.names |Protein.names                      |Unique..Groups. |Unique..Proteins. |Charges |      PEP|   Score|Identification.type.a1 |Identification.type.a2 |Identification.type.a3 |Identification.type.a4 |Identification.type.b1 |Identification.type.b2 |Identification.type.b3 |Identification.type.b4 |Identification.type.c1 |Identification.type.c2 |Identification.type.c3 |Identification.type.c4 |Identification.type.d1 |Identification.type.d2 |Identification.type.d3 |Identification.type.d4 |Identification.type.e1 |Identification.type.e2 |Identification.type.e3 |Identification.type.e4 | Experiment.a1| Experiment.a2| Experiment.a3| Experiment.a4| Experiment.b1| Experiment.b2| Experiment.b3| Experiment.b4| Experiment.c1| Experiment.c2| Experiment.c3| Experiment.c4| Experiment.d1| Experiment.d2| Experiment.d3| Experiment.d4| Experiment.e1| Experiment.e2| Experiment.e3| Experiment.e4|  Intensity| Intensity.a1| Intensity.a2| Intensity.a3| Intensity.a4| Intensity.b1| Intensity.b2| Intensity.b3| Intensity.b4| Intensity.c1| Intensity.c2| Intensity.c3| Intensity.c4| Intensity.d1| Intensity.d2| Intensity.d3| Intensity.d4| Intensity.e1| Intensity.e2| Intensity.e3| Intensity.e4|Reverse |Potential.contaminant | id|Protein.group.IDs |Mod..peptide.IDs |Evidence.IDs                                                                                                                                             |MS.MS.IDs                                                                                                                                                     | Best.MS.MS|Oxidation..M..site.IDs | MS.MS.Count| LFQ.intensity.a1| LFQ.intensity.a2| LFQ.intensity.a3| LFQ.intensity.a4| LFQ.intensity.b1| LFQ.intensity.b2| LFQ.intensity.b3| LFQ.intensity.b4| LFQ.intensity.c1| LFQ.intensity.c2| LFQ.intensity.c3| LFQ.intensity.c4| LFQ.intensity.d1| LFQ.intensity.d2| LFQ.intensity.d3| LFQ.intensity.d4| LFQ.intensity.e1| LFQ.intensity.e2| LFQ.intensity.e3| LFQ.intensity.e4|\n|:------------------------------------|:------------------------------|:------------------------------|:-----------------|:----------------|:-----------------|:----------------------|:---------------|:----------------|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|------:|----------------:|---------:|:--------|:---------------------|--------------:|------------:|:----------|:----------------------------------|:---------------|:-----------------|:-------|--------:|-------:|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|----------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|:-------|:---------------------|--:|:-----------------|:----------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------|----------:|:----------------------|-----------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|\n|AAAAAAAAAAAAAAAGAGAGAK               |QSRFQVDLVSENAGRAAAAAAAAAAAAAAA |AAAAAAAAGAGAGAKQTPADGEASGESEPA |R                 |A                |A                 |A                      |K               |Q                |      18|       0|       0|       0|       0|       0|       0|       3|       0|       0|       0|       1|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|     22|                0| 1595.8380|P55011   |P55011                |             93|          114|SLC12A2    |Solute carrier family 12 member 2  |yes             |yes               |2;3     | 0.00e+00|  98.407|By matching            |                       |                       |                       |                       |                       |                       |By MS/MS               |By MS/MS               |By MS/MS               |                       |By MS/MS               |                       |By matching            |By matching            |                       |                       |                       |By matching            |                       |             1|            NA|            NA|            NA|            NA|            NA|            NA|             1|             1|             1|            NA|             1|            NA|             1|             1|            NA|            NA|            NA|             1|            NA|   39754000|      6378300|            0|            0|            0|            0|            0|            0|            0|      4268500|      7099400|            0|            0|            0|      8563700|      6597000|            0|            0|            0|      6846700|            0|        |                      |  0|2115              |0                |0;1;2;3;4;5;6;7                                                                                                                                          |0;1;2;3                                                                                                                                                       |          2|                       |           2|          5715600|                0|                0|                0|                0|                0|                0|                0|          4324900|          8047900|                0|                0|                0|          9420400|          5673000|                0|                0|                0|          5761500|                0|\n|AAAAAAAAAAGAAGGR                     |______________________________ |AAAAAAAAAGAAGGRGSGPGRRRHLVPGAG |M                 |A                |A                 |G                      |R               |G                |      12|       1|       0|       0|       0|       0|       0|       3|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|     16|                0| 1197.6214|Q86U42   |Q86U42                |              2|           17|PABPN1     |Polyadenylate-binding protein 2    |yes             |yes               |2       | 0.00e+00| 275.000|By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By matching            |By MS/MS               |By MS/MS               |By MS/MS               |                       |By MS/MS               |By MS/MS               |By MS/MS               |By matching            |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |                       |By MS/MS               |By MS/MS               |             1|             1|             1|             1|             1|             1|             1|             1|            NA|             1|             1|             1|             1|             1|             1|             1|             1|            NA|             1|             1| 1211200000|     76718000|     53670000|     86511000|     79070000|     57211000|     56593000|     81544000|     79032000|            0|     46087000|     62303000|     73292000|     60707000|     50560000|     75644000|     75246000|     52106000|            0|     74366000|     70540000|        |                      |  1|3262              |1                |8;9;10;11;12;13;14;15;16;17;18;19;20;21;22;23;24;25                                                                                                      |4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19                                                                                                                     |          9|                       |          15|         68748000|         59998000|         74863000|         70216000|         57211000|         63173000|         69374000|         69165000|                0|         52244000|         66990000|         62028000|         62554000|         55618000|         65050000|         63171000|         55715000|                0|         62578000|         58656000|\n|AAAAAAALQAK                          |TILRQARNHKLRVDKAAAAAAALQAKSDEK |RVDKAAAAAAALQAKSDEKAAVAGKKPVVG |K                 |A                |A                 |A                      |K               |S                |       8|       0|       0|       0|       0|       1|       0|       0|       0|       0|       1|       1|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|     11|                0|  955.5451|P36578   |P36578                |            354|          364|RPL4       |60S ribosomal protein L4           |yes             |yes               |2       | 1.00e-07| 182.680|By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |             2|             3|             4|             2|             3|             2|             2|             2|             3|             3|             3|             2|             3|             2|             3|             2|             2|             3|             3|             2| 1829100000|    129520000|     56753000|    114890000|    126100000|     33394000|     66695000|     93968000|    125070000|     84220000|     83186000|    102980000|    108620000|     72544000|     76384000|    100270000|    118790000|     67553000|     52009000|    115880000|    100300000|        |                      |  2|1762              |2                |26;27;28;29;30;31;32;33;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50;51;52;53;54;55;56;57;58;59;60;61;62;63;64;65;66;67;68;69;70;71;72;73;74;75;76 |20;21;22;23;24;25;26;27;28;29;30;31;32;33;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50;51;52;53;54;55;56;57                                             |         29|                       |          30|        116060000|         63444000|         99420000|        111980000|         33394000|         74449000|         79944000|        109450000|         85332000|         94299000|        110730000|         91926000|         74751000|         84026000|         86223000|         99722000|         72233000|         56151000|         97516000|         83401000|\n|AAAAAAGAASGLPGPVAQGLK                |______________________________ |GAASGLPGPVAQGLKEALVDTLTGILSPVQ |M                 |A                |A                 |L                      |K               |E                |       9|       0|       0|       0|       0|       1|       0|       4|       0|       0|       2|       1|       0|       0|       2|       1|       0|       0|       0|       1|       0|       0|     21|                0| 1747.9581|Q96P70   |Q96P70                |              2|           22|IPO9       |Importin-9                         |yes             |yes               |2;3     | 0.00e+00| 202.440|By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2| 1789100000|    109030000|     72676000|    101320000|     97545000|     77269000|     79290000|    110840000|    110060000|     75937000|     74675000|     68192000|    102570000|     93726000|     72743000|    108550000|     98519000|     70725000|     80125000|     93910000|     91423000|        |                      |  3|3783              |3                |77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;94;95;96;97;98;99;100;101;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116                 |58;59;60;61;62;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;94;95;96;97;98;99;100;101;102;103;104;105;106;107 |         85|                       |          50|         97706000|         81244000|         87682000|         86622000|         77269000|         88508000|         94294000|         96324000|         76939000|         84650000|         73322000|         86806000|         96578000|         80020000|         93344000|         82709000|         75624000|         86506000|         79024000|         76020000|\n|AAAAAAGAGPEMVR                       |______________________________ |MAAAAAAGAGPEMVRGQVFDVGPRYTNLSY |M                 |A                |A                 |V                      |R               |G                |       7|       1|       0|       0|       0|       0|       1|       2|       0|       0|       0|       0|       1|       0|       1|       0|       0|       0|       0|       1|       0|       0|     14|                0| 1241.6187|P28482   |P28482                |              2|           15|MAPK1      |Mitogen-activated protein kinase 1 |yes             |yes               |2       | 0.00e+00| 168.740|By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |                       |By MS/MS               |By MS/MS               |By MS/MS               |                       |By MS/MS               |By MS/MS               |By MS/MS               |                       |                       |                       |                       |                       |                       |                       |                       |             1|             1|             1|             1|            NA|             1|             1|             1|            NA|             2|             1|             1|            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|   72178000|            0|     29646000|     41064000|            0|            0|            0|            0|            0|            0|      1468400|            0|            0|            0|            0|            0|            0|            0|            0|            0|            0|        |                      |  4|1600              |4                |117;118;119;120;121;122;123;124;125;126;127                                                                                                              |108;109;110;111;112;113;114;115;116;117                                                                                                                       |        109|                       |          10|                0|         33141000|         35535000|                0|                0|                0|                0|                0|                0|          1664500|                0|                0|                0|                0|                0|                0|                0|                0|                0|                0|\n|AAAAAAGSGTPREEEGPAGEAAASQPQAPTSVPGAR |______________________________ |AASQPQAPTSVPGARLSRLPLARVKALVKA |M                 |A                |A                 |A                      |R               |L                |      12|       2|       0|       0|       0|       2|       4|       5|       0|       0|       0|       0|       0|       0|       5|       3|       2|       0|       0|       1|       0|       0|     36|                1| 3287.5767|Q9NR33   |Q9NR33                |              2|           37|POLE4      |DNA polymerase epsilon subunit 4   |yes             |yes               |3       | 3.34e-05|  40.328|                       |                       |                       |                       |                       |                       |                       |                       |                       |                       |                       |By MS/MS               |                       |                       |                       |                       |                       |                       |                       |                       |            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|             1|            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|    6961000|            0|            0|            0|            0|            0|            0|            0|            0|            0|            0|            0|      6961000|            0|            0|            0|            0|            0|            0|            0|            0|        |                      |  5|4289              |5                |128                                                                                                                                                      |118                                                                                                                                                           |        118|                       |           1|                0|                0|                0|                0|                0|                0|                0|                0|                0|                0|                0|          5891200|                0|                0|                0|                0|                0|                0|                0|                0|\n\n\n:::\n:::\n\n\n#### Sample annotation table{#sec-annotation_table}\n\nEach row in the annotation table contains information about one\nsample. The columns contain various descriptors about the sample, such\nas the name of the sample or the MS run, the treatment (here the\nspike-in condition), or any other\nbiological or technical information that may impact the data quality\nor the quantification. Without an annotation table, no analysis\ncan be performed. The sample annotations are generated by the\nresearcher. In this example, the annotations are extracted from the\nsample names, although reporting a detailed design of experiments in a\ntable is seen as better practice [@Gatto2023-kk].\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoldata <- data.frame(quantCols = quantCols) |> \n  mutate(sampleId = gsub(\"Intensity.(..)\", \"\\\\1\", quantCols),\n         condition = gsub(\"Intensity.(.).\", \"\\\\1\", quantCols),\n         concentration = concentrations[condition]\n         )\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|quantCols    |sampleId |condition | concentration|\n|:------------|:--------|:---------|-------------:|\n|Intensity.a1 |a1       |a         |           3.0|\n|Intensity.a2 |a2       |a         |           3.0|\n|Intensity.a3 |a3       |a         |           3.0|\n|Intensity.a4 |a4       |a         |           3.0|\n|Intensity.b1 |b1       |b         |           4.5|\n|Intensity.b2 |b2       |b         |           4.5|\n\n\n:::\n:::\n\n\nWe will also extract the E. coli protein identifiers from the FASTA\nfile to later annotate the spike-in proteins which are known to be\ndifferentially abundant.\n\n1. We download the fasta files\n2. We read the text file as vector, one line p\n3. We keep only the protein headers\n4. We extract the proteins identifiers from the headers\n\n\n::: {.cell}\n\n```{.r .cell-code}\necoli <- bfcrpath(bfc, \"https://github.com/statOmics/msqrob2data/raw/refs/heads/main/dda/shen/ecoli_up000000625_7_06_2018.fasta\")\necoli <- readLines(ecoli)\necoli <- ecoli[grepl(\"^>\", ecoli)]\necoli <- gsub(\">sp\\\\|(.*)\\\\|.*\", \"\\\\1\", ecoli)\n```\n:::\n\n\n\n### Convert to QFeatures{#sec-qfeatures}\n\n`msqrob2` is built around the `QFeatures` class. We refer to the [R\nfor mass spectrometry\nbook](https://rformassspectrometry.github.io/book/sec-quant.html) for\na comprehensive description of the class. In a nutshell, the\n`QFeatures` package provides infrastructure to manage and analyse\nquantitative features from mass spectrometry experiments. It is based\non the `SummarizedExperiment` and `MultiAssayExperiment` classes. It\nleverages the hierarchical structure of proteomics experiments: data\nproteins are composed of peptides, themselves produced by spectra.\nEach piece of information in stored in an individual\n`SummarizedExperiment` object, later referred to as a \"set\".\nThroughout the aggregation and processing of these data, the relations\nbetween sets are tracked and recorded, thus allowing users to easily\nnavigate across spectra, peptide and protein quantitative data.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Illustration of the `QFeatures` data class.](figs/QFeatures.png){width=80%}\n:::\n:::\n\n\nThe `readQFeatures()` enables a seamless conversion of tabular data\ninto a `QFeatures` object. We provide the peptide table and the sample\nannotation table. The function will use the `quantCols` column in the\nsample annotation table to understand which columns in `peptides`\ncontain the quantitative values, and automatically link the\ncorresponding sample annotation with the quantitative values. We also\ntell the function to use the `Sequence` column as peptide identifier,\nwhich will be used as rownames. See `?readQFeatures()` for more\ndetails.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(spikein <- QFeatures::readQFeatures(\n  peptides, coldata, name = \"peptides\", fnames = \"Sequence\"\n))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking arguments.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading data as a 'SummarizedExperiment' object.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFormatting sample annotations (colData).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFormatting data as a 'QFeatures' object.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting assay rownames.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 1 set:\n\n [1] peptides: SummarizedExperiment with 32827 rows and 20 columns \n```\n\n\n:::\n:::\n\n\nWe now have a `QFeatures` object with 1 set, called `peptides` (which\nwe specified using the `name` argument). In this toy example, we have\ninformation for 32827 peptides across 45 samples, as\nexpected (recall the [experimental design](#sec-ecoli_experiment)).\n\nThe sample annotations can be retrieved using `colData()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolData(spikein)\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(head(colData(spikein)))\n```\n\n::: {.cell-output-display}\n\n\n|             |quantCols    |sampleId |condition | concentration|\n|:------------|:------------|:--------|:---------|-------------:|\n|Intensity.a1 |Intensity.a1 |a1       |a         |           3.0|\n|Intensity.a2 |Intensity.a2 |a2       |a         |           3.0|\n|Intensity.a3 |Intensity.a3 |a3       |a         |           3.0|\n|Intensity.a4 |Intensity.a4 |a4       |a         |           3.0|\n|Intensity.b1 |Intensity.b1 |b1       |b         |           4.5|\n|Intensity.b2 |Intensity.b2 |b2       |b         |           4.5|\n\n\n:::\n:::\n\n\nWe can get a sample annotation directly using the `$` accessor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(spikein$concentration)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  a   a   a   a   b   b \n3.0 3.0 3.0 3.0 4.5 4.5 \n```\n\n\n:::\n:::\n\n\nWe can extract the `SummarizedExperiment` object for the `peptides`\nset using double bracket subsetting^[A `QFeatures` object can be seen\nas a special list of `SummarizedExperiment` objects.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein[[\"peptides\"]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: SummarizedExperiment \ndim: 32827 20 \nmetadata(0):\nassays(1): ''\nrownames(32827): AAAAAAAAAAAAAAAGAGAGAK AAAAAAAAAAGAAGGR ...\n  YYVTIIDAPGHRDFIK YYYIPQYK\nrowData names(116): Sequence N.term.cleavage.window ...\n  LFQ.intensity.e3 LFQ.intensity.e4\ncolnames(20): Intensity.a1 Intensity.a2 ... Intensity.e3 Intensity.e4\ncolData names(0):\n```\n\n\n:::\n:::\n\n\nBut notice that the sample annotations were not extracted along with\nthe SummarizedExperiment (`colData names(0):`). This can be performed\nusing `getWithColData()`, which extracts the set of interest (like\n`[[]]`) along with all the associated sample annotations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngetWithColData(spikein, \"peptides\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: SummarizedExperiment \ndim: 32827 20 \nmetadata(0):\nassays(1): ''\nrownames(32827): AAAAAAAAAAAAAAAGAGAGAK AAAAAAAAAAGAAGGR ...\n  YYVTIIDAPGHRDFIK YYYIPQYK\nrowData names(116): Sequence N.term.cleavage.window ...\n  LFQ.intensity.e3 LFQ.intensity.e4\ncolnames(20): Intensity.a1 Intensity.a2 ... Intensity.e3 Intensity.e4\ncolData names(4): quantCols sampleId condition concentration\n```\n\n\n:::\n:::\n\n\nThe peptides annotations are available for in the corresponding \n`rowData`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrowData(spikein[[\"peptides\"]])\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(head(rowData(spikein[[\"peptides\"]])))\n```\n\n::: {.cell-output-display}\n\n\n|                                     |Sequence                             |N.term.cleavage.window         |C.term.cleavage.window         |Amino.acid.before |First.amino.acid |Second.amino.acid |Second.last.amino.acid |Last.amino.acid |Amino.acid.after | A.Count| R.Count| N.Count| D.Count| C.Count| Q.Count| E.Count| G.Count| H.Count| I.Count| L.Count| K.Count| M.Count| F.Count| P.Count| S.Count| T.Count| W.Count| Y.Count| V.Count| U.Count| O.Count| Length| Missed.cleavages|      Mass|Proteins |Leading.razor.protein | Start.position| End.position|Gene.names |Protein.names                      |Unique..Groups. |Unique..Proteins. |Charges |      PEP|   Score|Identification.type.a1 |Identification.type.a2 |Identification.type.a3 |Identification.type.a4 |Identification.type.b1 |Identification.type.b2 |Identification.type.b3 |Identification.type.b4 |Identification.type.c1 |Identification.type.c2 |Identification.type.c3 |Identification.type.c4 |Identification.type.d1 |Identification.type.d2 |Identification.type.d3 |Identification.type.d4 |Identification.type.e1 |Identification.type.e2 |Identification.type.e3 |Identification.type.e4 | Experiment.a1| Experiment.a2| Experiment.a3| Experiment.a4| Experiment.b1| Experiment.b2| Experiment.b3| Experiment.b4| Experiment.c1| Experiment.c2| Experiment.c3| Experiment.c4| Experiment.d1| Experiment.d2| Experiment.d3| Experiment.d4| Experiment.e1| Experiment.e2| Experiment.e3| Experiment.e4|  Intensity|Reverse |Potential.contaminant | id|Protein.group.IDs |Mod..peptide.IDs |Evidence.IDs                                                                                                                                             |MS.MS.IDs                                                                                                                                                     | Best.MS.MS|Oxidation..M..site.IDs | MS.MS.Count| LFQ.intensity.a1| LFQ.intensity.a2| LFQ.intensity.a3| LFQ.intensity.a4| LFQ.intensity.b1| LFQ.intensity.b2| LFQ.intensity.b3| LFQ.intensity.b4| LFQ.intensity.c1| LFQ.intensity.c2| LFQ.intensity.c3| LFQ.intensity.c4| LFQ.intensity.d1| LFQ.intensity.d2| LFQ.intensity.d3| LFQ.intensity.d4| LFQ.intensity.e1| LFQ.intensity.e2| LFQ.intensity.e3| LFQ.intensity.e4|\n|:------------------------------------|:------------------------------------|:------------------------------|:------------------------------|:-----------------|:----------------|:-----------------|:----------------------|:---------------|:----------------|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|------:|----------------:|---------:|:--------|:---------------------|--------------:|------------:|:----------|:----------------------------------|:---------------|:-----------------|:-------|--------:|-------:|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|----------:|:-------|:---------------------|--:|:-----------------|:----------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------|----------:|:----------------------|-----------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|\n|AAAAAAAAAAAAAAAGAGAGAK               |AAAAAAAAAAAAAAAGAGAGAK               |QSRFQVDLVSENAGRAAAAAAAAAAAAAAA |AAAAAAAAGAGAGAKQTPADGEASGESEPA |R                 |A                |A                 |A                      |K               |Q                |      18|       0|       0|       0|       0|       0|       0|       3|       0|       0|       0|       1|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|     22|                0| 1595.8380|P55011   |P55011                |             93|          114|SLC12A2    |Solute carrier family 12 member 2  |yes             |yes               |2;3     | 0.00e+00|  98.407|By matching            |                       |                       |                       |                       |                       |                       |By MS/MS               |By MS/MS               |By MS/MS               |                       |By MS/MS               |                       |By matching            |By matching            |                       |                       |                       |By matching            |                       |             1|            NA|            NA|            NA|            NA|            NA|            NA|             1|             1|             1|            NA|             1|            NA|             1|             1|            NA|            NA|            NA|             1|            NA|   39754000|        |                      |  0|2115              |0                |0;1;2;3;4;5;6;7                                                                                                                                          |0;1;2;3                                                                                                                                                       |          2|                       |           2|          5715600|                0|                0|                0|                0|                0|                0|                0|          4324900|          8047900|                0|                0|                0|          9420400|          5673000|                0|                0|                0|          5761500|                0|\n|AAAAAAAAAAGAAGGR                     |AAAAAAAAAAGAAGGR                     |______________________________ |AAAAAAAAAGAAGGRGSGPGRRRHLVPGAG |M                 |A                |A                 |G                      |R               |G                |      12|       1|       0|       0|       0|       0|       0|       3|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|     16|                0| 1197.6214|Q86U42   |Q86U42                |              2|           17|PABPN1     |Polyadenylate-binding protein 2    |yes             |yes               |2       | 0.00e+00| 275.000|By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By matching            |By MS/MS               |By MS/MS               |By MS/MS               |                       |By MS/MS               |By MS/MS               |By MS/MS               |By matching            |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |                       |By MS/MS               |By MS/MS               |             1|             1|             1|             1|             1|             1|             1|             1|            NA|             1|             1|             1|             1|             1|             1|             1|             1|            NA|             1|             1| 1211200000|        |                      |  1|3262              |1                |8;9;10;11;12;13;14;15;16;17;18;19;20;21;22;23;24;25                                                                                                      |4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19                                                                                                                     |          9|                       |          15|         68748000|         59998000|         74863000|         70216000|         57211000|         63173000|         69374000|         69165000|                0|         52244000|         66990000|         62028000|         62554000|         55618000|         65050000|         63171000|         55715000|                0|         62578000|         58656000|\n|AAAAAAALQAK                          |AAAAAAALQAK                          |TILRQARNHKLRVDKAAAAAAALQAKSDEK |RVDKAAAAAAALQAKSDEKAAVAGKKPVVG |K                 |A                |A                 |A                      |K               |S                |       8|       0|       0|       0|       0|       1|       0|       0|       0|       0|       1|       1|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|     11|                0|  955.5451|P36578   |P36578                |            354|          364|RPL4       |60S ribosomal protein L4           |yes             |yes               |2       | 1.00e-07| 182.680|By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |             2|             3|             4|             2|             3|             2|             2|             2|             3|             3|             3|             2|             3|             2|             3|             2|             2|             3|             3|             2| 1829100000|        |                      |  2|1762              |2                |26;27;28;29;30;31;32;33;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50;51;52;53;54;55;56;57;58;59;60;61;62;63;64;65;66;67;68;69;70;71;72;73;74;75;76 |20;21;22;23;24;25;26;27;28;29;30;31;32;33;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50;51;52;53;54;55;56;57                                             |         29|                       |          30|        116060000|         63444000|         99420000|        111980000|         33394000|         74449000|         79944000|        109450000|         85332000|         94299000|        110730000|         91926000|         74751000|         84026000|         86223000|         99722000|         72233000|         56151000|         97516000|         83401000|\n|AAAAAAGAASGLPGPVAQGLK                |AAAAAAGAASGLPGPVAQGLK                |______________________________ |GAASGLPGPVAQGLKEALVDTLTGILSPVQ |M                 |A                |A                 |L                      |K               |E                |       9|       0|       0|       0|       0|       1|       0|       4|       0|       0|       2|       1|       0|       0|       2|       1|       0|       0|       0|       1|       0|       0|     21|                0| 1747.9581|Q96P70   |Q96P70                |              2|           22|IPO9       |Importin-9                         |yes             |yes               |2;3     | 0.00e+00| 202.440|By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2|             2| 1789100000|        |                      |  3|3783              |3                |77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;94;95;96;97;98;99;100;101;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116                 |58;59;60;61;62;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;94;95;96;97;98;99;100;101;102;103;104;105;106;107 |         85|                       |          50|         97706000|         81244000|         87682000|         86622000|         77269000|         88508000|         94294000|         96324000|         76939000|         84650000|         73322000|         86806000|         96578000|         80020000|         93344000|         82709000|         75624000|         86506000|         79024000|         76020000|\n|AAAAAAGAGPEMVR                       |AAAAAAGAGPEMVR                       |______________________________ |MAAAAAAGAGPEMVRGQVFDVGPRYTNLSY |M                 |A                |A                 |V                      |R               |G                |       7|       1|       0|       0|       0|       0|       1|       2|       0|       0|       0|       0|       1|       0|       1|       0|       0|       0|       0|       1|       0|       0|     14|                0| 1241.6187|P28482   |P28482                |              2|           15|MAPK1      |Mitogen-activated protein kinase 1 |yes             |yes               |2       | 0.00e+00| 168.740|By MS/MS               |By MS/MS               |By MS/MS               |By MS/MS               |                       |By MS/MS               |By MS/MS               |By MS/MS               |                       |By MS/MS               |By MS/MS               |By MS/MS               |                       |                       |                       |                       |                       |                       |                       |                       |             1|             1|             1|             1|            NA|             1|             1|             1|            NA|             2|             1|             1|            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|   72178000|        |                      |  4|1600              |4                |117;118;119;120;121;122;123;124;125;126;127                                                                                                              |108;109;110;111;112;113;114;115;116;117                                                                                                                       |        109|                       |          10|                0|         33141000|         35535000|                0|                0|                0|                0|                0|                0|          1664500|                0|                0|                0|                0|                0|                0|                0|                0|                0|                0|\n|AAAAAAGSGTPREEEGPAGEAAASQPQAPTSVPGAR |AAAAAAGSGTPREEEGPAGEAAASQPQAPTSVPGAR |______________________________ |AASQPQAPTSVPGARLSRLPLARVKALVKA |M                 |A                |A                 |A                      |R               |L                |      12|       2|       0|       0|       0|       2|       4|       5|       0|       0|       0|       0|       0|       0|       5|       3|       2|       0|       0|       1|       0|       0|     36|                1| 3287.5767|Q9NR33   |Q9NR33                |              2|           37|POLE4      |DNA polymerase epsilon subunit 4   |yes             |yes               |3       | 3.34e-05|  40.328|                       |                       |                       |                       |                       |                       |                       |                       |                       |                       |                       |By MS/MS               |                       |                       |                       |                       |                       |                       |                       |                       |            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|             1|            NA|            NA|            NA|            NA|            NA|            NA|            NA|            NA|    6961000|        |                      |  5|4289              |5                |128                                                                                                                                                      |118                                                                                                                                                           |        118|                       |           1|                0|                0|                0|                0|                0|                0|                0|                0|                0|                0|                0|          5891200|                0|                0|                0|                0|                0|                0|                0|                0|\n\n\n:::\n:::\n\n\nWe can also retrieve the quantitative values for each set using \n`assays()`. Here we only show the first 5 rows and columns of the intensity matrix. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nassay(spikein[[1]])[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       Intensity.a1 Intensity.a2 Intensity.a3 Intensity.a4\nAAAAAAAAAAAAAAAGAGAGAK      6378300            0            0            0\nAAAAAAAAAAGAAGGR           76718000     53670000     86511000     79070000\nAAAAAAALQAK               129520000     56753000    114890000    126100000\nAAAAAAGAASGLPGPVAQGLK     109030000     72676000    101320000     97545000\nAAAAAAGAGPEMVR                    0     29646000     41064000            0\n                       Intensity.b1\nAAAAAAAAAAAAAAAGAGAGAK            0\nAAAAAAAAAAGAAGGR           57211000\nAAAAAAALQAK                33394000\nAAAAAAGAASGLPGPVAQGLK      77269000\nAAAAAAGAGPEMVR                    0\n```\n\n\n:::\n:::\n\n\n## Data preprocessing{#sec-basic_preprocess}\n\nSince we have a `QFeatures` object, we can directly make use of\n`QFeatures`' data preprocessing functionality^[see also the [R for\nmass spectrometry\nbook](https://rformassspectrometry.github.io/book/sec-quant.html)]. A\nmajor advantage of `QFeatures` is it provides the power to build\nhighly modular workflows, where each step is carried out by a\ndedicated function with a large choice of available methods and\nparameters. This means that users can adapt the workflow to their\nspecific use case and their specific needs.\n\n### Encoding missing values{#sec-encode_missing}\n\nThe first preprocessing step is to correctly encode the missing\nvalues. It is important that missing values are encoded using `NA`.\nFor instance, non-observed values should not be\nencoded with a zero because true zeros (the proteomic feature\nis absent from the sample) cannot be distinguished from technical\nzeros (the feature was missed by the instrument or could not be\nidentified). We therefore replace any zero in the quantitative data\nwith an `NA`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein <- zeroIsNA(spikein, names(spikein))\n```\n:::\n\n\nNote that `msqrob2` can handle missing data without having to rely on\nhard-to-verify imputation assumptions, which is our general recommendation. However, `msqrob2` does not\nprevent users from using imputation, which can be performed with\n`impute()` from the `QFeatures` package. Below, we show how one could\nperform KNN imputation^[We will however not evaluate the code in this\ntutorial as our general advice is to avoid imputation. To run the\ncode, you'll need to uncomment it first.] (see `?impute` for more\noptions).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# spikein <- impute(\n#   spikein, method = \"knn\",\n#   i = names(spikein), name = paste0(names(spikein), \"_imput\")\n# )\n```\n:::\n\n\n### Log2 transformation{#sec-log2}\n\nWe typically start a MS-based proteomics data analysis by log2 transforming the intensities. We illustrate the rationale\nusing the spike-in data. For this, we perform a short data\nmanipulation pipeline:\n\n1. We use `longForm()` to convert the `QFeatures` object into a long\ntable, where each row contains the quantitative information about\none observation, in which column, row and set it was found. Long\ntables are particularly useful for manipulating data with the\n`tidyverse` ecosystem, namely with `ggplot2` for visualisation.\n`longForm()` also allows to include annotations, and we here\ninclude `Mixture` and `TechRepMixture` for filtering and colouring.\n2. `longForm()` returns a `DataFrame` which we convert to a\n`data.frame`.\n3. We filter the data to keep only the data from peptide AEMSEYLFDK.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- longForm(spikein, colvars = colnames(colData(spikein))) |> ## 1.\n  data.frame() |> ## 2.\n  filter(rowname == \"AEMSEYLFDK\") ## 3.\n```\n:::\n\n\nNext, we visualise the data using `ggplot2`. We will show the\nintensities and log2-intensities for one of the peptides, AALEELVK, in\nfunction of the known E. coli spike-in concentration. We first define a common\nplot from which we generate two plots, one without and the other with\nlog2 transformation of the quantitative values.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![MS-data is heteroskedastic, but log transformation achieves homoskedasticity. Peptide intensities (left) or log2 intensities (right) are plotted in function of spike-in concentration.](01-basics_files/figure-html/basics_log_plot-1.png){width=672}\n:::\n:::\n\n\nWe can see that the variation around the mean for each concentration slightly increases as the mean increases. This is known as heteroskedasticity.\nWe will later see that `msqrob2` assumes that variance of the error\nis equal across the different conditions. Upon,\nlog2-transformation we can see that the problem of unequal variability\nis solved.\n\nAnother advantages of log2-transformation is that it provides a scale\nthat directly relates to biological interpretation. In biology, a\nchange induced by some condition often results in a fold change in\nconcentration. Interestingly, the log2 fold change (logFC), which is\nthe log2 of the ratio between two conditions, is identical to the\ndifference between the log of each condition.\n\n$$log_2FC_{b-a} = log_2b - log_2a = log_2 \\frac{b}{a}$$\n\nThis simplifies the modelling since the effects are now additive and\nit provides a straightforward interpretation, i.e. a logFC of 1 means that the\nabundances are on average $2\\times$ higher in $b$ than in $a$, a logFC of 2\nmeans an average increase of $4\\times$, for instance.\nAlso, note that the averages calculated at the log2-scale have the interpretation of log2-transformed geometric means. \n\nWe perform log2-transformation with `logTransform()` from the\n`QFeatures` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein <- logTransform(\n  spikein, \"peptides\", name = \"peptides_log\", base = 2\n)\n```\n:::\n\n\n### Peptide filtering{#sec-filter}\n\nFiltering removes low-quality and unreliable peptides that would\notherwise introduce noise and artefacts in the data. There are many\npossible criteria for peptide filtering:\n\n- Reverse sequences\n- Only identified by modification site (only modified peptides \ndetected)\n- Razor peptides: non-unique peptides assigned to the protein group \nwith the most other peptides \n- Contaminants\n- Peptides with few identifications\n- Proteins that are only identified with one or a few peptides\n- FDR of identification\n- ...\n\nIt is important that the filtering criteria are not distorting the distribution of the test statistics in the downstream analysis for features that are non-DA. It can be shown that filtering will not induce bias results when the filtering criterion is independent of test statistic. Here, the test statistics are based on the average difference between the log2-transformed intensities (effect size) and their corresponding standard error, which is a function of the residual standard deviation. The criteria that we proposed above are all based on the results of the identification step, hence, they are independent of the downstream test statistics that will be used to prioritize DA proteins. \n\nWe use `filterFeatures()` to perform the filtering. It uses\ninformation from the `rowData` and a formula to generate a filter for\neach feature (row) in each set across the object. If the filter\nreturns `TRUE`, the corresponding row is retained, otherwise it is\nremoved. Defining a filter through a formula offers a flexible\napproach, allowing for any customised filter. This dataset requires an\nextensive PSM filtering, which is an ideal use case to demonstrate the\ncustomisation of a filtering workflow.\n\n#### Remove failed protein inference\n\nWe remove peptides that could not be mapped to a protein. We also \nremove peptides that cannot be uniquely mapped to a single proteins\nbecause its sequence is shared across multiple proteins. This often\noccurs for homologs or for proteins that share similar functional\ndomains. Shared peptides are often mapped to protein groups, which are\nthe set of proteins that share the given peptides. Protein groups are\nencoded by appending the constituting protein identifiers, separated\nby a `\";\"`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein <- filterFeatures(\n  spikein, ~ Proteins != \"\" & ## Remove failed protein inference\n    !grepl(\";\", Proteins)) ## Remove protein groups\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n'Proteins' found in 2 out of 2 assay(s).\n```\n\n\n:::\n:::\n\n\n#### Remove reverse sequences and contaminants\n\nWe now remove the peptides that map to decoy sequences or to\ncontaminants proteins. Decoy peptides, which consist of fake peptide\nsequences generated by reversing a real amino-acid sequence, are used\nduring the database search to mitigating the number of random-hit PSM,\nhence mitigating misidentification. Contaminant proteins are proteins\nknown to be artificially incorporated during the experiment, but that\nare irrelevant to the biological system under study. Typical\ncontaminants are human or animal keratins (deposited by the\nexperimenter) or trypsin (used for protein digestion). It is important\nto remove these peptides before performing statistical modelling,\notherwise these proteins will be accounted for during the multiple\ntest adjustment, which will cause an unnecessary decrease of\nstatistical power. Note, that the column name of the contaminants in the peptides file differs according to the MaxQuant version. In our peptide.txt file decoys and contaminants are indicated with a \"+\" character in the column `Reverse` and `Potential.contaminant`, respectively. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein <- filterFeatures(spikein, ~ Reverse != \"+\" & ## Remove decoys\n                            Potential.contaminant != \"+\") ## Remove contaminants\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n'Reverse' found in 2 out of 2 assay(s).'Potential.contaminant' found in 2 out of 2 assay(s).\n```\n\n\n:::\n:::\n\n\n#### Remove highly missing peptides\n\nThe data are characterised by a high proportion of missing values as\nreported by `nNA()` from the `QFeatures` package. The function\ncomputes the number and the proportion of missing values across\npeptides, samples or for the whole data set and return a list of three\ntables called `nNArows`, `nNAcols`, and `nNA`, respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnNaRes <- nNA(spikein, \"peptides\")\nrange(nNaRes$nNAcols$pNA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2196928 0.2649294\n```\n\n\n:::\n:::\n\n\nThe samples contain between 22%\nand 26.5% missing values. The\nmissingness within each peptide is more variable, with most peptides\nfound accross all samples (`nNA` is 0) and other that could not be\nquantified in any sample (`nNA` is 20), as depicted\nby the histogram below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(nNaRes$nNArows) |> \n  ggplot() +\n  aes(x = nNA) +\n  geom_histogram(bins = 15) +\n  ggtitle(\"Number of missing values for each peptide\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](01-basics_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nWe keep peptides that were observed at last 4 times out of the $n\n= 20$ samples, so that we can estimate the peptide characteristics. We tolerate the following proportion of NAs:\n$\\text{pNA} = \\frac{(n - 4)}{n} = 0.8$, so we keep peptides that\nare observed in at least 20% of the samples, which corresponds to one treatment condition. This is an arbitrary\nvalue that may need to be adjusted depending on the experiment and the\ndata set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnObs <- 4\nn <- ncol(spikein[[\"peptides_log\"]])\n(spikein <- filterNA(spikein, i = \"peptides_log\", pNA = (n - nObs) / n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 2 sets:\n\n [1] peptides: SummarizedExperiment with 30661 rows and 20 columns \n [2] peptides_log: SummarizedExperiment with 27850 rows and 20 columns \n```\n\n\n:::\n:::\n\n\nWe keep 27850 peptides upon filtering.\n\n\n### Identifications per sample \n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein[,,\"peptides\"] |> \n  longForm(colvars = colnames(colData(spikein)), \n           rowvars= c(\"Sequence\", \n                      \"Proteins\")) |>\n  data.frame() |>\n  filter(!is.na(value)) |>\n  group_by(condition, sampleId) |>\n  summarise(peptides = length(unique(Sequence)),\n            Proteins = length(unique(Proteins))) |> \n  pivot_longer(-(1:2),\n               names_to = \"Feature\",\n               values_to = \"IDs\") |> \n  ggplot(aes(x = sampleId, y = IDs, fill = condition)) +\n  geom_col() +\n  #scale_fill_observable() +\n  facet_wrap(~Feature,\n             scales = \"free_y\") +\n  labs(title = \"Peptide and protein group identificiations per sample\",\n       x = \"Sample\",\n       y = \"Identifications\") +\n  theme_bw() + \n  theme(axis.text.x = element_text(angle = 90))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 20 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has regrouped the output.\nℹ Summaries were computed grouped by condition and sampleId.\nℹ Output is grouped by condition.\nℹ Use `summarise(.groups = \"drop_last\")` to silence this message.\nℹ Use `summarise(.by = c(condition, sampleId))` for per-operation grouping\n  (`?dplyr::dplyr_by`) instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](01-basics_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n### Normalisation{#sec-norm}\n\nThe most common objective of MS-based proteomics experiments is to\nunderstand the biological changes in protein abundance between\nexperimental conditions. However, changes in measurements between\ngroups can be caused due to technical factors. For instance, there are\nsystematic fluctuations from run-to-run that shift the measured\nintensity distribution. We can this explore as follows:\n\n1. We extract the sets containing the log transformed data. This is \nperformed using `QFeatures`' 3-way subsetting^[We will explain this\nwith more details at the end of the [summarisation step](#sec-summarisation)].\n2. We use `longForm()` to convert the `QFeatures` object into a long\ntable, including `condition` and `concentration` for filtering and\ncolouring.\n3. We visualise the density of the quantitative values within each\nsample. We colour each sample based on its spike-in condition.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein[, , \"peptides_log\"] |> ## 1.\n  longForm(colvars = c(\"concentration\", \"condition\")) |> ## 2.\n  data.frame() |> \n  ggplot() + ## 3.\n  aes(x = value,\n      colour = condition,\n      group = colname) +\n  geom_density() +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 20 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 92133 rows containing non-finite outside the scale range\n(`stat_density()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Intensity distribution for all samples before normalisation.](01-basics_files/figure-html/basics_before_norm-1.png){width=672}\n:::\n:::\n\n\nEven in this clean synthetic data set (same background with a small\npercentage of E. coli lysate), the marginal peptide intensity\ndistributions across samples are not well aligned. Ignoring this\neffect will increase the noise and reduce the statistical power of the\nexperiment, and may also, in case of unbalanced designs, introduce\nconfounding effects that will bias the results.\n\nTherefore, normalisation will transform the data to make the intensities of the \ndifferent samples comparable, e.g. by centering the distributions using the \nmedian, so that the distributions better coincide and overlap.\n\nSubtracting the sample median at the log scale from each precursor \nlog2 intensity, basically boils down to calculating log-ratio's between \nthe precursor intensity and its sample median. \n\nHere, we will use the Median of Ratios method of DESeq2, which was originally \ndeveloped for RNA-seq data analysis and can also correct for differences in \ncomposition of the proteomes in the different samples. \nThe method first calculates pseudo-reference sample (row-wise mean of log2 \nintensities, which corresponds to the log2 transformed geometric mean).\nTHen calculates log2 ratios of each sample w.r.t. the pseudo-reference.\nFinally the column wise median of these log2 ratios is taken to obtain \nthe sample based normalisation factor on the log2 scale.\nThis procedure is implemented in the `msqrob2` function `nfLogMedianOfRatios`.\n\n1. We calculate the log transformed normalisation factor from the Median of \nRatios method\n2.  Subtract these log2-norm factors from the intensities of each corresponding \ncolumn of the assay data and store the result in the new assay peptides_norm. \n(We adopt the sweep function to the `peptides_log` assay of the spikein \nQFeatures object with as statistic the log2 normfactor `STATS = nfLog` the \ndefault function `FUN = \"-\"`, `MARGIN = 2` to substract the column wise log2 \nnorm factor from each entry of the corresponding assay data).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnfLog <- nfLogMedianOfRatios(spikein, \"peptides_log\") #1.\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThis function aims to calculate norm factors on a log scale, \n          the input data are assumed to be on the log-scale!\n```\n\n\n:::\n\n```{.r .cell-code}\nspikein <- sweep( #Subtract log2 norm factor column-by-column (MARGIN = 2) #2.\n  spikein,\n  MARGIN = 2,\n  STATS = nfLog,\n  i = \"peptides_log\",\n  name = \"peptides_norm\"\n)\n```\n:::\n\n\nNote that users can also use all normalisation functions that are provided in \nQFeatures, i.e. by replacing the sweep function by `QFeatures::normalize`.\n\nFormally, the function applies the following operation on each sample\n$i$ across all PSMs $p$:\n\n$$\ny_{ip}^{\\text{norm}} = y_{ip} - \\hat{\\mu}_i\n$$\n\nwith $y_ip$ the log2-transformed intensities and $\\hat{\\mu}_i$ the \nlog2-transformed norm factor. Upon normalisation, we can see that the \ndistribution of the $y_{ip}^{\\text{norm}}$ nicely overlap \n(using the same code as above).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein[, , \"peptides_norm\"] |> ## 1.\n  longForm(colvars = c( \"concentration\", \"condition\")) |> ## 2.\n  data.frame() |> \n  ggplot() + ## 3.\n  aes(x = value,\n      colour = condition,\n      group = colname) +\n  geom_density()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 40 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 92133 rows containing non-finite outside the scale range\n(`stat_density()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Intensity distribution for all samples after normalisation.](01-basics_files/figure-html/basics_after_norm-1.png){width=672}\n:::\n:::\n\n\nBeware there exist numerous types of normalisation methods (see\n`?normalize`) and which method to use may be data set dependent. For\ninstance, some data set may show low overlap of distribution tails\nupon normalisation indicating that a simple shift is not sufficient.\nIn micro-array literature, quantile normalisation is used to force the\nmedian and all other quantiles to be equal across samples, but in\nproteomics, quantile normalisation often introduces artifacts due to a\ndifference in missing peptides across samples (c.f. [Challenges]).\n\nIt is important to understand that most normalisation procedures\nassume that the majority of the proteins do not change across\nconditions and only a small proportion of the proteins are\ndifferentially abundant. This assumption may not be valid in poorly\ndesigned spike-in studies [@O-Brien2024-lr] or for pull-down studies,\nfor example. Dedicated normalisation strategies are then required. \n\n### Summarisation{#sec-summarisation}\n\nThe objective of summarisation (also referred to as aggregation) is to\nsummarise the peptide-level intensities into a protein expression value.\nWe illustrate the motivation for summarisation using all peptide-level data for\none of the E. coli proteins. We also focus on the lowest (a) and highest (e)\nspike-in conditions. The different peptides are shown on the\nx axis and plot their log2 normalised intensities across samples on y\naxis. All the points belonging to the same sample are linked through a\ngrey line.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 40 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 20 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Peptide-level data for E. coli protein P0AEE5. The data set has been subset for samples with condition a and e. Each point represents a measured peptide within a sample, and the points are connected when they belong to the same sample.](01-basics_files/figure-html/basics_summarise-1.png){width=576}\n:::\n:::\n\n\n1. We can see that data for a protein can consist of many peptides, \nhence the need for summarisation.\n2. We observe that different peptides have different intensities \nwithin the same sample (same line). This is because different\npeptides have different properties and hence differ in their ionisation\nefficiency, which will influence the detectability in the MS \n([Challenges]).\n3. The peptide identification are inconsistent between groups of \ninterest. We can see the low-concentration group (condition a, red)\ndisplay more missing values than the high-concentration group\n(condition e, blue). Moreover, which value is missing depends on\nthe peptide characteristics. All the peptides found in the\nlow-concentration group are the most intense peptides in the high\nconcentration group.\n4. We also often find outliers, for instance, due to misidentification or fluctuations during MS acquisition.\n5. These data also suggest pseudo-replication. The peptide intensities\nin one same sample (dots connected by a line) are correlated, i.e.\nthey more alike than the peptide intensities between samples\n(the lines do not perfectly align). \n\nThe fact that different peptides have different intensities (2.), may\nbe inconsistently identified (3.) and/or quantified (4.), and show\nsample correlations (5.) can lead to bias if we use simple\nsummarisation approaches such as summing or averaging the peptide\nintensities for each sample. Instead, we will resort to more advanced\nsummarisation approaches to accommodate for these issues.\n\nHere, we summarise the peptide-level data into protein intensities\nthrough the robust summarisation approach [@Sticker2020-rl] which is a\nmodel approach that estimates for each protein $P$ separately:\n\n$$\ny_{ip} = \\beta_p^\\text{pep} + \\beta_i^\\text{samp} + \\epsilon_{ip}\n$$\n\nwhere $y_{ip}$ is the log-normalised peptide intensity for peptide $p$\nbelonging to protein $P$ in sample $i$. $\\beta_p^\\text{pep}$ is the\naverage effect of peptide $p$, which account for the fact that\ndifferent peptide yield different baseline intensities (see issue 2.\nabove). $\\beta_i^\\text{samp}$ is the average effect of sample $i$. In\nother words, it provides the estimated log2-transformed and normalised intensity of protein $P$ in\nsample $i$ corrected for the peptide effect, which will be used as the summarised protein value.\n$\\epsilon_{ip}$ is the residual effect that cannot be explained by the\naverage sample and peptide effects. The method is called robust\nsummarisation because the estimation process will minimize $\\epsilon$\nusing a robust estimator^[During robust estimation, the least squared\nerror minimisation, that is minimising $\\sum_i\\mathbf{\\epsilon}^2_i$, is\niteratively reweighted using Huber weights, i.e. $\\sum_iw_i\\mathbf{\\epsilon}^2_i$. This is internally\nperformed using `MASS::rlm()`.] that will down-weigh extreme values,\neffectively tackling issue 4.\n\n`aggregateFeatures()` streamlines summarisation. It requires the name\nof a `rowData` column to group the peptides into proteins (or\nprotein groups), here `Proteins`. We provide the summarisation\napproach through the `fun` argument. Other summarisation methods\nare available from the `MsCoreUtils` package, see `?aggregateFeatures`\nfor a comprehensive list. The function will return a `QFeatures`\nobject with a new set that we called `proteins`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(spikein <- aggregateFeatures(\n  spikein, i = \"peptides_norm\", \n  name = \"proteins\",\n  fcol = \"Proteins\", \n  fun = MsCoreUtils::robustSummary,\n  na.rm = TRUE\n))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nYour quantitative and row data contain missing values. Please read the\nrelevant section(s) in the aggregateFeatures manual page regarding the\neffects of missing values on data aggregation.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAggregated: 1/1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 4 sets:\n\n [1] peptides: SummarizedExperiment with 30661 rows and 20 columns \n [2] peptides_log: SummarizedExperiment with 27850 rows and 20 columns \n [3] peptides_norm: SummarizedExperiment with 27850 rows and 20 columns \n [4] proteins: SummarizedExperiment with 4592 rows and 20 columns \n```\n\n\n:::\n:::\n\n\nNote that all the links between peptides and proteins are kept^[In\nfact, this is also true for the previous transformation where the\npeptides are linked across sets.]. This come particularly handy when\nwe want to extract all the data from one protein, P0AEE5 for\ninstance. This can be performed using the 3-way indexing. Every\n`QFeatures` object contains one or more sets, each characterised by\nmultiple rows (peptides or proteins) and multiple columns (samples).\nTherefore, `QFeatures` can subset data based on one or more of these\nindices, `data[set_k, feature_i, sample_j]`. The first entry will\nsubset particular features. This can be the name of a peptide (e.g.\n`DGQIQFVLLK`) or the name of a protein (`P0AEE5`).\nThe second entry selects the samples columns of interest. The third\nentry selects the sets of interest. If an entry is left blank, all the\ncorresponding features, samples or sets will be selected. Let's\nextract all the data (all samples and all sets) related to the E. coli protein\n(`P0AEE5`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein[\"P0AEE5\", , ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 4 sets:\n\n [1] peptides: SummarizedExperiment with 16 rows and 20 columns \n [2] peptides_log: SummarizedExperiment with 16 rows and 20 columns \n [3] peptides_norm: SummarizedExperiment with 16 rows and 20 columns \n [4] proteins: SummarizedExperiment with 1 rows and 20 columns \n```\n\n\n:::\n:::\n\n\nThe function extracted one protein and its 16 related peptides. This\nfunctionality is particularly useful for plotting and exploring the\nchanges induces by the data processing. For instance:\n\n1. We use the `QFeatures` subsetting functionality to keep only the \ndata for the E. coli protein P0AEE5 and the sets before and after \nsummarisation.\n2. We use `longForm()` to convert the object for plotting.\n3. We plot the intensities for each sample, facetting by set and\ncolouring by experimental condition, linking dots from the same\npeptide or protein with a line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein[\"P0AEE5\", , c(\"peptides_norm\", \"proteins\")] |> ## 1.\n  longForm(colvars = colnames(colData(spikein))) |> ## 2.\n  data.frame() |>\n  ggplot() + ## 3.\n  aes(x = colname, \n      y = value,\n      group = rowname) +\n  geom_line(linewidth = 0.1) +\n  geom_point(aes(colour = condition)) +\n  facet_grid(~ assay) +\n  theme(axis.text.x = element_blank()) +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 40 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 25 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 45 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Data for protein P0AEE5 before and after summarisation](01-basics_files/figure-html/basics_summarisation_results-1.png){width=672}\n:::\n:::\n\n\nThe data processing is complete.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(spikein)\n```\n\n::: {.cell-output-display}\n![Overview of the `QFeatures` object and its processed sets.](01-basics_files/figure-html/basics_qfeatures_plot-1.png){width=672}\n:::\n:::\n\n\n## Data exploration{#sec_data_exploration}\n\nData exploration aims to highlight the main sources of variation in\nthe data prior to data modelling and can pinpoint to outlying or\noff-behaving samples. A common approach for data exploration is to\nperform dimension reduction, such as Multi Dimensional Scaling (MDS).\nWe will first extract the set to explore along the sample annotations\n(used for plot colouring).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nse <- getWithColData(spikein, \"proteins\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n:::\n\n\nWe then use the `scater` package to compute and plot the PCA. For\ntechnical reasons, it requires `SingleCellExperiment` class object,\nbut these can easily be generated from a `SummarizedExperiment`\nobject. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"scater\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: SingleCellExperiment\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: scuttle\n```\n\n\n:::\n\n```{.r .cell-code}\nse <- runMDS(as(se, \"SingleCellExperiment\"), exprs_values = 1)\n```\n:::\n\n\nWe can now explore the data structure while coloring for the factor of\ninterest, here `condition`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotMDS(se, colour_by = \"condition\") \n```\n\n::: {.cell-output-display}\n![MDS visualisation of the spike-in data set. Each point represents a sample and is coloured by the spike-in condiion.](01-basics_files/figure-html/basics_mds-1.png){width=768}\n:::\n:::\n\n\nThis plot reveals interesting information. First, we see that the\nsamples are nicely separated according to their spike-in condition.\nInterestingly, the conditions are sorted by the concentration^[Recall\nthat a to e condition imply low to high concentration.]. We also see\nsome structure in the second dimension. This would probe us to contact\nthe lab where the data were collected to ask if the samples were\nobtained in batches. It demonstrates the power of data exploration for\nQC.\n\n## Data modelling{#sec-modelling}\n\nWe model the preprocessed data to answer biologically relevant\nquestions. As described above, each sample has been synthetically\ncreated to contain a constant human background where E. coli lysates\nwere spiked in at five different concentration. Each sample\npreparation has been replicated four times. \nSo, the key question is \"can our\nmodel retrieve the proteins that have been spiked in across the\nconditions?\" Moreover, since we know the expected protein abundance in\neach sample, we will also be able to assess how accurate the model can\nestimate the average fold changes between spike-in conditions.\n\n### Sources of variation\n\nIn this experimental design, we can model a single source of variation: \nspike-in concentration^[Note that we have the spike-in concentration\nencoded in two ways. `concentration` is encoded as a numerical value\nand provides the actual concentration amount in fmol/µL. `condition`\nis encoded as a factor, meaning that every concentration is regarded\nas an independent group. We will use the latter encoding as most\ncommon research questions consist of group-wise comparisons. The\nmodelling of concentration as a numeric will be discussed in a\n[dedicated section](#sec-numeric_model)]. All remaining sources of\nvariability, e.g. pipetting errors, MS run to run variability, etc\nwill be lumped in the residual variability (error term).\n\n**Spike-in condition effects**: we model the source of variation\ninduced by the experimental treatment of interest as a fixed\neffect, which we consider non-random, i.e. the treatment effect is\nassumed to be the same in repeated experiments, but it is unknown\nand has to be estimated.\n\nWhen modelling a typical label-free experiment at the protein level, \nthe model boils down to the following linear model:\n\n$$\ny_i = \\mathbf{x}^T_i \\boldsymbol{\\beta} + \\epsilon_i\n$$\n\nwith $y_i$ the $\\log_2$-normalised and summarised protein intensities in sample $i$;\n$\\mathbf{x}_i$ a vector with the covariate pattern for the sample\nencoding the intercept, spike-in condition^[Categorical\nvariables are encoded using dummy coding.], or other experimental factors; $\\boldsymbol{\\beta}$ the\nvector of parameters that model the association between the covariates\nand the outcome; and $\\epsilon_i$ the residuals reflecting variation\nthat is not captured by the fixed effects. Note that $\\mathbf{x}_i$\nallows for a flexible parameterisation of the treatment beyond a\nsingle covariate, i.e. including a 1 for the intercept, continuous and\ncategorical variables as well as their interactions. We assume the\nresiduals to be independent and identically distributed (i.i.d)\naccording to a normal distribution with zero mean and constant\nvariance, i.e. $\\epsilon_{i} \\sim N(0,\\sigma_\\epsilon^2)$, that can\ndiffer from protein to protein.\n\nIn R, this model is encoded using the following simple formula^[We\ndon't need to specify the intercept as R automatically adds it during\nmodel estimation. you can explicitly add it using `~ 1 + ...`, you can\nalso suppress it using `~ 0 + `. When an intercept is included, one of\nthe groups is defined as the reference group and its corresponding\nmodel parameter is absorbed in the intercept. The residuals don't need\nto be specified as they are part of the model estimation process.]:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- ~ condition\n```\n:::\n\n\n### Model estimation{#sec-msqrob}\n\nWe estimate the model with `msqrob()`. The function takes the\n`QFeatures` object, extracts the quantitative values from the\n`\"proteins\"` set generated during summarisation, and fits a simple\nlinear model with `condition` as covariate, which are\nautomatically retrieved from `colData(spikein)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein <- msqrob(\n  spikein,  i = \"proteins\",\n  formula = model,\n  robust = TRUE\n)\n```\n:::\n\n\nWe enable M-estimation (`robust = TRUE`) for improved robustness\nagainst outliers. \nWe can also enable ridge regression (`ridge = TRUE`), which can stabilise \nthe parameter estimation of fixed effects. \nHowever, this is numerically more complex and is **only possible with msqrob2 \nif there are more than two slope terms** in the model, e.g. designs with more \nthan two groups or designs involving multiple covariates. The next chapter \nprovides more details on [robust regression](#sec-robust) and \n[ridge regression](#sec-ridge).\n\nThe fitting results are available in the `msqrobModels` column of the\n`rowData`. More specifically, the modelling output is stored in the\n`rowData` as a `statModel` object, one model per row (protein). We\nwill see in a later section how to perform statistical inference on\nthe estimated parameters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodels <- rowData(spikein[[\"proteins\"]])[[\"msqrobModels\"]]\nmodels[1:3]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$A0AVT1\nObject of class \"StatModel\"\nThe type is \"rlm\"\nThere number of elements is 5 \n\n$A0FGR8\nObject of class \"StatModel\"\nThe type is \"rlm\"\nThere number of elements is 5 \n\n$A0MZ66\nObject of class \"StatModel\"\nThe type is \"rlm\"\nThere number of elements is 5 \n```\n\n\n:::\n:::\n\n\n## Statistical inference{#sec-inference}\n\nWe can now convert the biological question \"does the spike-in\ncondition affect the protein intensities?\" into a statistical\nhypothesis. In other words, we must convert this question in a\ncombination of the model parameters, also referred to as a contrast.\nTo aid defining contrasts, we will visualise the experimental design\nusing the `ExploreModelMatrix` package. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"ExploreModelMatrix\")\nVisualizeDesign(\n  sampleData =  colData(spikein),\n  designFormula = model,\n  textSizeFitted = 4\n)$plotlist\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Visualisation of the experimental design using the `ExploreModelMatrix` package.](01-basics_files/figure-html/basics_VisualizeDesign-1.png){width=672}\n:::\n:::\n\n\nSpike-in condition `a` is the reference group. So the mean log2\nintensity for samples from condition a is `(Intercept)`. The mean\nlog2 expression for samples from condition b is '(Intercept) +\nconditionb'. Hence, the average log2 fold change between condition b\nand condition a is modelled using the parameter 'conditionb'. \n\nWith `getCoef()`, we can retrieve the estimated model parameters. \nWe start with extracting the model output, stored as `StatModel`\nobjects, from the `rowData`. Next, `getCoef()` retrieves the estimated\nmodel parameters:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodels <- rowData(spikein[[\"proteins\"]])$msqrobModels\nparams <- getCoef(models[[1]])\nhead(params)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n (Intercept)   conditionb   conditionc   conditiond   conditione \n23.506173482  0.104948589  0.027846447 -0.008119888 -0.071619774 \n```\n\n\n:::\n:::\n\n\nWe are interested, for this data set, in the\nparameters that model the effect of `condition`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparams[grep(\"condition\", names(params))]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  conditionb   conditionc   conditiond   conditione \n 0.104948589  0.027846447 -0.008119888 -0.071619774 \n```\n\n\n:::\n:::\n\n\nFor this protein we can see that the effects of condition are small, as\nexpected since the protein is part of the human constant background.\nWe now explore the parameters for one of the E. coli\nproteins.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparams <- getCoef(models[[\"P0AEE5\"]])\nparams[grep(\"condition\", names(params))]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nconditionb conditionc conditiond conditione \n 0.6625094  1.0662914  1.3155302  1.6919511 \n```\n\n\n:::\n:::\n\n\nSince this is a benchmark study and we know the concentration of A\n(0.25 fmol/µL) and B (0.74 fmol/µL), the obvious answer is\n$log_2(4.5) - log_2(3) = 0.585$. The average log2 difference in\nintensity between condition B and condition A that has been estimated\nby the model is 0.6625094, rather close. Now,\nthe question is if we can conclude that the fold change between\ncondition B and condition A is statistically significant for this protein based on the\nmodel output.\n\n### Hypothesis testing{#sec-hypothesis_testing}\n\n\nAs shown above, the average difference in log2 intensity between\ncondition b and a after correcting for the lab effect is\n`conditionb`. This combination of parameters is also called a\ncontrast. Thus, we assess the following null hypothesis for this\ncontrast: `conditionb = 0` with our statistical test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrast <- \"conditionb = 0\"\n```\n:::\n\n\n`makeContrast()` converts the hypothesis into a formal contrast matrix\nwith parameter names as rows and hypotheses in columns^[Note, that we only need to specify the names of the model parameters that are involved in the contrast when using the make contrast function. The hypothesisTest function below will then subset the relevant part from the model output. Also, note that the contrast matrix in this example is trivial. However, we will\n[later](#sec-multiple_contrasts) show how to asses multiple hypotheses\nat once and then the contrast matrix consists of multiple\ncolumns, with one column for each contrast].\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(L <- makeContrast(\n  \"conditionb = 0\",\n  \"conditionb\"\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           conditionb\nconditionb          1\n```\n\n\n:::\n:::\n\n\nWe can now test our null hypothesis using `hypothesisTest()` which\ntakes the `QFeatures` object with the fitted model and the contrast we\njust built. `msqrob2` automatically applies the hypothesis\ntesting to all proteins in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein <- hypothesisTest(spikein, i = \"proteins\", contrast = L)\n```\n:::\n\n\nThe results are stored in the set containing the model, here\n`proteins`. We retrieve the results from the `rowData`.\nNote, that for this spike-in study we know the ground truth, so we also add variable `isEcoli` to indicate if the protein is spiked \n(from E. coli).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#inference <- rowData(spikein[[\"proteins\"]])$ridgeconditionb\ninference <- rowData(spikein[[\"proteins\"]])$conditionb\ninference$Protein <- rownames(inference)\ninference$isEcoli <- inference$Protein %in% ecoli\nhead(inference)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             logFC         se        df          t      pval   adjPval Protein\nA0AVT1  0.10494859 0.07901174 15.963899  1.3282658 0.2027682 0.6845834  A0AVT1\nA0FGR8  0.06906717 0.04535794 16.141441  1.5227140 0.1471798 0.5908265  A0FGR8\nA0MZ66 -0.10892095 0.06295311 16.313394 -1.7301916 0.1024661 0.4872344  A0MZ66\nA1L0T0 -0.02486814 0.18978721 16.791528 -0.1310317 0.8973073 0.9858930  A1L0T0\nA1X283 -0.15880954 0.44509882  5.288059 -0.3567962 0.7350432 0.9680034  A1X283\nA2RRP1 -0.12957365 0.09296872 14.972800 -1.3937339 0.1837409 0.6617389  A2RRP1\n       isEcoli\nA0AVT1   FALSE\nA0FGR8   FALSE\nA0MZ66   FALSE\nA1L0T0   FALSE\nA1X283   FALSE\nA2RRP1   FALSE\n```\n\n\n:::\n:::\n\n\nNote, that missing values can occur because data modelling\nresulted in a `fitError` (the [advanced vignette](#sec-fiterror)\ndescribes how to deal with proteins that could not be fit).\n\nThe results also include an adjusted p-value for each protein $j$ to\ncorrect for multiple testing using the Benjamini-Hochberg False\nDiscovery Rate (FDR) method, which represents an estimate of the\nminimum FDR at which the test result for protein $j$ is considered\nsignificant, i.e. the expected fraction of false positives that are\nreported in the shortest top list of the most significant proteins\nthat include protein $j$.\n\n### Volcano plots\n\nA volcano plot is a common visualisation that provides an overview of\nthe hypothesis testing results, plotting the $-\\log_{10}$ p-value^[Note, that \nupon this transformation a value of 1 represents a p-value of 0.1, 2 a p-value \nof 0.01, 3 a p-value of 0.001, etc.] as a function of the estimated log fold \nchange. Volcano plots can be used to highlight the most interesting proteins \nthat have large fold changes and/or are highly significant. We can use the table \nabove directly to build a volcano plot using the `plotVolcano` function of \nmsqrob2. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ninference |> \n  plotVolcano() +\n  ggtitle(\"Statistical inference results\",\n          paste0(\"H0: \", colnames(L), \" = 0\"))\n```\n\n::: {.cell-output-display}\n![](01-basics_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n\nNote, that we also know the ground truth for this dataset because it is a \nspike-in study. So we will color the dots according to the ground truth in \n`isEcoli` and will use a different shape according to the significance (FDR \nabove or below $\\alpha = 0.05$).\nWe also add a vertical line according to the real logFC. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\ninference |> \n  plotVolcano() +\n  ggtitle(\"Statistical inference results\",\n          paste0(\"H0: \", colnames(L), \" = 0\")) + \n  aes(color = isEcoli, shape = adjPval < alpha) + \n    scale_color_manual(\n      values = c(\"grey20\", \"firebrick\"), \n      name = \"species\",\n      labels = c(\"human\", \"ecoli\")\n      ) +\n  labs(shape = paste0(\"FDR < \",alpha)) + \n  geom_vline(xintercept = log2(4.5) - log2(3), linetype = \"dashed\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](01-basics_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\nWe retrieve the proteins that are significantly differentially\nabundant based on the FDR-adjusted p-value (`adjPval`). Note that the\nmajority of the differentially abundant proteins are E. coli proteins.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(is_significant = inference$adjPval < alpha, \n      is_ecoli = inference$isEcoli)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              is_ecoli\nis_significant FALSE TRUE\n         FALSE  3716  199\n         TRUE     21  447\n```\n\n\n:::\n:::\n\n\nBecause we known the ground truth, we can also provide a list with\nfalse positives, true positives and the false discovery proprotion\n(FP/(FP+TP)) at a nominal 5% FDR level and observe that the FDP for this contrast is close to the 5% FDR, which is an estimate of the expected FDP if all assumptions made in the data analysis are valid.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninference |> \n  filter(adjPval < alpha) |>\n  summarise(\n    fp = sum(!isEcoli), \n    tp = sum(isEcoli), \n    fdp = round(mean(!isEcoli) * 100, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  fp  tp  fdp\n1 21 447 4.49\n```\n\n\n:::\n:::\n\n\n### Heatmaps{#sec-heatmaps}\n\nWe can explore the quantitative data of the significant proteins using\na heatmap. First, we select the names of the proteins that were \ndeclared significant between condition A and condition B and extract\ntheir quantitative data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigNames <- inference$Protein[!is.na(inference$adjPval) & inference$adjPval < alpha]\nse <- getWithColData(spikein, \"proteins\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n```{.r .cell-code}\nse <- se[sigNames, se$condition %in% c(\"a\", \"b\")]\n```\n:::\n\n\nNext, we extract the quantitative data and scale by rows^[The\n`scales()` function aligns the means and the centered standard\ndeviations by column. Since we want to scale by row, we need to\ntranspose (`t())`) before scaling and transpose back after scaling.\nScaling the data will remove changes in feature intensities that are\ncaused by uninteresting changes in ionisation efficiency.] with\n`assay()`. We will create a heatmap using the `ComplexHeatmap`\npackage, which enables heatmap annotations. We will annotate the\nheatmap using our model variables `condition` and `lab`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquants <- t(scale(t(assay(se))))\nlibrary(\"ComplexHeatmap\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: grid\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n========================================\nComplexHeatmap version 2.26.1\nBioconductor page: http://bioconductor.org/packages/ComplexHeatmap/\nGithub page: https://github.com/jokergoo/ComplexHeatmap\nDocumentation: http://jokergoo.github.io/ComplexHeatmap-reference\n\nIf you use it in published research, please cite either one:\n- Gu, Z. Complex Heatmap Visualization. iMeta 2022.\n- Gu, Z. Complex heatmaps reveal patterns and correlations in multidimensional \n    genomic data. Bioinformatics 2016.\n\n\nThe new InteractiveComplexHeatmap package can directly export static \ncomplex heatmaps into an interactive Shiny app with zero effort. Have a try!\n\nThis message can be suppressed by:\n  suppressPackageStartupMessages(library(ComplexHeatmap))\n========================================\n```\n\n\n:::\n\n```{.r .cell-code}\nannotations <- columnAnnotation(\n  condition = se$condition\n)\n```\n:::\n\n\nWe now make the heatmap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234) ## annotation colours are randomly generated by default\nHeatmap(\n quants, name = \"log2 intensity\",\n cluster_rows = FALSE,\n top_annotation = annotations\n)\n```\n\n::: {.cell-output-display}\n![Heatmap of the proteins that are significantly differentially abundant between condition b and condition a.](01-basics_files/figure-html/basics_heatmap-1.png){width=480}\n:::\n:::\n\n\nWe observe that the majority of the returned proteins are indeed upregulated in the higher spike-in condition b. \n\n### Fold change distributions\n\nAs this is a spike-in study with known ground truth, we can also plot\nthe log2 fold change distributions against its true values, in\nthis case 0 for the human proteins and 0.585 for the\nE. coli proteins.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(inference) +\n  aes(y = logFC,\n      x = isEcoli,\n      colour = isEcoli) +\n  geom_boxplot() +\n  geom_hline(yintercept = c(0, log2(4.5) - log2(3)), \n             colour = c(\"grey20\", \"firebrick\")) +\n  scale_color_manual(\n    values = c(\"grey20\", \"firebrick\"), name = \"\",\n    labels = c(\"Human proteins\", \"E. coli proteins\")\n  ) +\n  ggtitle(paste0(\"Hypothesis test: \", colnames(L), \" = 0\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 209 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Distribution of the log2 fold changes between condition b and condition a. The red line is the expected value for spike-in proteins while the black line is the expected value for constant proteins.](01-basics_files/figure-html/basics_boxplots-1.png){width=672}\n:::\n:::\n\n\nEstimated log2 fold change for human proteins are closely distributed\naround 0, as expected. log2 fold changes for E. coli proteins are\ndistributed around the fold changes induced by the experimental\ndesign, indicating that msqrob2 is providing unbiased fold change estimates. \n\n### Detail plots{#sec-detail_plot}\n\nWe can explore the data for a protein to validate the statistical\ninference results. For example, let's explore the peptide and the\nsummarised protein intensities for the protein with the most\nsignificant difference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(targetProtein <- rownames(inference)[which.min(inference$adjPval)])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"P0A799\"\n```\n\n\n:::\n:::\n\n\nTo obtain the required data, we perform a little data manipulation\npipeline:\n\nWe use the `QFeatures` subsetting functionality to retrieve all data\nrelated to  and focusing on the `peptides_log` and\n`proteins` sets that contains the peptide ion data used for model\nfitting. We then convert the data with `longForm()` for plotting.\nFinally, we plot the log2 normalised intensities for each sample at\nthe protein and at the peptide level. Since multiple peptides are\nrecorded for the protein, we link peptides across samples using a grey\nline. Samples are colored according to E. coli spike-in condition.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein[targetProtein, , c(\"peptides_log\", \"proteins\")] |> #1\n  longForm(colvars = colnames(colData(spikein)), #2\n           rowvars = \"Proteins\") |>\n  data.frame() |> \n  ggplot() +\n  aes(x = colname,\n      y = value) +\n  geom_line(aes(group = rowname), linewidth = 0.1) +\n  geom_point(aes(colour = condition)) +\n  facet_wrap(~ assay, scales = \"free\") +\n  ggtitle(targetProtein) +\n  theme_minimal() +\n  theme(axis.text.x = element_blank())\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 40 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 12 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 34 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Detail plot showing the peptide log intensities (left) and log-transformed normalised and summarised protein intensities (right). Every point is a sample, coloured by spike-in condition, and points belonging to the same feature (peptide or protein) are linked with a grey line.](01-basics_files/figure-html/detail_plot-1.png){width=768}\n:::\n:::\n\n\n## Going further\n\n### Testing muliple contrasts at once{#sec-multiple_contrasts}\n\nWe showed how to perform a hypothesis test to answer the question \n\"which proteins change in abundance between condition b and condition \na?\". However, since we have 5 conditions, we can do further \ncomparisons.  `msqrob2` can assess multiple hypothesis at once. Like\nabove we must provide which hypotheses we want to compare. \n`createPairwiseContrasts()` will generate all possible comparisons\nbetween `condition` level. The function requires the model\nspecification that has been estimated and the sample annotation from\nthe data. We also specify that we estimated the model using ridge\nregression, which influences parameter names.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(allHypotheses <- createPairwiseContrasts(\n  model, \n  colData(spikein), \n  \"condition\"\n))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: the 'nobars' function has moved to the reformulas package. Please update your imports, or ask an upstream package maintainter to do so.\nThis warning is displayed once per session.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"conditionb = 0\"              \"conditionc = 0\"             \n [3] \"conditiond = 0\"              \"conditione = 0\"             \n [5] \"conditionc - conditionb = 0\" \"conditiond - conditionb = 0\"\n [7] \"conditione - conditionb = 0\" \"conditiond - conditionc = 0\"\n [9] \"conditione - conditionc = 0\" \"conditione - conditiond = 0\"\n```\n\n\n:::\n:::\n\n\nWe now run the same workflow as above for a single hypothesis, except \nthat here `allHypotheses` is a vector of contrasts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(L <- makeContrast(\n  allHypotheses,\n  parameterNames = paste0(\"condition\", c(\"b\", \"c\", \"d\", \"e\"))\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           conditionb conditionc conditiond conditione conditionc - conditionb\nconditionb          1          0          0          0                      -1\nconditionc          0          1          0          0                       1\nconditiond          0          0          1          0                       0\nconditione          0          0          0          1                       0\n           conditiond - conditionb conditione - conditionb\nconditionb                      -1                      -1\nconditionc                       0                       0\nconditiond                       1                       0\nconditione                       0                       1\n           conditiond - conditionc conditione - conditionc\nconditionb                       0                       0\nconditionc                      -1                      -1\nconditiond                       1                       0\nconditione                       0                       1\n           conditione - conditiond\nconditionb                       0\nconditionc                       0\nconditiond                      -1\nconditione                       1\n```\n\n\n:::\n:::\n\n\nThe contrast contains multiple hypotheses (multiple column) that \ninvolve multiple parameters (multiple rows). \n\nWe use again `hypothesisTest()` for performing the hypothesis test. We\nalready generated results for the contrast `ridgeconditionb = 0` and\nthe function will throw an error by default, but we can overwrite the\nresults with the argument `overwrite = TRUE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein <- hypothesisTest(spikein, i = \"proteins\", L, overwrite = TRUE)\n```\n:::\n\n\nThe results tables for the contrast are stored in the row data of the \n`proteins` assay in `spikein` under the colomnames of the contrast matrix `L`.\n\nUsers can directly access the results tables via de colData. However, `msqrob2` \nalso provides the `msqrobCollect` function. This function will automatically \nretrieve the results tables for all contrasts in contrast matrix `L` and combine \nthem by default in one  table. This table contains two additional columns: \n`contrast` with the name of the contrast and `feature` with the name of the \nmodelled `feature`, here protein. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ninferences <- \n  msqrobCollect(spikein[[\"proteins\"]], L) \nhead(inferences)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        logFC         se        df          t      pval\nconditionb.A0AVT1  0.10494859 0.07901174 15.963899  1.3282658 0.2027682\nconditionb.A0FGR8  0.06906717 0.04535794 16.141441  1.5227140 0.1471798\nconditionb.A0MZ66 -0.10892095 0.06295311 16.313394 -1.7301916 0.1024661\nconditionb.A1L0T0 -0.02486814 0.18978721 16.791528 -0.1310317 0.8973073\nconditionb.A1X283 -0.15880954 0.44509882  5.288059 -0.3567962 0.7350432\nconditionb.A2RRP1 -0.12957365 0.09296872 14.972800 -1.3937339 0.1837409\n                    adjPval   contrast feature\nconditionb.A0AVT1 0.6845834 conditionb  A0AVT1\nconditionb.A0FGR8 0.5908265 conditionb  A0FGR8\nconditionb.A0MZ66 0.4872344 conditionb  A0MZ66\nconditionb.A1L0T0 0.9858930 conditionb  A1L0T0\nconditionb.A1X283 0.9680034 conditionb  A1X283\nconditionb.A2RRP1 0.6617389 conditionb  A2RRP1\n```\n\n\n:::\n:::\n\n\nWe rename the contrasts by removing the string 'ridgecondition'.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ninferences$contrast <- gsub(\"condition\",\"\", inferences$contrast)\n```\n:::\n\n\nWe add the ground truth as we know that E. coli is spiked in: \n\n\n::: {.cell}\n\n```{.r .cell-code}\ninferences$isEcoli <- inferences$feature %in% ecoli\n```\n:::\n\n\nWe plot the volcano plots with each comparison in a separate facet and again\ncolor the dots according to the ground truth. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ninferences |> \n  plotVolcano() +\n    aes(color = isEcoli, shape = adjPval < alpha) + \n    scale_color_manual(\n      values = c(\"grey20\", \"firebrick\"), \n      name = \"species\",\n      labels = c(\"human\", \"ecoli\")\n      ) +\n  labs(shape = paste0(\"FDR < \",alpha)) + \n  facet_wrap(~ contrast) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Volcano plot of the statistical inference results for all pairwise comparisons.](01-basics_files/figure-html/basics_volcano_multiple-1.png){width=864}\n:::\n:::\n\n\nSince we know the ground truth we can again evaluate the number of\ntrue positives, false positives and false discovery proportion.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninferences |> \n  filter(adjPval < 0.05) |> \n  group_by(contrast) |> \n  summarise(\n    fp = sum(!isEcoli), \n    tp = sum(isEcoli), \n    fdp = round(mean(!isEcoli)*100,2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   contrast    fp    tp   fdp\n   <chr>    <int> <int> <dbl>\n 1 b           21   447  4.49\n 2 c           42   543  7.18\n 3 c - b       27   320  7.78\n 4 d           57   587  8.85\n 5 d - b       46   514  8.21\n 6 d - c        8   234  3.31\n 7 e           97   611 13.7 \n 8 e - b       82   581 12.4 \n 9 e - c       40   506  7.33\n10 e - d        7   265  2.57\n```\n\n\n:::\n:::\n\n\nIf the FDR is well controlled, we expect the FDPs to fluctuate around the \nnominal FDR level of 5%. \nWe observe, however,that the FDPs for the contrasts envolving larger fold \nchanges e.g e (e vs a) and (e vs b) are much larger than 5%, indicating that \nthe results might be too liberal for these comparisons. \nNote, that this is often seen in spike-in studies where all proteins that are \nspiked in are regulated in the same direction, which can lead to ion suppression\nfor the non-DA proteins in high spike-in samples and puts a burden on the \nnormalisation assumptions. \nWe will illustrate in later chapters [Benchmarking workflows](#sec-benchmarking) \nand [Optimisation of a data analysis workflow](#sec-workflow-optimisation) that \nmore robust inference for this dataset can be provided with ridge regression. \nHowever, this comes at a considerable computational cost.  \n\nWe can also assess the fold changes, but we first create a small table\nwith the real values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrealLogFC <- data.frame(\n  logFC = t(L) %*% lm(log2(concentration) ~ condition, colData(spikein))$coef[-1]\n)\nrealLogFC$contrast <- gsub(\"condition\",\"\",colnames(L))\n```\n:::\n\n\nWe can now create the boxplots with the estimated log2-fold changes,\nadding horizontal lines with the corresponding target values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninferences |>\n  na.exclude() |> \n  ggplot(\n    aes(y = logFC,\n        x = isEcoli,\n        colour = isEcoli)) +\n  geom_boxplot()  +\n  scale_color_manual(\n    values = c(\"grey20\", \"firebrick\"), name = \"\",\n    labels = c(\"Human proteins\", \"E. coli proteins\")\n  ) +\n  facet_wrap(~contrast) +\n  geom_hline(data = realLogFC, aes(yintercept = logFC), \n             colour = \"firebrick\") +\n  geom_hline(yintercept = 0)\n```\n\n::: {.cell-output-display}\n![Distribution of the log2 fold changes for all pairwise comparisons. The red line is the expected value for spike-in proteins while the black line is the expected value for constant proteins.](01-basics_files/figure-html/basics_boxplots_multiple-1.png){width=672}\n:::\n:::\n\nWe again observe that the log2 fold change estimates are close to the \nreal spike-in fold changes induced by the experimental design.\n\n### Model the spike-in concentration as a numeric\n\nSince the relative concentration of the E. coli spike-in lysate is\nknown, we can also model the effect of the treatment using the\nlog2-transformed spike-in concentration as a continuous covariate. We\nthen expect the slope to be close to 1 for E. coli proteins.\n\n1. We first create a variable with log2 transformed concentration in\n   the `colData`.\n2. We fit an msqrob model using the log2 transformed concentration as\n   a fixed effect. Note, that we set `ridge = FALSE` because we only \n   have one slope parameter in the model. We store the models in a new\n   column with name `\"concentration_model\"`.\n3. We setup a contrast for the slope term.\n4. We conduct the hypothesis test for all proteins.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein$concentration_log2 <- log2(spikein$concentration) #1.\nspikein <- msqrob( #2.\n  spikein, i = \"proteins\",\n  formula = ~ concentration_log2,\n  ridge = FALSE,\n  robust = TRUE, \n  modelColumnName = \"concentration_model\"\n)\nL <- makeContrast( #3.\n  \"concentration_log2 = 0\", parameterNames = \"concentration_log2\"\n)\nspikein <- hypothesisTest( #4.\n  spikein, i = \"proteins\", L, modelColumn = \"concentration_model\",\n  overwrite = TRUE\n)\n```\n:::\n\n\nWe plot the results using the volcano plot as in the previous section.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninferenceLin <- msqrobCollect(spikein[[\"proteins\"]], L)\ninferenceLin$isEcoli <- inferenceLin$feature %in% ecoli\nplotVolcano(inferenceLin) + \n  aes(color = isEcoli, shape = adjPval < alpha) + \n  scale_color_manual(\n    values = c(\"grey20\", \"firebrick\"), \n    name = \"species\",\n    labels = c(\"human\", \"ecoli\")\n    ) + \n  geom_vline(xintercept = 1, linetype = \"dashed\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Volcano plot of the statistical inference results when modelling the spike-in concentration as a continuous variable. `logFC` actually stands for the slope parameter.](01-basics_files/figure-html/basics_volcano_continuous-1.png){width=864}\n:::\n:::\n\n\nSimilarly, we plot the estimated log2 concentration slope against the \nexpected value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninferenceLin |>\n  na.exclude() |>\n  ggplot(\n    aes(y = logFC,\n        x = isEcoli,\n        colour = isEcoli)) +\n  geom_boxplot()  +\n  scale_color_manual(\n    values = c(\"grey20\", \"firebrick\"), name = \"\",\n    labels = c(\"Human proteins\", \"E. coli proteins\")\n  ) + \n  geom_hline(yintercept = 0) + \n  geom_hline(yintercept = 1, color = \"firebrick\")\n```\n\n::: {.cell-output-display}\n![Distribution of the log2 fold changes for the slope parameter. The red line is the expected value for spike-in proteins while the black line is the expected value for constant proteins.](01-basics_files/figure-html/basics_boxplots_continuous-1.png){width=672}\n:::\n:::\n\n\nNote, that the slopes for the human and E. coli proteins are centered\naround 0 and 1, respectively. \n\n## Conclusion\n\nIn this vignette, we have demonstrated a typical data analysis\nworkflow for label free data using `msqrob2`. Because the packages\nrelies on the `QFeatures` data class, we could demonstrate the\nimplementation of a complete pre-processing workflow starting from\nMaxQuant's peptide table: log2-transformation, PSM filtering, missing\nvalue management, normalisation, and summarisation. The data\nexploration revealed expected patterns of variation among samples, as\nthis is a ground truth data set.\n\nOnce pre-processed, we use the `msqrob2` package to model the (known)\neffect of spike-in condition. We showed how to run statistical\ninference on the modelling results to retrieve the significance of\ndifferentially abundant proteins. We explored statistical results\nthrough volcano plots and boxplots of the log2 fold changes and\nvisually validated the results for one protein by plotting the input\ndata. We have shown the inference pipeline can be streamlined when\nassessing multiple hypotheses. In this example, the spike-in\ncondition can be encoded as a categorical variable or a numeric\nvariable, and we showed how to model and interpret the results for \nboth cases. \n\nThis chapter thus provides a general framework for analysing simple\nexperimental designs for label-free proteomics experiments. Remember,\nthis book provides [an overview](#sec-overview_use_cases) of different\nuse-cases with more complex designs. In the next chapter, we will\nillustrate advanced concepts of proteomics data analysis, illustrated\nby the analysis of a TMT-labelled spike-in experiment.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}