<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="Chapter 3 Advanced statistical analysis with msqrob2 | Statistical analysis of mass spectrometry-based proteomics data" />
<meta property="og:type" content="book" />




<meta name="author" content="Christophe Vanderaa, Stijn Vandenbulcke, Lieven Clement" />

<meta name="date" content="2025-11-04" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="description" content="Chapter 3 Advanced statistical analysis with msqrob2 | Statistical analysis of mass spectrometry-based proteomics data">

<title>Chapter 3 Advanced statistical analysis with msqrob2 | Statistical analysis of mass spectrometry-based proteomics data</title>

<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/envisioned.css" rel="stylesheet" />
<link href="libs/msmb-css-0/msmb.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}

}
</script>
<script>
function copy_link(id) {
  var dummy = document.createElement('input'),
  text = window.location.href.split(/[?#]/)[0] + '#' + id;
  document.body.appendChild(dummy);
  dummy.value = text;
  dummy.select();
  document.execCommand('copy');
  document.body.removeChild(dummy);
  
  var tooltip = document.getElementById(id + '-tooltip');
  tooltip.innerHTML = 'Copied!';
}

function reset_tooltip(id) {
  var tooltip = document.getElementById(id);
  tooltip.innerHTML = 'Copy link';
}
</script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }

code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>


<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul class="navbar">
<li class="msmb"><p class="title">Statistical analysis of mass spectrometry-based proteomics data<p><p class="author">Christophe Vanderaa, Stijn Vandenbulcke, Lieven Clement</p>
<li class="dropdown" style="float:right">
<a href="javascript:void(0)" class="dropbtn">&#x25BE; Chapters</a>
<div class="dropdown-content">
<a href="index.html" id="toc-preamble"><span class="toc-section-number">1</span> Preamble</a>
<a href="sec-basics.html" id="toc-sec-basics"><span class="toc-section-number">2</span> Statistical analysis with msqrob2</a>
<a id="active-page" href="sec-advanced.html" id="toc-sec-advanced"><span class="toc-section-number">3</span> Advanced statistical analysis with msqrob2</a><ul class="toc-sections">
<li class="toc"><a href="#background-1"> Background</a></li>
<li class="toc"><a href="#load-packages-1"> Load packages</a></li>
<li class="toc"><a href="#data"> Data</a></li>
<li class="toc"><a href="#data-preprocessing"> Data preprocessing</a></li>
<li class="toc"><a href="#data-exploration"> Data exploration</a></li>
<li class="toc"><a href="#NA"> Data modelling</a></li>
<li class="toc"><a href="#statistical-inference"> Statistical inference</a></li>
<li class="toc"><a href="#protein-level-inference"> Protein-level inference</a></li>
<li class="toc"><a href="#dealing-with-fiterrors"> Dealing with <code id="sec-fiterror">fitErrors</code></a></li>
<li class="toc"><a href="#conclusion-1"> Conclusion</a></li>
</ul>
<a href="sec-benchmarking.html" id="toc-sec-benchmarking"><span class="toc-section-number">4</span> Benchmarking workflows</a>
<a href="sec-francisella.html" id="toc-sec-francisella"><span class="toc-section-number">5</span> The francisella use case: a MaxQuant LFQ DDA dataset with technical replication</a>
<a href="sec-heart_chapter.html#sec-heart_chapter" id="toc-sec-heart_chapter"><span class="toc-section-number">6</span> Heart use case: a MaxQuant LFQ DDA dataset with a more complex design</a>
<a href="sec-mouse_diet.html#sec-mouse_diet" id="toc-sec-mouse_diet"><span class="toc-section-number">7</span> The mouse diet use case: a Skyline TMT DDA dataset</a>
<a href="sec-end.html" id="toc-sec-end"><span class="toc-section-number">8</span> Usefull links and session information</a>
</div>
</li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="sec-advanced" class="section level1" number="3">
<h1>
<span class="header-section-number">Chapter 3</span> Advanced statistical analysis with msqrob2</h1>
<p>This chapter builds upon the <a href="sec-basics.html#sec-basics">basics</a> of proteomics data
analysis and provides more advanced concepts using <code>msqrob2</code>. To
illustrate these advanced concepts, we will use the spike-in study
published by <span class="citation">Huang et al. (<label for="tufte-mn-8" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-8" class="margin-toggle">2020<span class="marginnote">Huang, Ting, Meena Choi, Manuel Tzouros, Sabrina Golling, Nikhil Janak Pandya, Balazs Banfai, Tom Dunkley, and Olga Vitek. 2020. <span>“<span>MSstatsTMT</span>: Statistical Detection of Differentially Abundant Proteins in Experiments with Isobaric Labeling and Multiple Mixtures.”</span> <em>Mol. Cell. Proteomics</em> 19 (10): 1706–23.</span>)</span>. We chose this data set because:</p>
<ol style="list-style-type: decimal">
<li>Spike-in data contain ground truth information about which proteins
are differentially abundant, enabling us to show the impact of
different analysis strategies.</li>
<li>It has been acquired with a TMT-labelling strategy that require a
complex experimental design. This provides an excellent example
to explain the different sources of variability in an MS experiment
and demonstrate the flexibility of <code>msqrob2</code> to model this
variability.</li>
</ol>
<div id="background-1" class="section level2" number="3.1">
<h2>
<span class="header-section-number">3.1</span> Background<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('background-1')" onmouseout="reset_tooltip('background-1-tooltip')"><span class="tooltiptext" id="background-1-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>Labelling strategies in mass spectrometry (MS)-based proteomics
enhance sample throughput by enabling the acquisition of multiple
samples within a single run. The labelling strategy that allows the
highest multiplexing is the tandem mass tag (TMT) labelling and will
be the focus of the current tutorial.</p>
<div id="sec-tmt_workflow" class="section level3" number="3.1.1">
<h3>
<span class="header-section-number">3.1.1</span> TMT workflow<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sec-tmt_workflow')" onmouseout="reset_tooltip('sec-tmt_workflow-tooltip')"><span class="tooltiptext" id="sec-tmt_workflow-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>TMT-based workflow highly overlap with <a href="%7B#sec-lfq_workflow%7D">label-free
workflows</a>. However, TMT-based workflows have an
additional sample preparation step, where the digested peptides from
each sample are labelled with a TMT reagent and samples with different
TMT reagents are pooled in a single TMT mixture<label for="tufte-sn-18" class="margin-toggle sidenote-number">18</label><input type="checkbox" id="tufte-sn-18" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">18</span> Depending on the
reagents used, 6, 10, 11 up to 18 samples can be pooled in one
mixture</span>. The signal processing is also slightly affected since the
quantification no longer occurs in the MS1 space but at the MS2 level.
It is important to understand that TMT reagent are isobaric, meaning
that the same peptide with different TMT labels will have the same
mass for the intact ion, as recorded during MS1. However, the TMT
fragments that are released upon fragmentation during MS2, also called
TMT reporter ions, have label-specific masses. The TMT fragments have
an expected mass and are distributed in a low-mass range of the MS2
space. The intensity of each TMT fragment is directly proportional to
the peptide quantity in the original sample before pooling. The TMT
fragment intensities measured during MS2 are used as quantitative
data. The higher mass range contains the peptide fragments that
compose the peptide fingerprint, similarly to LFQ. This data range is
therefore used for peptide identification. Interestingly, the peptide
fingerprint originates from the same peptide across multiple samples.
This leads to a signal boost for low abundant peptides and hence
should improve data sensitivity and consistency.</p>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-180"></span>
<p class="caption marginnote shownote">
Figure 3.1: Overview of an TMT-based proteomics workflow.
</p>
<img src="figs/tmt_workflow.png" alt="Overview of an TMT-based proteomics workflow." width="40%">
</div>
</div>
<div id="challenges" class="section level3" number="3.1.2">
<h3>
<span class="header-section-number">3.1.2</span> Challenges<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('challenges')" onmouseout="reset_tooltip('challenges-tooltip')"><span class="tooltiptext" id="challenges-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>The analysis of TMT-based proteomics data shares the same challenges
as the <a href="sec-basics.html#sec-lfq_challenges">data analysis challenges for LFQ</a>.
However, TMT workflows impose additional challenges:</p>
<ul>
<li>Contemporary experiments often involve increasingly complex designs,
where the number of samples exceeds the capacity of a single TMT
mixture, resulting in a complex correlation structure that must be
addressed for accurate statistical inference. We will describe in
the modelling section the different sources of variation.</li>
<li>We also recommend modelling TMT data at the lowest level, that is at
the peptide ion level, for optimal performance
<span class="citation">(<label for="tufte-mn-9" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-9" class="margin-toggle">Vandenbulcke et al. 2025<span class="marginnote">Vandenbulcke, Stijn, Christophe Vanderaa, Oliver Crook, Lennart Martens, and Lieven Clement. 2025. <span>“<span>Msqrob2TMT</span>: Robust Linear Mixed Models for Inferring Differential Abundant Proteins in Labeled Experiments with Arbitrarily Complex Design.”</span> <em>Mol. Cell. Proteomics</em> 24 (7): 101002.</span>)</span>. These ion-level models are more complex and
include additional sources of variation instead of relying on the
summarised protein values. We have shown for LFQ data that a
two-step approach where data are first summarised (using a
<a href="sec-basics.html#sec-summarisation">model-based method</a>) and then modelled with
<code>msqrob2</code> leads to similar results, and hence provides more accessible models
for non-specialised data analysts <span class="citation">(<label for="tufte-mn-10" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-10" class="margin-toggle">Sticker et al. 2020<span class="marginnote">Sticker, Adriaan, Ludger Goeminne, Lennart Martens, and Lieven Clement. 2020. <span>“Robust Summarization and Inference in Proteome-Wide Label-Free Quantification.”</span> <em>Mol. Cell. Proteomics</em> 19 (7): 1209–19.</span>)</span>.</li>
</ul>
</div>
<div id="experimental-context" class="section level3" number="3.1.3">
<h3>
<span class="header-section-number">3.1.3</span> Experimental context<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('experimental-context')" onmouseout="reset_tooltip('experimental-context-tooltip')"><span class="tooltiptext" id="experimental-context-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>The data set used in this chapter is a spike-in experiment
(PXD0015258) published by <span class="citation">Huang et al. (<label for="tufte-mn-11" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-11" class="margin-toggle">2020<span class="marginnote">Huang, Ting, Meena Choi, Manuel Tzouros, Sabrina Golling, Nikhil Janak Pandya, Balazs Banfai, Tom Dunkley, and Olga Vitek. 2020. <span>“<span>MSstatsTMT</span>: Statistical Detection of Differentially Abundant Proteins in Experiments with Isobaric Labeling and Multiple Mixtures.”</span> <em>Mol. Cell. Proteomics</em> 19 (10): 1706–23.</span>)</span>. It consists of controlled
mixtures with known ground truth. UPS1 peptides at concentrations of
500, 333, 250, and 62.5 fmol were spiked into 50 g of SILAC HeLa
peptides, each in duplicate. These concentrations form a dilution
series of 1, 0.667, 0.5, and 0.125 relative to the highest UPS1
peptide amount (500 fmol). A reference sample was created by combining
the diluted UPS1 peptide samples with 50g of SILAC HeLa peptides. All
dilutions and the reference sample were prepared in duplicate,
resulting in a total of ten samples. These samples were then treated
with TMT10-plex reagents and combined before LC-MS/MS analysis. This
protocol was repeated five times, each with three technical
replicates, totaling 15 MS runs.</p>
<p>We will start from the PSM data generated by Skyline and infer
protein-level differences between samples. To achieve this goal, we
will apply an msqrob2TMT workflow, a data processing and modelling
workflow dedicated to the analysis of TMT-based proteomics datasets.
We will demonstrate how the workflow can highlight the spiked-in
proteins. Before delving into the analysis, let us prepare our
computational environment.</p>
</div>
</div>
<div id="load-packages-1" class="section level2" number="3.2">
<h2>
<span class="header-section-number">3.2</span> Load packages<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('load-packages-1')" onmouseout="reset_tooltip('load-packages-1-tooltip')"><span class="tooltiptext" id="load-packages-1-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>We load the <code>msqrob2</code> package, along with additional packages for
data manipulation and visualisation.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="sec-advanced.html#cb94-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"msqrob2"</span>)</span>
<span id="cb94-2"><a href="sec-advanced.html#cb94-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb94-3"><a href="sec-advanced.html#cb94-3" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb94-4"><a href="sec-advanced.html#cb94-4" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"patchwork"</span>)</span></code></pre></div>
<p>We also configure the <a href="sec-basics.html#sec-parallel">parallelisation</a> framework.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="sec-advanced.html#cb95-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"BiocParallel"</span>)</span>
<span id="cb95-2"><a href="sec-advanced.html#cb95-2" tabindex="-1"></a><span class="fu">register</span>(<span class="fu">SerialParam</span>())</span></code></pre></div>
</div>
<div id="data" class="section level2" number="3.3">
<h2>
<span class="header-section-number">3.3</span> Data<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('data')" onmouseout="reset_tooltip('data-tooltip')"><span class="tooltiptext" id="data-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<div id="sec-caching" class="section level3" number="3.3.1">
<h3>
<span class="header-section-number">3.3.1</span> File caching<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sec-caching')" onmouseout="reset_tooltip('sec-caching-tooltip')"><span class="tooltiptext" id="sec-caching-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>The data have been deposited by the authors in the <code>MSV000084264</code>
MASSiVE repository, but we will retrieve the time stamped data from
our <a href="https://zenodo.org/records/14767905">Zenodo repository</a>. We need
2 files: the Skyline identification and quantification table generated
by the authors and the sample annotation files.</p>
<p>To facilitate management of the files, we download the required files
using the <code>BiocFileCache</code> package. The package will set up a local
database in a cache directory<label for="tufte-sn-19" class="margin-toggle sidenote-number">19</label><input type="checkbox" id="tufte-sn-19" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">19</span> You will be prompted to create a new
folder the first time you use the package.</span>. <code>BiocFileCache()</code> creates
a connection to that database and <code>bfcrpath()</code> will query the database
for the required URL. If that URL is not present in the database, the
function will automatically download the URL target file and store it
in the cache directory. If the URL is already present in the database,
the function will retrieve the associated file from the local cache
directory. This procedure ensures that the files are downloaded only
once while providing a direct link to its source link. When these
links point to permanent archives (like Zenodo) or large public
databases (like PRIDE or MASSiVE), this approach promotes reproducible
analyses.</p>
<p>The chunk below will take some time to complete the first time you run
it as it needs to download the (large) file locally, but will fetch
the local copy the following times.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="sec-advanced.html#cb96-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"BiocFileCache"</span>)</span>
<span id="cb96-2"><a href="sec-advanced.html#cb96-2" tabindex="-1"></a>bfc <span class="ot">&lt;-</span> <span class="fu">BiocFileCache</span>()</span>
<span id="cb96-3"><a href="sec-advanced.html#cb96-3" tabindex="-1"></a>psmFile <span class="ot">&lt;-</span> <span class="fu">bfcrpath</span>(bfc, <span class="st">"https://zenodo.org/records/14767905/files/spikein1_psms.txt?download=1"</span>)</span>
<span id="cb96-4"><a href="sec-advanced.html#cb96-4" tabindex="-1"></a>annotFile <span class="ot">&lt;-</span> <span class="fu">bfcrpath</span>(bfc, <span class="st">"https://zenodo.org/records/14767905/files/spikein1_annotations.csv?download=1"</span>)</span></code></pre></div>
<p>Now the files are downloaded, we can load the two tables.</p>
</div>
<div id="sec-psm_table" class="section level3" number="3.3.2">
<h3>
<span class="header-section-number">3.3.2</span> PSM table<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sec-psm_table')" onmouseout="reset_tooltip('sec-psm_table-tooltip')"><span class="tooltiptext" id="sec-psm_table-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>An MS experiment generates spectra. Each MS2 spectrum is used to infer
the peptide identity using a search engine. When
an observed spectrum is matched to a theoretical peptide spectrum, we
have a peptide-to-spectrum match (PSM). The identification software
compiles all the PSMs inside a table. Hence, the PSM data is the
lowest possible level to perform data modelling.</p>
<p>Each row in the PSM data table contains information for one PSM (the
table below shows the first 6 rows). The columns contains various
information about the PSM, such as the peptide sequence and charge,
the quantified value, the inferred protein group, the measured and
predicted retention time and precursor mass, the score of the match,
… In the case of Skyline TMT data, the quantification values are provides in
multiple columns (start with <code>"Abundance."</code>), one for each TMT label.
Regardless of TMT or LFQ experiments, the PSM table stacks the
quantitative values from samples in different runs below each other.
We must therefore split the table by run to ensure that every
quantitative column contains data from a single sample. This is
performed during the conversion to a <code>QFeatures</code> object.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="sec-advanced.html#cb97-1" tabindex="-1"></a>psms <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(psmFile)</span>
<span id="cb97-2"><a href="sec-advanced.html#cb97-2" tabindex="-1"></a>qcols <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">"Abundance"</span>, <span class="fu">colnames</span>(psms), <span class="at">value =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<table style="width:100%;">
<colgroup>
<col width="0%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="4%">
<col width="6%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="2%">
<col width="8%">
<col width="1%">
<col width="8%">
<col width="2%">
<col width="0%">
<col width="1%">
<col width="0%">
<col width="0%">
<col width="1%">
<col width="1%">
<col width="0%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="0%">
<col width="2%">
<col width="2%">
<col width="2%">
<col width="0%">
<col width="1%">
<col width="4%">
<col width="0%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
</colgroup>
<thead><tr class="header">
<th align="left">Checked</th>
<th align="left">Confidence</th>
<th align="left">Identifying.Node</th>
<th align="left">PSM.Ambiguity</th>
<th align="left">Annotated.Sequence</th>
<th align="left">Modifications</th>
<th align="left">Marked.as</th>
<th align="right">X..Protein.Groups</th>
<th align="right">X..Proteins</th>
<th align="left">Master.Protein.Accessions</th>
<th align="left">Master.Protein.Descriptions</th>
<th align="left">Protein.Accessions</th>
<th align="left">Protein.Descriptions</th>
<th align="right">X..Missed.Cleavages</th>
<th align="right">Charge</th>
<th align="right">DeltaScore</th>
<th align="right">DeltaCn</th>
<th align="right">Rank</th>
<th align="right">Search.Engine.Rank</th>
<th align="right">m.z..Da.</th>
<th align="right">MH…Da.</th>
<th align="right">Theo..MH…Da.</th>
<th align="right">DeltaM..ppm.</th>
<th align="right">Deltam.z..Da.</th>
<th align="left">Activation.Type</th>
<th align="left">MS.Order</th>
<th align="right">Isolation.Interference….</th>
<th align="right">Average.Reporter.S.N</th>
<th align="right">Ion.Inject.Time..ms.</th>
<th align="right">RT..min.</th>
<th align="right">First.Scan</th>
<th align="left">Spectrum.File</th>
<th align="left">File.ID</th>
<th align="right">Abundance..126</th>
<th align="right">Abundance..127N</th>
<th align="right">Abundance..127C</th>
<th align="right">Abundance..128N</th>
<th align="right">Abundance..128C</th>
<th align="right">Abundance..129N</th>
<th align="right">Abundance..129C</th>
<th align="right">Abundance..130N</th>
<th align="right">Abundance..130C</th>
<th align="right">Abundance..131</th>
<th align="left">Quan.Info</th>
<th align="right">Ions.Score</th>
<th align="right">Identity.Strict</th>
<th align="right">Identity.Relaxed</th>
<th align="right">Expectation.Value</th>
<th align="right">Percolator.q.Value</th>
<th align="right">Percolator.PEP</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">False</td>
<td align="left">High</td>
<td align="left">Mascot (O4)</td>
<td align="left">Unambiguous</td>
<td align="left">[K].gFQQILAGEYDHLPEQAFYMVGPIEEAVAk.[A]</td>
<td align="left">N-Term(TMT6plex); K30(TMT6plex)</td>
<td align="left"></td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">P06576</td>
<td align="left">ATP synthase subunit beta, mitochondrial OS=Homo sapiens GN=ATP5B PE=1 SV=3</td>
<td align="left">P06576</td>
<td align="left">ATP synthase subunit beta, mitochondrial OS=Homo sapiens GN=ATP5B PE=1 SV=3</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">1.0000</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1270.3249</td>
<td align="right">3808.960</td>
<td align="right">3808.966</td>
<td align="right">-1.51</td>
<td align="right">-0.00192</td>
<td align="left">CID</td>
<td align="left">MS2</td>
<td align="right">47.955590</td>
<td align="right">8.7</td>
<td align="right">50.000</td>
<td align="right">212.2487</td>
<td align="right">112815</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture1_03.raw</td>
<td align="left">F1</td>
<td align="right">2548.326</td>
<td align="right">3231.929</td>
<td align="right">2760.839</td>
<td align="right">4111.639</td>
<td align="right">3127.254</td>
<td align="right">1874.163</td>
<td align="right">2831.423</td>
<td align="right">2298.401</td>
<td align="right">3798.876</td>
<td align="right">3739.067</td>
<td align="left">NA</td>
<td align="right">90</td>
<td align="right">28</td>
<td align="right">21</td>
<td align="right">0.0000000</td>
<td align="right">0</td>
<td align="right">0.0000140</td>
</tr>
<tr class="even">
<td align="left">False</td>
<td align="left">High</td>
<td align="left">Mascot (K2)</td>
<td align="left">Unambiguous</td>
<td align="left">[R].qYPWGVAEVENGEHcDFTILr.[N]</td>
<td align="left">N-Term(TMT6plex); C15(Carbamidomethyl); R21(Label:13C(6)15N(4))</td>
<td align="left"></td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">Q16181</td>
<td align="left">Septin-7 OS=Homo sapiens GN=SEPT7 PE=1 SV=2</td>
<td align="left">Q16181</td>
<td align="left">Septin-7 OS=Homo sapiens GN=SEPT7 PE=1 SV=2</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">1.0000</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">920.4493</td>
<td align="right">2759.333</td>
<td align="right">2759.332</td>
<td align="right">0.31</td>
<td align="right">0.00028</td>
<td align="left">CID</td>
<td align="left">MS2</td>
<td align="right">9.377507</td>
<td align="right">8.1</td>
<td align="right">3.242</td>
<td align="right">164.7507</td>
<td align="right">87392</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture3_03.raw</td>
<td align="left">F5</td>
<td align="right">22861.765</td>
<td align="right">25817.946</td>
<td align="right">23349.498</td>
<td align="right">29449.609</td>
<td align="right">25995.929</td>
<td align="right">22955.769</td>
<td align="right">30578.971</td>
<td align="right">30660.488</td>
<td align="right">38728.853</td>
<td align="right">25047.280</td>
<td align="left">NA</td>
<td align="right">76</td>
<td align="right">24</td>
<td align="right">17</td>
<td align="right">0.0000001</td>
<td align="right">0</td>
<td align="right">0.0000003</td>
</tr>
<tr class="odd">
<td align="left">False</td>
<td align="left">High</td>
<td align="left">Mascot (K2)</td>
<td align="left">Unambiguous</td>
<td align="left">[R].dkPSVEPVEEYDYEDLk.[E]</td>
<td align="left">N-Term(TMT6plex); K2(Label); K17(Label)</td>
<td align="left"></td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">Q9Y450</td>
<td align="left">HBS1-like protein OS=Homo sapiens GN=HBS1L PE=1 SV=1</td>
<td align="left">Q9Y450</td>
<td align="left">HBS1-like protein OS=Homo sapiens GN=HBS1L PE=1 SV=1</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0.9730</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">920.1605</td>
<td align="right">2758.467</td>
<td align="right">2758.461</td>
<td align="right">2.08</td>
<td align="right">0.00192</td>
<td align="left">CID</td>
<td align="left">MS2</td>
<td align="right">38.317050</td>
<td align="right">17.8</td>
<td align="right">13.596</td>
<td align="right">143.4534</td>
<td align="right">74786</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture3_03.raw</td>
<td align="left">F5</td>
<td align="right">25504.083</td>
<td align="right">27740.450</td>
<td align="right">25144.974</td>
<td align="right">25754.579</td>
<td align="right">29923.176</td>
<td align="right">34097.637</td>
<td align="right">31650.255</td>
<td align="right">27632.692</td>
<td align="right">23886.881</td>
<td align="right">35331.092</td>
<td align="left">NA</td>
<td align="right">74</td>
<td align="right">30</td>
<td align="right">23</td>
<td align="right">0.0000004</td>
<td align="right">0</td>
<td align="right">0.0000010</td>
</tr>
<tr class="even">
<td align="left">False</td>
<td align="left">High</td>
<td align="left">Mascot (F2)</td>
<td align="left">Selected</td>
<td align="left">[R].hEHQVMLmr.[Q]</td>
<td align="left">N-Term(TMT6plex); M8(Oxidation); R9(Label:13C(6)15N(4))</td>
<td align="left"></td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">Q15233</td>
<td align="left">Non-POU domain-containing octamer-binding protein OS=Homo sapiens GN=NONO PE=1 SV=4</td>
<td align="left">Q15233</td>
<td align="left">Non-POU domain-containing octamer-binding protein OS=Homo sapiens GN=NONO PE=1 SV=4</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">0.5250</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">359.6898</td>
<td align="right">1435.737</td>
<td align="right">1435.738</td>
<td align="right">-0.04</td>
<td align="right">-0.00002</td>
<td align="left">CID</td>
<td align="left">MS2</td>
<td align="right">21.390040</td>
<td align="right">36.5</td>
<td align="right">50.000</td>
<td align="right">21.6426</td>
<td align="right">6458</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture4_02.raw</td>
<td align="left">F10</td>
<td align="right">13493.228</td>
<td align="right">14674.490</td>
<td align="right">11187.900</td>
<td align="right">12831.495</td>
<td align="right">13839.426</td>
<td align="right">12441.353</td>
<td align="right">13450.885</td>
<td align="right">14777.844</td>
<td align="right">13039.995</td>
<td align="right">12057.121</td>
<td align="left">NA</td>
<td align="right">40</td>
<td align="right">25</td>
<td align="right">18</td>
<td align="right">0.0003351</td>
<td align="right">0</td>
<td align="right">0.0001175</td>
</tr>
<tr class="odd">
<td align="left">False</td>
<td align="left">High</td>
<td align="left">Mascot (K2)</td>
<td align="left">Unambiguous</td>
<td align="left">[R].dNLTLWTADNAGEEGGEAPQEPQS.[-]</td>
<td align="left">N-Term(TMT6plex)</td>
<td align="left"></td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">P31947</td>
<td align="left">14-3-3 protein sigma OS=Homo sapiens GN=SFN PE=1 SV=1</td>
<td align="left">P31947</td>
<td align="left">14-3-3 protein sigma OS=Homo sapiens GN=SFN PE=1 SV=1</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">1.0000</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">920.0943</td>
<td align="right">2758.268</td>
<td align="right">2758.264</td>
<td align="right">1.53</td>
<td align="right">0.00141</td>
<td align="left">CID</td>
<td align="left">MS2</td>
<td align="right">0.000000</td>
<td align="right">16.7</td>
<td align="right">6.723</td>
<td align="right">174.1863</td>
<td align="right">92950</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture3_03.raw</td>
<td align="left">F5</td>
<td align="right">64582.786</td>
<td align="right">50576.417</td>
<td align="right">47126.037</td>
<td align="right">56285.129</td>
<td align="right">46257.310</td>
<td align="right">52634.885</td>
<td align="right">49716.850</td>
<td align="right">60660.574</td>
<td align="right">55830.488</td>
<td align="right">40280.577</td>
<td align="left">NA</td>
<td align="right">38</td>
<td align="right">21</td>
<td align="right">14</td>
<td align="right">0.0002153</td>
<td align="right">0</td>
<td align="right">0.0000138</td>
</tr>
<tr class="even">
<td align="left">False</td>
<td align="left">High</td>
<td align="left">Mascot (K2)</td>
<td align="left">Unambiguous</td>
<td align="left">[R].aLVAIGTHDLDTLSGPFTYTAk.[R]</td>
<td align="left">N-Term(TMT6plex); K22(Label)</td>
<td align="left"></td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">Q9NSD9</td>
<td align="left">Phenylalanine–tRNA ligase beta subunit OS=Homo sapiens GN=FARSB PE=1 SV=3</td>
<td align="left">Q9NSD9</td>
<td align="left">Phenylalanine–tRNA ligase beta subunit OS=Homo sapiens GN=FARSB PE=1 SV=3</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">0.9783</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">919.8502</td>
<td align="right">2757.536</td>
<td align="right">2757.532</td>
<td align="right">1.48</td>
<td align="right">0.00136</td>
<td align="left">CID</td>
<td align="left">MS2</td>
<td align="right">30.619960</td>
<td align="right">26.7</td>
<td align="right">8.958</td>
<td align="right">176.4863</td>
<td align="right">94294</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture3_03.raw</td>
<td align="left">F5</td>
<td align="right">35404.709</td>
<td align="right">31905.852</td>
<td align="right">30993.941</td>
<td align="right">36854.351</td>
<td align="right">37506.001</td>
<td align="right">25703.444</td>
<td align="right">38626.598</td>
<td align="right">35447.942</td>
<td align="right">33788.409</td>
<td align="right">32031.516</td>
<td align="left">NA</td>
<td align="right">46</td>
<td align="right">29</td>
<td align="right">22</td>
<td align="right">0.0002060</td>
<td align="right">0</td>
<td align="right">0.0000720</td>
</tr>
</tbody>
</table>
<p>There is a peculiarity with the dataset: the spectra have been
identified with 2 nodes. In one node, the authors searched the
SwissProt database for proteins with static modifications related to
the metabolic labelling, in the other node they searched the Sigma_UPS
protein database without these static modifications. However, some
spectra were identified by both nodes leading to duplicate PSMs. We
here remove these duplicated PSMs that are identification artefacts.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="sec-advanced.html#cb98-1" tabindex="-1"></a>duplicatesQuants <span class="ot">&lt;-</span> <span class="fu">duplicated</span>(psms[, qcols]) <span class="sc">|</span> <span class="fu">duplicated</span>(psms[, qcols], <span class="at">fromLast =</span> <span class="cn">TRUE</span>)</span>
<span id="cb98-2"><a href="sec-advanced.html#cb98-2" tabindex="-1"></a>psms <span class="ot">&lt;-</span> psms[<span class="sc">!</span>duplicatesQuants, ]</span></code></pre></div>
<p>We will also subset the data set to reduce computational costs. If you
want to run the analysis on the full data set, you can skip this code
chunk. The subsetting will keep all UPS proteins, known to be
differentially abundant by experimental design, and we will keep 500
background proteins known to be unchanged across condition.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="sec-advanced.html#cb99-1" tabindex="-1"></a>allProteins <span class="ot">&lt;-</span> <span class="fu">unique</span>(psms<span class="sc">$</span>Protein.Accessions)</span>
<span id="cb99-2"><a href="sec-advanced.html#cb99-2" tabindex="-1"></a>upsProteins <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">"ups"</span>, allProteins, <span class="at">value =</span> <span class="cn">TRUE</span>)</span>
<span id="cb99-3"><a href="sec-advanced.html#cb99-3" tabindex="-1"></a>helaProteins <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">"ups"</span>, allProteins, <span class="at">value =</span> <span class="cn">TRUE</span>, <span class="at">invert =</span> <span class="cn">TRUE</span>)</span>
<span id="cb99-4"><a href="sec-advanced.html#cb99-4" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb99-5"><a href="sec-advanced.html#cb99-5" tabindex="-1"></a>keepProteins <span class="ot">&lt;-</span> <span class="fu">c</span>(upsProteins, <span class="fu">sample</span>(helaProteins, <span class="dv">500</span>))</span>
<span id="cb99-6"><a href="sec-advanced.html#cb99-6" tabindex="-1"></a>psms <span class="ot">&lt;-</span> psms[psms<span class="sc">$</span>Protein.Accessions <span class="sc">%in%</span> keepProteins, ]</span></code></pre></div>
</div>
<div id="sample-annotation-table" class="section level3" number="3.3.3">
<h3>
<span class="header-section-number">3.3.3</span> Sample annotation table<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sample-annotation-table')" onmouseout="reset_tooltip('sample-annotation-table-tooltip')"><span class="tooltiptext" id="sample-annotation-table-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>The purpose and structure of the sample annotation table is identical
across proteomics experiments (see introduction to the <a href="sec-basics.html#sec-annotation_table">sample
annotation table</a>). The annotation table used
in this tutorial has been generated by the authors.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="sec-advanced.html#cb100-1" tabindex="-1"></a>coldata <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(annotFile)</span></code></pre></div>
<p>We perform a little cleanup:</p>
<ol style="list-style-type: decimal">
<li>We keep only the sample annotations that are meaningful to the
experiment and that are not redundant with other annotations.</li>
<li>We extract the run identifier from the MS file name (which we store
as the <code>File.Name</code> annotation).</li>
<li>The TMT used for labelling each sample is stored in the <code>Channel</code>
column. We however prefer to use the less esoteric term <code>Label</code>
for more clarity with the main text when we’ll discuss labelling
effects.</li>
</ol>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="sec-advanced.html#cb101-1" tabindex="-1"></a><span class="do">## 1.</span></span>
<span id="cb101-2"><a href="sec-advanced.html#cb101-2" tabindex="-1"></a>coldata <span class="ot">&lt;-</span> coldata[, <span class="fu">c</span>(<span class="st">"Run"</span>, <span class="st">"Channel"</span>, <span class="st">"Condition"</span>, <span class="st">"Mixture"</span>, <span class="st">"TechRepMixture"</span>)]</span>
<span id="cb101-3"><a href="sec-advanced.html#cb101-3" tabindex="-1"></a><span class="do">## 2.</span></span>
<span id="cb101-4"><a href="sec-advanced.html#cb101-4" tabindex="-1"></a>coldata<span class="sc">$</span>File.Name <span class="ot">&lt;-</span> coldata<span class="sc">$</span>Run</span>
<span id="cb101-5"><a href="sec-advanced.html#cb101-5" tabindex="-1"></a>coldata<span class="sc">$</span>Run <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">"^.*(Mix.*).raw"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, coldata<span class="sc">$</span>Run)</span>
<span id="cb101-6"><a href="sec-advanced.html#cb101-6" tabindex="-1"></a><span class="do">## 3.</span></span>
<span id="cb101-7"><a href="sec-advanced.html#cb101-7" tabindex="-1"></a><span class="fu">colnames</span>(coldata)[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">"Label"</span></span></code></pre></div>
<table>
<colgroup>
<col width="12%">
<col width="6%">
<col width="10%">
<col width="9%">
<col width="15%">
<col width="46%">
</colgroup>
<thead><tr class="header">
<th align="left">Run</th>
<th align="left">Label</th>
<th align="left">Condition</th>
<th align="left">Mixture</th>
<th align="right">TechRepMixture</th>
<th align="left">File.Name</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Mixture1_01</td>
<td align="left">126</td>
<td align="left">Norm</td>
<td align="left">Mixture1</td>
<td align="right">1</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw</td>
</tr>
<tr class="even">
<td align="left">Mixture1_01</td>
<td align="left">127N</td>
<td align="left">0.667</td>
<td align="left">Mixture1</td>
<td align="right">1</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw</td>
</tr>
<tr class="odd">
<td align="left">Mixture1_01</td>
<td align="left">127C</td>
<td align="left">0.125</td>
<td align="left">Mixture1</td>
<td align="right">1</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw</td>
</tr>
<tr class="even">
<td align="left">Mixture1_01</td>
<td align="left">128N</td>
<td align="left">0.5</td>
<td align="left">Mixture1</td>
<td align="right">1</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw</td>
</tr>
<tr class="odd">
<td align="left">Mixture1_01</td>
<td align="left">128C</td>
<td align="left">1</td>
<td align="left">Mixture1</td>
<td align="right">1</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw</td>
</tr>
<tr class="even">
<td align="left">Mixture1_01</td>
<td align="left">129N</td>
<td align="left">0.125</td>
<td align="left">Mixture1</td>
<td align="right">1</td>
<td align="left">161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw</td>
</tr>
</tbody>
</table>
</div>
<div id="sec_advanced_readqf" class="section level3" number="3.3.4">
<h3>
<span class="header-section-number">3.3.4</span> Convert to QFeatures<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sec_advanced_readqf')" onmouseout="reset_tooltip('sec_advanced_readqf-tooltip')"><span class="tooltiptext" id="sec_advanced_readqf-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>We use <code>readQFeatures()</code> to create a <a href="sec-basics.html#sec-qfeatures"><code>QFeatures</code>
object</a>. Since we start from the PSM-level data, the
approach is somewhat more elaborate<label for="tufte-sn-20" class="margin-toggle sidenote-number">20</label><input type="checkbox" id="tufte-sn-20" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">20</span> You can find an illustrated
step-by-step guide in the <a href="https://rformassspectrometry.github.io/QFeatures/articles/read_QFeatures.html">QFeatures
vignette</a></span>.
First, recall that every quantitative column in the PSM table contains
information for multiple runs. Therefore, the function split the table
based on the run identifier, given by the <code>runCol</code> argument (for
Skyline, that identifier is contained in <code>Spectrum.File</code>). So, the
<code>QFeatures</code> object after import will contain as many sets as there are
runs. Next, the function links the annotation table with the PSM data.
To achieve this, the annotation table must contain a <code>runCol</code> column
that provides the run identifier in which each sample has been
acquired, and this information will be used to match the identifiers
in the <code>Spectrum.File</code> column of the PSM table. The annotation table
must also contain a <code>quantCols</code> column that tells the function which
column in the PSM table contains the quantitative information for a
given sample. In this case, the <code>quantCols</code> depend on</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="sec-advanced.html#cb102-1" tabindex="-1"></a>coldata<span class="sc">$</span>runCol <span class="ot">&lt;-</span> coldata<span class="sc">$</span>File.Name</span>
<span id="cb102-2"><a href="sec-advanced.html#cb102-2" tabindex="-1"></a>coldata<span class="sc">$</span>quantCols <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"Abundance.."</span>, coldata<span class="sc">$</span>Label)</span>
<span id="cb102-3"><a href="sec-advanced.html#cb102-3" tabindex="-1"></a>(spikein <span class="ot">&lt;-</span> <span class="fu">readQFeatures</span>(</span>
<span id="cb102-4"><a href="sec-advanced.html#cb102-4" tabindex="-1"></a>  psms, <span class="at">colData =</span> coldata,</span>
<span id="cb102-5"><a href="sec-advanced.html#cb102-5" tabindex="-1"></a>  <span class="at">runCol =</span> <span class="st">"Spectrum.File"</span>,</span>
<span id="cb102-6"><a href="sec-advanced.html#cb102-6" tabindex="-1"></a>  <span class="at">quantCols =</span> qcols</span>
<span id="cb102-7"><a href="sec-advanced.html#cb102-7" tabindex="-1"></a>))</span></code></pre></div>
<pre><code>## An instance of class QFeatures (type: bulk) with 15 sets:
## 
##  [1] 161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw: SummarizedExperiment with 1905 rows and 10 columns 
##  [2] 161117_SILAC_HeLa_UPS1_TMT10_Mixture1_02.raw: SummarizedExperiment with 1902 rows and 10 columns 
##  [3] 161117_SILAC_HeLa_UPS1_TMT10_Mixture1_03.raw: SummarizedExperiment with 1952 rows and 10 columns 
##  ...
##  [13] 161117_SILAC_HeLa_UPS1_TMT10_Mixture5_01.raw: SummarizedExperiment with 1919 rows and 10 columns 
##  [14] 161117_SILAC_HeLa_UPS1_TMT10_Mixture5_02.raw: SummarizedExperiment with 1909 rows and 10 columns 
##  [15] 161117_SILAC_HeLa_UPS1_TMT10_Mixture5_03.raw: SummarizedExperiment with 1844 rows and 10 columns</code></pre>
<p>We now have a <code>QFeatures</code> object with 15 sets, each containing data
associated with an MS run. The name of each set is defined by the name
of the corresponding file name of the run, which is unnecessarily
long. We simplify the set names, although this step is optional and
only meant to improve the clarity of the output.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="sec-advanced.html#cb104-1" tabindex="-1"></a><span class="do">## This is optional</span></span>
<span id="cb104-2"><a href="sec-advanced.html#cb104-2" tabindex="-1"></a><span class="fu">names</span>(spikein) <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">"^.*(Mix.*).raw"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, <span class="fu">names</span>(spikein))</span>
<span id="cb104-3"><a href="sec-advanced.html#cb104-3" tabindex="-1"></a>(inputNames <span class="ot">&lt;-</span> <span class="fu">names</span>(spikein))</span></code></pre></div>
<pre><code>##  [1] "Mixture1_01" "Mixture1_02" "Mixture1_03" "Mixture2_01" "Mixture2_02" "Mixture2_03" "Mixture3_01" "Mixture3_02" "Mixture3_03"
## [10] "Mixture4_01" "Mixture4_02" "Mixture4_03" "Mixture5_01" "Mixture5_02" "Mixture5_03"</code></pre>
</div>
</div>
<div id="data-preprocessing" class="section level2" number="3.4">
<h2>
<span class="header-section-number">3.4</span> Data preprocessing<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('data-preprocessing')" onmouseout="reset_tooltip('data-preprocessing-tooltip')"><span class="tooltiptext" id="data-preprocessing-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>Similar to the <a href="sec-basics.html#sec-basic_preprocess">basic concepts chapter</a>, we
will use the <code>QFeatures</code>’ data preprocessing functionality. The
data preprocessing workflow for TMT data is similar to the workflow
for LFQ data, but there are subtle differences associated with the
fact that we start from PSM-level data, namely the PSM filtering is
mode complex and the data preprocessing will be applied for each run
separately to remove part of the run effect.</p>
<div id="encoding-missing-values" class="section level3" number="3.4.1">
<h3>
<span class="header-section-number">3.4.1</span> Encoding missing values<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('encoding-missing-values')" onmouseout="reset_tooltip('encoding-missing-values-tooltip')"><span class="tooltiptext" id="encoding-missing-values-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>Any zero value needs to be <a href="sec-basics.html#sec-encode_missing">encoded by a missing
value</a>.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="sec-advanced.html#cb106-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">zeroIsNA</span>(spikein, inputNames)</span></code></pre></div>
</div>
<div id="log2-transformation" class="section level3" number="3.4.2">
<h3>
<span class="header-section-number">3.4.2</span> Log2 transformation<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('log2-transformation')" onmouseout="reset_tooltip('log2-transformation-tooltip')"><span class="tooltiptext" id="log2-transformation-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>Similar to any MS-based proteomics data, TMT data are heteroskedastic,
with a strong mean-variance relationship. This is illustrated by the
intensities and log2-intensities for one of the peptide ions, the
triply charged DLLHVLAFSK, in function of the UPS spike-in dilution
factor.</p>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-193-1.png" width="672"></p>
<p>Log2-transformation solves the heteroskedasticity issue, but also
provides a scale that directly relates to biological interpretation
(see the <a href="sec-basics.html#sec-log2">basic concepts chapter</a>). We perform
log2-transformation with <code>logTransform()</code> from the <code>QFeatures</code> package.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="sec-advanced.html#cb107-1" tabindex="-1"></a>logNames  <span class="ot">&lt;-</span> <span class="fu">paste0</span>(inputNames, <span class="st">"_log"</span>)</span>
<span id="cb107-2"><a href="sec-advanced.html#cb107-2" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">logTransform</span>(</span>
<span id="cb107-3"><a href="sec-advanced.html#cb107-3" tabindex="-1"></a>    spikein, inputNames, <span class="at">name =</span> logNames, <span class="at">base =</span> <span class="dv">2</span></span>
<span id="cb107-4"><a href="sec-advanced.html#cb107-4" tabindex="-1"></a>)</span></code></pre></div>
</div>
<div id="sample-filtering" class="section level3" number="3.4.3">
<h3>
<span class="header-section-number">3.4.3</span> Sample filtering<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sample-filtering')" onmouseout="reset_tooltip('sample-filtering-tooltip')"><span class="tooltiptext" id="sample-filtering-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>We first remove the reference samples. These samples were used by the
MSstatsTMT authors to obtain normalisation factors <span class="citation">(<label for="tufte-mn-12" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-12" class="margin-toggle">Huang et al. 2020<span class="marginnote">Huang, Ting, Meena Choi, Manuel Tzouros, Sabrina Golling, Nikhil Janak Pandya, Balazs Banfai, Tom Dunkley, and Olga Vitek. 2020. <span>“<span>MSstatsTMT</span>: Statistical Detection of Differentially Abundant Proteins in Experiments with Isobaric Labeling and Multiple Mixtures.”</span> <em>Mol. Cell. Proteomics</em> 19 (10): 1706–23.</span>)</span>.
However, this approach ignores the uncertainty associated with the
measurement with these reference samples, potentially inflating the
noise in the samples of interest. Hence, <code>msqrob2</code> workflows do not
use reference normalisation. In practice, we found no impact on model
performance <span class="citation">(<label for="tufte-mn-13" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-13" class="margin-toggle">Vandenbulcke et al. 2025<span class="marginnote">Vandenbulcke, Stijn, Christophe Vanderaa, Oliver Crook, Lennart Martens, and Lieven Clement. 2025. <span>“<span>Msqrob2TMT</span>: Robust Linear Mixed Models for Inferring Differential Abundant Proteins in Labeled Experiments with Arbitrarily Complex Design.”</span> <em>Mol. Cell. Proteomics</em> 24 (7): 101002.</span>)</span>, hence we favor a more parsimonious
approach. The information is available from the <code>colData</code>, under the
<code>Condition</code> column. We remove any sample that is marked as <code>Norm</code>
using <code>subsetByColData()</code>.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="sec-advanced.html#cb108-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">subsetByColData</span>(spikein, spikein<span class="sc">$</span>Condition <span class="sc">!=</span> <span class="st">"Norm"</span>)</span></code></pre></div>
</div>
<div id="sec-filter" class="section level3" number="3.4.4">
<h3>
<span class="header-section-number">3.4.4</span> PSM filtering<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sec-filter')" onmouseout="reset_tooltip('sec-filter-tooltip')"><span class="tooltiptext" id="sec-filter-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>Filtering removes low-quality and unreliable PSMs that would otherwise
introduce noise and artefacts in the data. Conceptually, PSM filtering
is identical to <a href="sec-basics.html#sec-filter">peptide filtering</a>, but we will here
apply filtering criteria for which some are not readily available in
the data. Therefore, we will add custom filtering variable to the
<code>rowData</code> that will then be used with <code>filterFeatures()</code>. This
provides an ideal use case to demonstrate the customisation of a
filtering workflow.</p>
<p><strong>TODO</strong>: use some of the QFeaturesGUI functions?</p>
<div id="remove-ambiguous-identifications" class="section level4" number="3.4.4.1">
<h4>
<span class="header-section-number">3.4.4.1</span> Remove ambiguous identifications</h4>
<p>The background proteins originate from HeLa cells, which also contain
UPS proteins. The background UPS proteins and the spiked-in UPS
proteins differ in metabolic labelling, so we should be able to
distinguish them. We used the PSM-level data searched with mascot, as
provided by the MSstatsTMT authors who used two mascot identification
nodes. In one node they searched the SwissProt database for proteins
with static modifications related to the metabolic labelling, in the
other node they searched the Sigma_UPS protein database without these
static modifications. Ideally, this should separate the spiked-in UPS
proteins and the UPS proteins from the HeLa cells, however, this is
not always the case. The SwissProt search is expected to return
peptide-spectrum matches (PSMs) for all proteins, including non-UPS
HeLa, UPS HeLa, and spike-in UPS proteins. Conversely, the Sigma_UPS
search is expected to return PSMs exclusively for spike-in UPS
proteins. However, a PSM that matches a UPS protein in the SwissProt
search but is not identified as such in the Sigma_UPS search could
either correctly originate from a HeLa protein or represent a
spiked-in UPS protein that was not recognised as such in the Sigma_UPS
search. Additionally, there are ambiguous PSMs that are not matched to
a UPS protein in the HeLa search but are matched to a UPS protein in
the SwissProt search. To address this, we exclude these ambiguous
proteins from the analysis.</p>
<p>To define the amibiguous PSMs, we retrieve the PSM annotations from
the <code>rowData</code> and create a new colum indicating whether a PSM belongs
to a UPS protein or not, based on the protein SwissProt identifiers.
For this, we apply a custom filtering worklow:</p>
<ol style="list-style-type: decimal">
<li>
<strong>Collect data</strong>: combine all the <code>rowData</code> information in a single
table. We will apply the filter on the</li>
</ol>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="sec-advanced.html#cb109-1" tabindex="-1"></a>rowdata <span class="ot">&lt;-</span> <span class="fu">rbindRowData</span>(spikein, logNames)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>
<strong>Compute new variable</strong>: (2a) define whether the PSM’s protein
group is a UPS protein and then (2b) define an ambiguous PSM as a
PSM that is marked as UPS by the SwissProt identifier but not by
the Sigma_UPS node (<code>Marked.as</code> column), and inversely.</li>
</ol>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="sec-advanced.html#cb110-1" tabindex="-1"></a><span class="do">## 2a.</span></span>
<span id="cb110-2"><a href="sec-advanced.html#cb110-2" tabindex="-1"></a>rowdata<span class="sc">$</span>isUps <span class="ot">&lt;-</span> <span class="st">"no"</span></span>
<span id="cb110-3"><a href="sec-advanced.html#cb110-3" tabindex="-1"></a>isUpsProtein <span class="ot">&lt;-</span> <span class="fu">grepl</span>(<span class="st">"ups"</span>, rowdata<span class="sc">$</span>Protein.Accessions)</span>
<span id="cb110-4"><a href="sec-advanced.html#cb110-4" tabindex="-1"></a>rowdata<span class="sc">$</span>isUps[isUpsProtein] <span class="ot">&lt;-</span> <span class="st">"yes"</span></span>
<span id="cb110-5"><a href="sec-advanced.html#cb110-5" tabindex="-1"></a><span class="do">## 2b.</span></span>
<span id="cb110-6"><a href="sec-advanced.html#cb110-6" tabindex="-1"></a>rowdata<span class="sc">$</span>isUps[<span class="sc">!</span>isUpsProtein <span class="sc">&amp;</span> <span class="fu">grepl</span>(<span class="st">"UPS"</span>, rowdata<span class="sc">$</span>Marked.as)] <span class="ot">&lt;-</span> <span class="st">"amb"</span></span>
<span id="cb110-7"><a href="sec-advanced.html#cb110-7" tabindex="-1"></a>rowdata<span class="sc">$</span>isUps[isUpsProtein <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"UPS"</span>, rowdata<span class="sc">$</span>Marked.as)] <span class="ot">&lt;-</span> <span class="st">"amb"</span></span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>
<strong>Reinsert in the rowData</strong>: insert the modified table with new
information back in the <code>rowData</code> of the different sets. This means
that the single table with <code>rowData</code> information needs to be split
by each set. <code>split()</code> will produce a named list of tables and each
table will be iteratively inserted as <code>rowData</code> of the set.</li>
</ol>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="sec-advanced.html#cb111-1" tabindex="-1"></a><span class="fu">rowData</span>(spikein) <span class="ot">&lt;-</span> <span class="fu">split</span>(rowdata, rowdata<span class="sc">$</span>assay)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>
<strong>Apply the filter</strong>: the filtering is performed by
<code>filterFeatures()</code> using the new information from the <code>rowData</code>. We
specify <code>keep = TRUE</code> because the input sets (before
log-transformation) do not contain the filtering variable, so we
tell the function to keep all PSMs for the sets that don’t have the
variable <code>isUps</code>.</li>
</ol>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="sec-advanced.html#cb112-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">filterFeatures</span>(spikein, <span class="sc">~</span> isUps <span class="sc">!=</span> <span class="st">"amb"</span>, <span class="at">keep =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="remove-failed-protein-inference-1" class="section level4" number="3.4.4.2">
<h4>
<span class="header-section-number">3.4.4.2</span> Remove failed protein inference</h4>
<p>Next, we remove PSMs that could not be mapped to a protein or that map
to multiple proteins, i.e. a protein group. For the latter, the
protein identifier contains multiple identifiers separated by a <code>;</code>).
This information is readily available in the <code>rowData</code>, so there is no
need for a custom filtering.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="sec-advanced.html#cb113-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">filterFeatures</span>(</span>
<span id="cb113-2"><a href="sec-advanced.html#cb113-2" tabindex="-1"></a>    spikein, <span class="sc">~</span> Protein.Accessions <span class="sc">!=</span> <span class="st">""</span> <span class="sc">&amp;</span> <span class="do">## Remove failed protein inference</span></span>
<span id="cb113-3"><a href="sec-advanced.html#cb113-3" tabindex="-1"></a>        <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">";"</span>, Protein.Accessions)) <span class="do">## Remove protein groups</span></span></code></pre></div>
</div>
<div id="remove-inconsistent-protein-inference" class="section level4" number="3.4.4.3">
<h4>
<span class="header-section-number">3.4.4.3</span> Remove inconsistent protein inference</h4>
<p>We also remove peptide ions that map to a different protein depending
on the run. Again, this requires a custom filtering and we apply the
same filtering workflow as above.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="sec-advanced.html#cb114-1" tabindex="-1"></a><span class="do">## 1. Collect data</span></span>
<span id="cb114-2"><a href="sec-advanced.html#cb114-2" tabindex="-1"></a>rowdata <span class="ot">&lt;-</span> <span class="fu">rbindRowData</span>(spikein, logNames)</span>
<span id="cb114-3"><a href="sec-advanced.html#cb114-3" tabindex="-1"></a><span class="do">## 2. Compute new variable</span></span>
<span id="cb114-4"><a href="sec-advanced.html#cb114-4" tabindex="-1"></a>rowdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(rowdata) <span class="sc">|&gt;</span></span>
<span id="cb114-5"><a href="sec-advanced.html#cb114-5" tabindex="-1"></a>    <span class="fu">group_by</span>(Annotated.Sequence, Charge) <span class="sc">|&gt;</span></span>
<span id="cb114-6"><a href="sec-advanced.html#cb114-6" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">nProtsMapped =</span> <span class="fu">length</span>(<span class="fu">unique</span>(Protein.Accessions)))</span>
<span id="cb114-7"><a href="sec-advanced.html#cb114-7" tabindex="-1"></a><span class="do">## 3. Reinsert in the rowData</span></span>
<span id="cb114-8"><a href="sec-advanced.html#cb114-8" tabindex="-1"></a><span class="fu">rowData</span>(spikein) <span class="ot">&lt;-</span> <span class="fu">split</span>(rowdata, rowdata<span class="sc">$</span>assay)</span>
<span id="cb114-9"><a href="sec-advanced.html#cb114-9" tabindex="-1"></a><span class="do">## 4. Apply the filter</span></span>
<span id="cb114-10"><a href="sec-advanced.html#cb114-10" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">filterFeatures</span>(spikein, <span class="sc">~</span> nProtsMapped <span class="sc">==</span> <span class="dv">1</span>, <span class="at">keep =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="remove-one-run-wonders" class="section level4" number="3.4.4.4">
<h4>
<span class="header-section-number">3.4.4.4</span> Remove one-run wonders</h4>
<p>We also remove proteins that can only be found in one run as such
proteins may not be trustworthy. In this case,</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="sec-advanced.html#cb115-1" tabindex="-1"></a><span class="do">## 1. Collect data</span></span>
<span id="cb115-2"><a href="sec-advanced.html#cb115-2" tabindex="-1"></a>rowdata <span class="ot">&lt;-</span> <span class="fu">rbindRowData</span>(spikein, logNames)</span>
<span id="cb115-3"><a href="sec-advanced.html#cb115-3" tabindex="-1"></a><span class="do">## 2. Compute new variable</span></span>
<span id="cb115-4"><a href="sec-advanced.html#cb115-4" tabindex="-1"></a>rowdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(rowdata) <span class="sc">|&gt;</span></span>
<span id="cb115-5"><a href="sec-advanced.html#cb115-5" tabindex="-1"></a>    <span class="fu">group_by</span>(Protein.Accessions) <span class="sc">|&gt;</span></span>
<span id="cb115-6"><a href="sec-advanced.html#cb115-6" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">nRuns =</span> <span class="fu">length</span>(<span class="fu">unique</span>(assay)))</span>
<span id="cb115-7"><a href="sec-advanced.html#cb115-7" tabindex="-1"></a><span class="do">## 3. Reinsert in the rowData</span></span>
<span id="cb115-8"><a href="sec-advanced.html#cb115-8" tabindex="-1"></a><span class="fu">rowData</span>(spikein) <span class="ot">&lt;-</span> <span class="fu">split</span>(rowdata, rowdata<span class="sc">$</span>assay)</span>
<span id="cb115-9"><a href="sec-advanced.html#cb115-9" tabindex="-1"></a><span class="do">## 4. Apply the filter</span></span>
<span id="cb115-10"><a href="sec-advanced.html#cb115-10" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">filterFeatures</span>(spikein, <span class="sc">~</span> nRuns <span class="sc">&gt;</span> <span class="dv">1</span>, <span class="at">keep =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="sec-duplicated_psms" class="section level4" number="3.4.4.5">
<h4>
<span class="header-section-number">3.4.4.5</span> Remove duplicated PSMs</h4>
<p>Finally, peptide ions that were identified with multiple PSMs in a run
are collapsed to the PSM with the highest summed intensity over the
TMT labels, a strategy that is also used by MSstats.</p>
<p>This filtering requires a more complex workflow because it mixes
information from the <code>rowData</code> (to obtain ion identities) with
quantitative data (to obtain PSM intensity ranks). We therefore
compute the filtering variable for every set iteratively:</p>
<ol style="list-style-type: decimal">
<li>Get the <code>rowData</code> for the current set.</li>
<li>Make a new variable <code>ionID</code>.</li>
<li>We calculate the <code>rowSums</code> for each ion.</li>
<li>Make a new variable <code>psmRank</code> that ranks the PSMs for each ion
identifier based on the summed intensity.</li>
<li>We store the new information back in the <code>rowData</code>.</li>
</ol>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="sec-advanced.html#cb116-1" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> logNames) { <span class="do">## for each set of interest</span></span>
<span id="cb116-2"><a href="sec-advanced.html#cb116-2" tabindex="-1"></a>    rowdata <span class="ot">&lt;-</span> <span class="fu">rowData</span>(spikein[[i]]) <span class="do">## 1.</span></span>
<span id="cb116-3"><a href="sec-advanced.html#cb116-3" tabindex="-1"></a>    rowdata<span class="sc">$</span>ionID <span class="ot">&lt;-</span> <span class="fu">paste0</span>(rowdata<span class="sc">$</span>Annotated.Sequence, rowdata<span class="sc">$</span>Charge) <span class="do">## 2.</span></span>
<span id="cb116-4"><a href="sec-advanced.html#cb116-4" tabindex="-1"></a>    rowdata<span class="sc">$</span>rowSums <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(<span class="fu">assay</span>(spikein[[i]]), <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="do">## 3.</span></span>
<span id="cb116-5"><a href="sec-advanced.html#cb116-5" tabindex="-1"></a>    rowdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(rowdata) <span class="sc">|&gt;</span></span>
<span id="cb116-6"><a href="sec-advanced.html#cb116-6" tabindex="-1"></a>        <span class="fu">group_by</span>(ionID) <span class="sc">|&gt;</span></span>
<span id="cb116-7"><a href="sec-advanced.html#cb116-7" tabindex="-1"></a>        <span class="fu">mutate</span>(<span class="at">psmRank =</span> <span class="fu">rank</span>(<span class="sc">-</span>rowSums)) <span class="do">## 4.</span></span>
<span id="cb116-8"><a href="sec-advanced.html#cb116-8" tabindex="-1"></a>    <span class="fu">rowData</span>(spikein[[i]]) <span class="ot">&lt;-</span> <span class="fu">DataFrame</span>(rowdata) <span class="do">## 5.</span></span>
<span id="cb116-9"><a href="sec-advanced.html#cb116-9" tabindex="-1"></a>}</span></code></pre></div>
<p>For each ion that maps to multiple PSMs, we keep the PSM with the
highest summed intensity, that is that ranks first.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="sec-advanced.html#cb117-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">filterFeatures</span>(spikein, <span class="sc">~</span> psmRank <span class="sc">==</span> <span class="dv">1</span>, <span class="at">keep =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="remove-highly-missing-psms" class="section level4" number="3.4.4.6">
<h4>
<span class="header-section-number">3.4.4.6</span> Remove highly missing PSMs</h4>
<p>We then remove PSMs with five or more missing values out of the ten
TMT labels (&gt;= 50%). This is an arbitrary value that may need to be
adjusted depending on the experiment and the data set.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="sec-advanced.html#cb118-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">filterNA</span>(spikein, logNames, <span class="at">pNA =</span> <span class="fl">0.5</span>)</span></code></pre></div>
</div>
<div id="filtering-wrap-up" class="section level4" number="3.4.4.7">
<h4>
<span class="header-section-number">3.4.4.7</span> Filtering wrap-up</h4>
<p>We have demonstrated the different procedures to perform feature
filtering. Here is a summary (from simple to complex):</p>
<ol style="list-style-type: decimal">
<li>If you want to filter on missing values, use <code>filterNA()</code>.</li>
<li>If you want to filter based on a <code>rowData</code> column, use
<code>filterFeatures()</code>.</li>
<li>If you want to filter based on information that needs to be built
from <code>rowData</code> information, use the following workflow: i. collect
the <code>rowData</code> in a table; ii. compute the new variable; iii.
reinsert the updated table in the <code>rowData</code>; iv. apply the filter
with <code>filterFeatures()</code>.</li>
<li>If you want to filter based on <code>rowData</code> and quantitative
information, iterate the following workflow over each set:
<ol style="list-style-type: lower-roman">
<li>Get the <code>rowData</code> for the current set; ii. Compute the filtering
variable based on <code>rowData</code> and/or quantitative information; iii.
store the new information back in the <code>rowData</code>. Then, the
filtering can be performed by <code>filterFeatures()</code>.</li>
</ol>
</li>
</ol>
<p>When using <code>filterFeatures()</code>, specify <code>keep = TRUE</code> to select all
features for which a custom variable is not available or has not been
computed. By default, the function will remove all the feature of a
set for which the information is not available.</p>
<p>These standard and custom filtering procedures have been demonstrated
on PSM-level data, but the same procedures can be performed at any
data level, e.g. also at peptide or protein level.</p>
</div>
</div>
<div id="normalisation" class="section level3" number="3.4.5">
<h3>
<span class="header-section-number">3.4.5</span> Normalisation<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('normalisation')" onmouseout="reset_tooltip('normalisation-tooltip')"><span class="tooltiptext" id="normalisation-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>Before performing normalisation, we explore the systematic shifts
across the samples (using the pipeline described in the <a href="sec-basics.html#sec-norm">previous
chapter</a>). To facilitate interpretation, we facet the data
by TMT mixture.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="sec-advanced.html#cb119-1" tabindex="-1"></a>spikein[, , logNames] <span class="sc">|&gt;</span></span>
<span id="cb119-2"><a href="sec-advanced.html#cb119-2" tabindex="-1"></a>    <span class="fu">longForm</span>(<span class="at">colvars =</span> <span class="fu">c</span>(<span class="st">"Mixture"</span>, <span class="st">"TechRepMixture"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb119-3"><a href="sec-advanced.html#cb119-3" tabindex="-1"></a>    <span class="fu">data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb119-4"><a href="sec-advanced.html#cb119-4" tabindex="-1"></a>    <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb119-5"><a href="sec-advanced.html#cb119-5" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">colour =</span> <span class="fu">as.factor</span>(TechRepMixture), <span class="at">group =</span> colname) <span class="sc">+</span></span>
<span id="cb119-6"><a href="sec-advanced.html#cb119-6" tabindex="-1"></a>    <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb119-7"><a href="sec-advanced.html#cb119-7" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Intensity distribution for each observational unit"</span>,</span>
<span id="cb119-8"><a href="sec-advanced.html#cb119-8" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">"Before normalisation"</span>,</span>
<span id="cb119-9"><a href="sec-advanced.html#cb119-9" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"Technical replicate"</span>) <span class="sc">+</span></span>
<span id="cb119-10"><a href="sec-advanced.html#cb119-10" tabindex="-1"></a>    <span class="fu">facet_grid</span>(Mixture <span class="sc">~</span> .) <span class="sc">+</span></span>
<span id="cb119-11"><a href="sec-advanced.html#cb119-11" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-206-1.png" width="480"></p>
<p>Similarly to the previous chapter, we again observe misalignments of
the intensity distributions across samples. We see the intensity
distributions cluster by technical replicate. Since each replicate
contains all experimental conditions, we know that these difference
stem from technical variability and not biological variability. We
normalise the data by median centering.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="sec-advanced.html#cb120-1" tabindex="-1"></a>normNames  <span class="ot">&lt;-</span> <span class="fu">paste0</span>(inputNames, <span class="st">"_norm"</span>)</span>
<span id="cb120-2"><a href="sec-advanced.html#cb120-2" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">normalize</span>(</span>
<span id="cb120-3"><a href="sec-advanced.html#cb120-3" tabindex="-1"></a>    spikein, logNames, <span class="at">name =</span> normNames,</span>
<span id="cb120-4"><a href="sec-advanced.html#cb120-4" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"center.median"</span></span>
<span id="cb120-5"><a href="sec-advanced.html#cb120-5" tabindex="-1"></a>)</span></code></pre></div>
<p>And we confirm that the normalisation resulted in a better alignment
of the intensity distribution across samples.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="sec-advanced.html#cb121-1" tabindex="-1"></a>spikein[, , normNames] <span class="sc">|&gt;</span></span>
<span id="cb121-2"><a href="sec-advanced.html#cb121-2" tabindex="-1"></a>    <span class="fu">longForm</span>(<span class="at">colvars =</span> <span class="fu">c</span>(<span class="st">"Mixture"</span>, <span class="st">"TechRepMixture"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb121-3"><a href="sec-advanced.html#cb121-3" tabindex="-1"></a>    <span class="fu">data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb121-4"><a href="sec-advanced.html#cb121-4" tabindex="-1"></a>    <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb121-5"><a href="sec-advanced.html#cb121-5" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">colour =</span> <span class="fu">as.factor</span>(TechRepMixture), <span class="at">group =</span> colname) <span class="sc">+</span></span>
<span id="cb121-6"><a href="sec-advanced.html#cb121-6" tabindex="-1"></a>    <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb121-7"><a href="sec-advanced.html#cb121-7" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Intensity distribution for each observational unit"</span>,</span>
<span id="cb121-8"><a href="sec-advanced.html#cb121-8" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">"Before normalisation"</span>,</span>
<span id="cb121-9"><a href="sec-advanced.html#cb121-9" tabindex="-1"></a>         <span class="at">colour =</span> <span class="st">"Technical replicate"</span>) <span class="sc">+</span></span>
<span id="cb121-10"><a href="sec-advanced.html#cb121-10" tabindex="-1"></a>    <span class="fu">facet_grid</span>(Mixture <span class="sc">~</span> .) <span class="sc">+</span></span>
<span id="cb121-11"><a href="sec-advanced.html#cb121-11" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-208-1.png" width="480"></p>
<p>Up to now, the data from different runs were kept in separate assays.
We can now join the normalised sets into an <code>ions</code> set using
<code>joinAssays()</code>. Sets are joined by stacking the columns (samples) in a
matrix and rows (features) are matched according to a row identifier,
here the <code>ionID</code> from the <code>rowData</code>.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="sec-advanced.html#cb122-1" tabindex="-1"></a>(spikein <span class="ot">&lt;-</span> <span class="fu">joinAssays</span>(</span>
<span id="cb122-2"><a href="sec-advanced.html#cb122-2" tabindex="-1"></a>    spikein, normNames, <span class="at">fcol =</span> <span class="st">"ionID"</span>, <span class="at">name =</span> <span class="st">"ions"</span></span>
<span id="cb122-3"><a href="sec-advanced.html#cb122-3" tabindex="-1"></a>))</span></code></pre></div>
<pre><code>## An instance of class QFeatures (type: bulk) with 46 sets:
## 
##  [1] Mixture1_01: SummarizedExperiment with 1719 rows and 8 columns 
##  [2] Mixture1_02: SummarizedExperiment with 1722 rows and 8 columns 
##  [3] Mixture1_03: SummarizedExperiment with 1776 rows and 8 columns 
##  ...
##  [44] Mixture5_02_norm: SummarizedExperiment with 1646 rows and 8 columns 
##  [45] Mixture5_03_norm: SummarizedExperiment with 1578 rows and 8 columns 
##  [46] ions: SummarizedExperiment with 4066 rows and 120 columns</code></pre>
<p>We have a new set contain 15 runs <span class="math inline">\(\times\)</span> 8 labelled sample = 120
data columns. Note that the 15 sets have 4066
ions in common, leading to a joined set with <code>r nrows(spikein)[["ions"]]</code> rows.</p>
<p>If we want to use protein-level data for modelling, we will need a
summarisation step. Note that this last step is optional.</p>
</div>
<div id="summarisation" class="section level3" number="3.4.6">
<h3>
<span class="header-section-number">3.4.6</span> Summarisation<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('summarisation')" onmouseout="reset_tooltip('summarisation-tooltip')"><span class="tooltiptext" id="summarisation-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>While this chapter will focus on ion-level data modelling, modelling
of protein-level data is possible upon summarisation. Below, we
illustrate the challenges of <a href="sec-basics.html#sec-summarisation">summarising</a> TMT
data using one of the UPS proteins in Mixture 1 (separating the data
for each technical replicate). We also focus on the 0.125x and the 1x
spike-in conditions. We illustrate the different peptide ions on the x
axis and plot the log2 normalised intensities across samples on y
axis. All the points belonging to the same sample are linked through a
grey line.</p>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-210-1.png" width="576"></p>
<p>We see that the same challenges observed for <a href="sec-basics.html#sec-summarisation">LFQ
data</a> also apply to TMT data. Briefly:</p>
<ol style="list-style-type: decimal">
<li>Data for a protein can consist of many peptide ions.</li>
<li>Peptide ions have different intensity baselines.</li>
<li>There is strong missingness across runs (compare points between
replicates), but the missingness is mitigated within runs (compare
points within replicates<label for="tufte-sn-21" class="margin-toggle sidenote-number">21</label><input type="checkbox" id="tufte-sn-21" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">21</span> Note that the data points from one
peptide ion in one replicate has been extracted from a single MS2
spectrum.</span>).</li>
<li>Subtle intensity shifts for the same peptide across different
replicates, called spectrum effects, are caused by small run-to-run
fluctuations.</li>
<li>Presence of outliers. For instance, the first peptide ion
doesn’t show the same change in intensity between conditions
compared to majority of the peptides.</li>
</ol>
<p><strong>TODO</strong>: use robust summary instead of median polish for consistency
with previous vignette?</p>
<p>Here, we summarise the ion-level data into protein intensities
through the median polish approach, which alternately removes the
peptide-ions and the sample medians from the data until the summaries
stabilise. Removing the peptide-ion medians will solve issue 2. as it
removes the ion-specific effects. Using the median instead of
the mean will solve issue 5. Note that we perform summarisation for
each run separately, hence the ion effect will be different for
each run, effectively allowing for a spectrum effect and solving
issue 4.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="sec-advanced.html#cb124-1" tabindex="-1"></a>summNames <span class="ot">&lt;-</span> <span class="fu">paste0</span>(inputNames, <span class="st">"_proteins"</span>)</span>
<span id="cb124-2"><a href="sec-advanced.html#cb124-2" tabindex="-1"></a>(spikein <span class="ot">&lt;-</span> <span class="fu">aggregateFeatures</span>(</span>
<span id="cb124-3"><a href="sec-advanced.html#cb124-3" tabindex="-1"></a>    spikein, <span class="at">i =</span> normNames,  <span class="at">name =</span> summNames,</span>
<span id="cb124-4"><a href="sec-advanced.html#cb124-4" tabindex="-1"></a>    <span class="at">fcol =</span> <span class="st">"Protein.Accessions"</span>, <span class="at">fun =</span> MsCoreUtils<span class="sc">::</span>medianPolish,</span>
<span id="cb124-5"><a href="sec-advanced.html#cb124-5" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb124-6"><a href="sec-advanced.html#cb124-6" tabindex="-1"></a>))</span></code></pre></div>
<pre><code>## An instance of class QFeatures (type: bulk) with 61 sets:
## 
##  [1] Mixture1_01: SummarizedExperiment with 1719 rows and 8 columns 
##  [2] Mixture1_02: SummarizedExperiment with 1722 rows and 8 columns 
##  [3] Mixture1_03: SummarizedExperiment with 1776 rows and 8 columns 
##  ...
##  [59] Mixture5_01_proteins: SummarizedExperiment with 307 rows and 8 columns 
##  [60] Mixture5_02_proteins: SummarizedExperiment with 296 rows and 8 columns 
##  [61] Mixture5_03_proteins: SummarizedExperiment with 299 rows and 8 columns</code></pre>
<p>We can now join the different protein sets into a single set. We omit
the <code>fcol</code> argument, meaning that the set rows will be matched based
on the row names (generated by <code>aggregateFeatures()</code>).</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="sec-advanced.html#cb126-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">joinAssays</span>( </span>
<span id="cb126-2"><a href="sec-advanced.html#cb126-2" tabindex="-1"></a>    spikein, summNames, <span class="st">"proteins"</span></span>
<span id="cb126-3"><a href="sec-advanced.html#cb126-3" tabindex="-1"></a>)</span></code></pre></div>
</div>
</div>
<div id="data-exploration" class="section level2" number="3.5">
<h2>
<span class="header-section-number">3.5</span> Data exploration<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('data-exploration')" onmouseout="reset_tooltip('data-exploration-tooltip')"><span class="tooltiptext" id="data-exploration-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>We perform data exploration using MDS, using the same pipeline as
in <a href="sec-basics.html#sec_data_exploration">the previous chapter</a>.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="sec-advanced.html#cb127-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"scater"</span>)</span>
<span id="cb127-2"><a href="sec-advanced.html#cb127-2" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">getWithColData</span>(spikein, <span class="st">"ions"</span>)</span>
<span id="cb127-3"><a href="sec-advanced.html#cb127-3" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">runMDS</span>(<span class="fu">as</span>(se, <span class="st">"SingleCellExperiment"</span>), <span class="at">exprs_values =</span> <span class="dv">1</span>)</span>
<span id="cb127-4"><a href="sec-advanced.html#cb127-4" tabindex="-1"></a><span class="fu">plotMDS</span>(se, <span class="at">colour_by =</span> <span class="st">"Condition"</span>) <span class="sc">+</span></span>
<span id="cb127-5"><a href="sec-advanced.html#cb127-5" tabindex="-1"></a>  <span class="fu">plotMDS</span>(se, <span class="at">colour_by =</span> <span class="st">"Run"</span>) <span class="sc">+</span> </span>
<span id="cb127-6"><a href="sec-advanced.html#cb127-6" tabindex="-1"></a>  <span class="fu">plotMDS</span>(se, <span class="at">colour_by =</span> <span class="st">"Mixture"</span>)</span></code></pre></div>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-213-1.png" width="672"></p>
<p>There is a strong run-to-run effect, which is partly explained by a
mixture effect as the runs from the same mixture tend to be closer
than runs from different mixtures. The condition effect is much more
subtle to find, probably because we know only a few UPS proteins were
spiked in while the majority of the background proteins are unchanged.</p>
<p>As discussed above, the median polish summarisation should remove part
of the run to run effect. We repeat the data exploration, but using
the protein-level data.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="sec-advanced.html#cb128-1" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">getWithColData</span>(spikein, <span class="st">"proteins"</span>)</span>
<span id="cb128-2"><a href="sec-advanced.html#cb128-2" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">runMDS</span>(<span class="fu">as</span>(se, <span class="st">"SingleCellExperiment"</span>), <span class="at">exprs_values =</span> <span class="dv">1</span>)</span>
<span id="cb128-3"><a href="sec-advanced.html#cb128-3" tabindex="-1"></a><span class="fu">plotMDS</span>(se, <span class="at">colour_by =</span> <span class="st">"Condition"</span>) <span class="sc">+</span></span>
<span id="cb128-4"><a href="sec-advanced.html#cb128-4" tabindex="-1"></a>  <span class="fu">plotMDS</span>(se, <span class="at">colour_by =</span> <span class="st">"Run"</span>) <span class="sc">+</span> </span>
<span id="cb128-5"><a href="sec-advanced.html#cb128-5" tabindex="-1"></a>  <span class="fu">plotMDS</span>(se, <span class="at">colour_by =</span> <span class="st">"Mixture"</span>)</span></code></pre></div>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-214-1.png" width="672"></p>
<p>While the run effects are smaller (i.e. points within a run are more
scattered than on the previous plots) on the protein-level MDS
compared to the ion-level MDS (the samples are less clustered per
run), we can see that normalisation and summarisation alone are not
sufficient to correct for these unwanted effects. We will take care of
these effects during the data modelling.</p>
</div>
<div id="sec-run_model" class="section level2" number="3.6">
<h2>
<span class="header-section-number">3.6</span> Data modelling<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sec-run_model')" onmouseout="reset_tooltip('sec-run_model-tooltip')"><span class="tooltiptext" id="sec-run_model-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>Proteomics data contain several sources of variation that need to be
accounted for by the model. Before delving into these sources of
variation, we here show how to run the model that accounts for all
relevant sources of variation in the spike-in experiment, which we
have shown performs best <span class="citation">(<label for="tufte-mn-14" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-14" class="margin-toggle">Vandenbulcke et al. 2025<span class="marginnote">Vandenbulcke, Stijn, Christophe Vanderaa, Oliver Crook, Lennart Martens, and Lieven Clement. 2025. <span>“<span>Msqrob2TMT</span>: Robust Linear Mixed Models for Inferring Differential Abundant Proteins in Labeled Experiments with Arbitrarily Complex Design.”</span> <em>Mol. Cell. Proteomics</em> 24 (7): 101002.</span>)</span>.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="sec-advanced.html#cb129-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">msqrobAggregate</span>(</span>
<span id="cb129-2"><a href="sec-advanced.html#cb129-2" tabindex="-1"></a>    spikein,  <span class="at">i =</span> <span class="st">"ions"</span>,</span>
<span id="cb129-3"><a href="sec-advanced.html#cb129-3" tabindex="-1"></a>    <span class="at">formula =</span> <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> Condition <span class="sc">+</span> <span class="do">## fixed effect for experimental condition</span></span>
<span id="cb129-4"><a href="sec-advanced.html#cb129-4" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Label) <span class="sc">+</span> <span class="do">## random effect for label</span></span>
<span id="cb129-5"><a href="sec-advanced.html#cb129-5" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Mixture) <span class="sc">+</span> <span class="do">## random effect for mixture</span></span>
<span id="cb129-6"><a href="sec-advanced.html#cb129-6" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run) <span class="sc">+</span> <span class="do">## random effect for run</span></span>
<span id="cb129-7"><a href="sec-advanced.html#cb129-7" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run<span class="sc">:</span>Label) <span class="sc">+</span> <span class="do">## random effect for PSMs for the same protein in a label of a run</span></span>
<span id="cb129-8"><a href="sec-advanced.html#cb129-8" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run<span class="sc">:</span>ionID), <span class="do">## random effect for ions in the same spectrum of an MS run</span></span>
<span id="cb129-9"><a href="sec-advanced.html#cb129-9" tabindex="-1"></a>    <span class="at">fcol =</span> <span class="st">"Protein.Accessions"</span>,</span>
<span id="cb129-10"><a href="sec-advanced.html#cb129-10" tabindex="-1"></a>    <span class="at">modelColumnName =</span> <span class="st">"msqrob_psms_rrilm"</span>,</span>
<span id="cb129-11"><a href="sec-advanced.html#cb129-11" tabindex="-1"></a>    <span class="at">robust =</span> <span class="cn">TRUE</span>, <span class="at">ridge =</span> <span class="cn">TRUE</span></span>
<span id="cb129-12"><a href="sec-advanced.html#cb129-12" tabindex="-1"></a>)</span></code></pre></div>
<p><strong>TODO</strong>: I canot remember why we suppress the intercept…</p>
<p>We will now build the model by progressively adding the different
sources of variation.</p>
<div id="sec-fixed_effect" class="section level3" number="3.6.1">
<h3>
<span class="header-section-number">3.6.1</span> Effect of treatment of interest<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sec-fixed_effect')" onmouseout="reset_tooltip('sec-fixed_effect-tooltip')"><span class="tooltiptext" id="sec-fixed_effect-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>We model the source of variation induced by the experimental
treatment of interest as a <strong>fixed effect</strong>, which we consider
non-random, i.e. the treatment effect is assumed to be the same in
repeated experiments, but it is unknown and has to be estimated. When
modelling a typical label-free experiment at the protein level, the
model boils down to a linear model, again we suppress the index for
protein:</p>
<p><span class="math display">\[
y_r = \mathbf{x}^T_r \boldsymbol{\beta} + \epsilon_r,
\]</span></p>
<p>with <span class="math inline">\(y_r\)</span> the <span class="math inline">\(\log_2\)</span>-normalized protein intensities in run r;
<span class="math inline">\(\mathbf{x}_r\)</span> a vector with the covariate pattern for the sample in
run <span class="math inline">\(r\)</span> encoding the intercept, treatment, potential batch effects and
confounders; <span class="math inline">\(\boldsymbol{\beta}\)</span> the vector of parameters that model
the association between the covariates and the outcome; and
<span class="math inline">\(\epsilon_r\)</span> the residuals reflecting variation that is not captured
by the fixed effects. Note that <span class="math inline">\(\mathbf{x}_r\)</span> allows for a flexible
parameterization of the treatment beyond a single covariate, i.e.
including a 1 for the intercept, continuous and categorical variables
as well as their interactions. For all models considered in this work,
we assume the residuals to be independent and identically distributed
(i.i.d) according to a normal distribution with zero mean and constant
variance, i.e. <span class="math inline">\(\epsilon_{r} \sim N(0,\sigma_\epsilon^2)\)</span>, that can
differ from protein to protein.</p>
<p>Now we defined a model, we must estimate from the data. Using
<code>msqrob()</code> (described in the <a href="sec-basics.html#sec-msqrob">previous chapter</a>), the
model translates into the following code:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="sec-advanced.html#cb130-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">msqrob</span>(</span>
<span id="cb130-2"><a href="sec-advanced.html#cb130-2" tabindex="-1"></a>    spikein,  <span class="at">i =</span> <span class="st">"proteins"</span>,</span>
<span id="cb130-3"><a href="sec-advanced.html#cb130-3" tabindex="-1"></a>    <span class="at">formula =</span> <span class="sc">~</span>  <span class="dv">0</span> <span class="sc">+</span> Condition, <span class="do">## fixed effect for experimental condition</span></span>
<span id="cb130-4"><a href="sec-advanced.html#cb130-4" tabindex="-1"></a>    <span class="at">robust =</span> <span class="cn">TRUE</span>, <span class="at">ridge =</span> <span class="cn">TRUE</span></span>
<span id="cb130-5"><a href="sec-advanced.html#cb130-5" tabindex="-1"></a>)</span></code></pre></div>
<p><strong>TODO</strong>: do we need to suppress the intercept? We documented this for
the msqrob2TMT vignette but my feeling is that we should learn users
to perform to build contrasts with intercepts. However, regarding
ridge regression, suppressing the intercept is better and we found
that ridge regression performs better.</p>
<p>This model is however incomplete and relying on its results would lead
to incorrect conclusions as we are still missing important source of
variation. We did therefore not run the modelling command and will
expand the model.</p>
</div>
<div id="effect-of-tmt-label-and-run" class="section level3" number="3.6.2">
<h3>
<span class="header-section-number">3.6.2</span> Effect of TMT label and run<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('effect-of-tmt-label-and-run')" onmouseout="reset_tooltip('effect-of-tmt-label-and-run-tooltip')"><span class="tooltiptext" id="effect-of-tmt-label-and-run-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>As label-free experiments contain only a single sample per run,
run-specific effects will be absorbed in the residuals. However, the
data analysis of labeled experiments, e.g. using TMT multiplexing,
involving multiple MS runs has to account for run- and label-specific
effects, explicitly. If all treatments are present in each run, and if
TMT label swaps are performed so as to avoid confounding between label
and treatment, then the model parameters can be estimated using fixed
label and run effects. Indeed, for these designs run acts as a
blocking variable as all treatment effects can be estimated within
each run.</p>
<p>However, for more complex designs this is no longer possible and the
uncertainty in the estimation of the mean model parameters can involve
both within and between TMT label and run variability. For these
designs we can resort to mixed models where the label and run effect
are modelled using <strong>random effects</strong>, i.e. they are considered as a
random sample from the population of all possible runs and TMT labels,
which are assumed to be i.i.d normally distributed with mean 0 and
constant variance, <span class="math inline">\(u_r \sim N(0,\sigma^{2,\text{run}})\)</span> (<span class="math inline">\(u_{label}
\sim N(0,\sigma^{2,\text{label}})\)</span>). The use of random effects thus
models the correlation in the data, explicitly. Indeed, protein
intensities that are measured within the same run/label will be more
similar than protein intensities between runs/labels.</p>
<p>Hence, the model is extended to:</p>
<p><span class="math display">\[
y_{rl} =
\mathbf{x}^T_{rl} \boldsymbol{\beta} + u_l^\text{label} + u_r^\text{run} +
\epsilon_{rl}
\]</span>
with <span class="math inline">\(y_{rl}\)</span> the normalised <span class="math inline">\(\log_2\)</span> protein intensities in run <span class="math inline">\(r\)</span>
and label <span class="math inline">\(l\)</span>, <span class="math inline">\(u_l^\text{label}\)</span> the effect introduced by
the label <span class="math inline">\(l\)</span>, and <span class="math inline">\(u_r^\text{run}\)</span> the effect for MS run
<span class="math inline">\(r\)</span>.</p>
<p>This translates in the following code:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="sec-advanced.html#cb131-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">msqrob</span>(</span>
<span id="cb131-2"><a href="sec-advanced.html#cb131-2" tabindex="-1"></a>    spikein,  <span class="at">i =</span> <span class="st">"proteins"</span>,</span>
<span id="cb131-3"><a href="sec-advanced.html#cb131-3" tabindex="-1"></a>    <span class="at">formula =</span> <span class="sc">~</span>  <span class="dv">0</span> <span class="sc">+</span> Condition <span class="sc">+</span> <span class="do">## fixed effect for experimental condition</span></span>
<span id="cb131-4"><a href="sec-advanced.html#cb131-4" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Label) <span class="sc">+</span> <span class="do">## random effect for label</span></span>
<span id="cb131-5"><a href="sec-advanced.html#cb131-5" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run), <span class="do">## random effect for MS run</span></span>
<span id="cb131-6"><a href="sec-advanced.html#cb131-6" tabindex="-1"></a>    <span class="at">robust =</span> <span class="cn">TRUE</span>, <span class="at">ridge =</span> <span class="cn">TRUE</span></span>
<span id="cb131-7"><a href="sec-advanced.html#cb131-7" tabindex="-1"></a>    )</span></code></pre></div>
<p>This model is still incomplete and is no executed as we still need to
account that each mixture has been replicated three times.</p>
</div>
<div id="sec-tmt_protein_model" class="section level3" number="3.6.3">
<h3>
<span class="header-section-number">3.6.3</span> Effect of replication<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sec-tmt_protein_model')" onmouseout="reset_tooltip('sec-tmt_protein_model-tooltip')"><span class="tooltiptext" id="sec-tmt_protein_model-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>Some experiments also include technical replication where a TMT
mixture can be acquired multiple times. This again will induce
correlation. Indeed, protein intensities from the same mixture will be
more alike than those of different mixtures. Hence, we also include a
random effect to account for this pseudo-replication, i.e.
<span class="math inline">\(u^\text{mix}_m \sim N(0, \sigma^{2,\text{mix}})\)</span>. The model thus
extends to:</p>
<p><span class="math display">\[
y_{rlm} =
\mathbf{x}^T_{rlm} \boldsymbol{\beta} +  u_{l}^\text{label} +
u_r^\text{run} + u_m^\text{mix} + \epsilon_{rlm}
\]</span></p>
<p>with <span class="math inline">\(m\)</span> the index for mixture.</p>
<p>The model translates to the following code:</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="sec-advanced.html#cb132-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">msqrob</span>(</span>
<span id="cb132-2"><a href="sec-advanced.html#cb132-2" tabindex="-1"></a>    spikein,  <span class="at">i =</span> <span class="st">"proteins"</span>,</span>
<span id="cb132-3"><a href="sec-advanced.html#cb132-3" tabindex="-1"></a>    <span class="at">formula =</span> <span class="sc">~</span>  <span class="dv">0</span> <span class="sc">+</span> Condition <span class="sc">+</span> <span class="do">## fixed effect for experimental condition</span></span>
<span id="cb132-4"><a href="sec-advanced.html#cb132-4" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Label) <span class="sc">+</span> <span class="do">## random effect for label</span></span>
<span id="cb132-5"><a href="sec-advanced.html#cb132-5" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run) <span class="sc">+</span> <span class="do">## random effect for MS run</span></span>
<span id="cb132-6"><a href="sec-advanced.html#cb132-6" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Mixture), <span class="do">## random effect for mixture</span></span>
<span id="cb132-7"><a href="sec-advanced.html#cb132-7" tabindex="-1"></a>    <span class="at">robust =</span> <span class="cn">TRUE</span>, <span class="at">ridge =</span> <span class="cn">TRUE</span>,</span>
<span id="cb132-8"><a href="sec-advanced.html#cb132-8" tabindex="-1"></a>    <span class="at">overwrite =</span> <span class="cn">TRUE</span></span>
<span id="cb132-9"><a href="sec-advanced.html#cb132-9" tabindex="-1"></a>)</span></code></pre></div>
<p>This model provides a sensible representation of the sources of
variation in the data if we were to model the data at the protein
level. This time, we executed the code and will use the result in a
later section. However, we found that modelling protein-level effects
from ion-level data leads to improved performance. This will require
an additional model expansion.</p>
</div>
<div id="sec-tmt_ion_model" class="section level3" number="3.6.4">
<h3>
<span class="header-section-number">3.6.4</span> Ion-level modelling<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sec-tmt_ion_model')" onmouseout="reset_tooltip('sec-tmt_ion_model-tooltip')"><span class="tooltiptext" id="sec-tmt_ion_model-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>Estimating the treatment effect from ion-level data will again induce
additional levels of correlation. Indeed, the intensities for the
different reporter ions in a TMT run within the same spectrum (PSM)
will be more similar than the intensities between PSMs. We therefore
need to add a random effect term to account for the within PSM
correlation structure, i.e. <span class="math inline">\(u^\text{PSM}_{rp} \sim
N(0,\sigma^{2,\text{PSM}})\)</span>. Moreover, in each label of a run multiple
PSM intensities are picked up for each protein. Hence, intensities
from different PSMs for a protein in the same label of a run will be
more alike than intensities of different PSMs for the same protein
between labels of runs, and we will address this correlation with a
label-specific random effect nested in run, i.e. <span class="math inline">\(u_{rl}^{label} \sim
N(0,\sigma^{2,\text{label}})\)</span>. The model then becomes:</p>
<p><span class="math display">\[
y_{rlmp} =
\mathbf{x}^T_{rlmp} \beta + u_{l}^\text{label} +
u_r^\text{run} + u_m^\text{mix}  +
u_{rl}^\text{label} + u_{rp}^\text{PSM} + \epsilon_{rlmp}
\]</span>
with <span class="math inline">\(y_{rlmp}\)</span> the <span class="math inline">\(\log_2\)</span>-normalized PSM intensities for run <span class="math inline">\(r\)</span>
with label <span class="math inline">\(l\)</span> in mixture <span class="math inline">\(m\)</span> and peptide ion <span class="math inline">\(p\)</span>. Note, that the
peptide ion random effect is also nested within each run since each
spectrum is described by run-specific characteristics.</p>
<p><code>msqrobAggregate()</code>enables the fitting of an ion-level model to obtain
protein-level estimates. The function behaves similarly to <code>msqrob()</code>
and shares most of the arguments. The notable difference is the <code>fcol</code>
argument that tells the function how to group the ion-level data into
protein-level data. Here, we will group ions by the
<code>Protein.Accessions</code>. The results will be stored in a new
protein-level set, which we call <code>proteins_msqrob</code>.
<code>msqrobAggregate()</code> will fetch annotations from the <code>colData</code> (i.e.
<code>"Condition"</code>, <code>"Label"</code>, <code>"Run"</code>, <code>"Mixture"</code>), but contrarily to
<code>msqrob()</code>, it can also fetch anntations from the <code>rowData</code> (i.e.
<code>"ionID"</code>).</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="sec-advanced.html#cb133-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">msqrobAggregate</span>(</span>
<span id="cb133-2"><a href="sec-advanced.html#cb133-2" tabindex="-1"></a>    spikein,  <span class="at">i =</span> <span class="st">"ions"</span>,</span>
<span id="cb133-3"><a href="sec-advanced.html#cb133-3" tabindex="-1"></a>    <span class="at">formula =</span> <span class="sc">~</span>  <span class="dv">0</span> <span class="sc">+</span> Condition <span class="sc">+</span> <span class="do">## fixed effect for experimental condition</span></span>
<span id="cb133-4"><a href="sec-advanced.html#cb133-4" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Label) <span class="sc">+</span> <span class="do">## random effect for label</span></span>
<span id="cb133-5"><a href="sec-advanced.html#cb133-5" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run) <span class="sc">+</span> <span class="do">## random effect for Run</span></span>
<span id="cb133-6"><a href="sec-advanced.html#cb133-6" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Mixture) <span class="sc">+</span> <span class="do">## random effect for mixture</span></span>
<span id="cb133-7"><a href="sec-advanced.html#cb133-7" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run<span class="sc">:</span>Label) <span class="sc">+</span> <span class="do">## random effect for label nested in run</span></span>
<span id="cb133-8"><a href="sec-advanced.html#cb133-8" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run<span class="sc">:</span>ionID), <span class="do">## random effect for ion nested in run</span></span>
<span id="cb133-9"><a href="sec-advanced.html#cb133-9" tabindex="-1"></a>    <span class="at">fcol =</span> <span class="st">"Protein.Accessions"</span>,</span>
<span id="cb133-10"><a href="sec-advanced.html#cb133-10" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"proteins_msqrob"</span>,</span>
<span id="cb133-11"><a href="sec-advanced.html#cb133-11" tabindex="-1"></a>    <span class="at">robust =</span> <span class="cn">TRUE</span>, <span class="at">ridge =</span> <span class="cn">TRUE</span></span>
<span id="cb133-12"><a href="sec-advanced.html#cb133-12" tabindex="-1"></a>)</span></code></pre></div>
<p>So, we built the model shown at the beginning of this section,
effectively accounting for all sources of variation in TMT-based
proteomics data.</p>
</div>
<div id="why-robust-regression" class="section level3" number="3.6.5">
<h3>
<span class="header-section-number">3.6.5</span> Why robust regression?<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('why-robust-regression')" onmouseout="reset_tooltip('why-robust-regression-tooltip')"><span class="tooltiptext" id="why-robust-regression-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>Throughout this book, we estimate the model parameters using robust
regression through M-estimation (<code>robust = TRUE</code>). This class of
estimation does not need the assumption that the residuals <span class="math inline">\(\epsilon\)</span>
are normally distributed. However, if the residuals are normal, the
M-estimators have a high efficiency.</p>
<p>In ordinary least squares (OLS), the loss function that is minimised
is:</p>
<p><span class="math display">\[
\sum\limits_{i = 1}^n \left(y_i - \mathbf{x}_i^T \boldsymbol{\beta}\right)^2
\]</span></p>
<p>While the M-estimation minimise the following loss function:</p>
<p><span class="math display">\[
\sum\limits_{i = 1}^n \rho \left(y_i - \mathbf{x}_i^T \boldsymbol{\beta}\right)
\]</span></p>
<p>No normality assumption needed</p>
<p>Robust fit minimises the maximal bias of the estimators</p>
<p>CI and statistical tests are based on asymptotic theory</p>
<p>If <span class="math inline">\(\epsilon\)</span> is normal, the M-estimators have a high efficiency!</p>
<p>ordinary least squares (OLS): minimize loss function</p>
</div>
<div id="why-ridge-regression" class="section level3" number="3.6.6">
<h3>
<span class="header-section-number">3.6.6</span> Why ridge regression?<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('why-ridge-regression')" onmouseout="reset_tooltip('why-ridge-regression-tooltip')"><span class="tooltiptext" id="why-ridge-regression-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>We also enable ridge regression (<code>ridge = TRUE</code>) which stabilises the
parameter estimation of fixed effects.</p>
<p><strong>TODO</strong>: take subset A bs B and demonstrate that rideg is not
possible. Also faster without ridge.</p>
</div>
</div>
<div id="statistical-inference" class="section level2" number="3.7">
<h2>
<span class="header-section-number">3.7</span> Statistical inference<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('statistical-inference')" onmouseout="reset_tooltip('statistical-inference-tooltip')"><span class="tooltiptext" id="statistical-inference-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>We can now convert the biological question “does the spike-in
condition affect the protein intensities?” into a statistical
hypothesis. In other words, we need to define the <a href="sec-basics.html#sec-inference">contrast</a>.
We plot an overview of the model parameters.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="sec-advanced.html#cb134-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ExploreModelMatrix"</span>)</span>
<span id="cb134-2"><a href="sec-advanced.html#cb134-2" tabindex="-1"></a>vd <span class="ot">&lt;-</span> <span class="fu">VisualizeDesign</span>(</span>
<span id="cb134-3"><a href="sec-advanced.html#cb134-3" tabindex="-1"></a>    <span class="at">sampleData =</span>  <span class="fu">colData</span>(spikein),</span>
<span id="cb134-4"><a href="sec-advanced.html#cb134-4" tabindex="-1"></a>    <span class="at">designFormula =</span> <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> Condition,</span>
<span id="cb134-5"><a href="sec-advanced.html#cb134-5" tabindex="-1"></a>    <span class="at">textSizeFitted =</span> <span class="dv">4</span></span>
<span id="cb134-6"><a href="sec-advanced.html#cb134-6" tabindex="-1"></a>)</span>
<span id="cb134-7"><a href="sec-advanced.html#cb134-7" tabindex="-1"></a>vd<span class="sc">$</span>plotlist</span></code></pre></div>
<pre><code>## [[1]]</code></pre>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-216-1.png" width="672"></p>
<p>Note that with ExploreModelMatrix we can only visualise fixed effects
part of the model. This is fine as the mean protein abundances can
only systematically differ from each other according to the
<code>Condition</code> (fixed effect).</p>
<div id="hypothesis-testing-1" class="section level3" number="3.7.1">
<h3>
<span class="header-section-number">3.7.1</span> Hypothesis testing<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('hypothesis-testing-1')" onmouseout="reset_tooltip('hypothesis-testing-1-tooltip')"><span class="tooltiptext" id="hypothesis-testing-1-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>The average difference intensity between the 1x and the 0.5x
conditions is provided by the contrast <code>ridgeCondition1 - ridgeCondition0.5</code>. This is, however, not the only difference we could
assess. As described in the <a href="sec-basics.html#sec-multiple_contrasts">previous
chapter</a>, we will generate a contrast matrix
that assess all possible pairwise comparisons between spike-in
conditions.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="sec-advanced.html#cb136-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"utils.R"</span>)</span>
<span id="cb136-2"><a href="sec-advanced.html#cb136-2" tabindex="-1"></a>allHypotheses <span class="ot">&lt;-</span> <span class="fu">createPairwiseContrasts</span>(</span>
<span id="cb136-3"><a href="sec-advanced.html#cb136-3" tabindex="-1"></a>  <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> Condition <span class="sc">+</span> <span class="do">## fixed effect for experimental condition</span></span>
<span id="cb136-4"><a href="sec-advanced.html#cb136-4" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Label) <span class="sc">+</span> <span class="do">## random effect for label</span></span>
<span id="cb136-5"><a href="sec-advanced.html#cb136-5" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run) <span class="sc">+</span> <span class="do">## random effect for Run</span></span>
<span id="cb136-6"><a href="sec-advanced.html#cb136-6" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Mixture) <span class="sc">+</span> <span class="do">## random effect for mixture</span></span>
<span id="cb136-7"><a href="sec-advanced.html#cb136-7" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run<span class="sc">:</span>Label) <span class="sc">+</span> <span class="do">## random effect for label nested in run</span></span>
<span id="cb136-8"><a href="sec-advanced.html#cb136-8" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run<span class="sc">:</span>ionID), </span>
<span id="cb136-9"><a href="sec-advanced.html#cb136-9" tabindex="-1"></a>  <span class="fu">colData</span>(spikein), <span class="st">"Condition"</span>, <span class="at">ridge =</span> <span class="cn">TRUE</span></span>
<span id="cb136-10"><a href="sec-advanced.html#cb136-10" tabindex="-1"></a>)</span>
<span id="cb136-11"><a href="sec-advanced.html#cb136-11" tabindex="-1"></a>L <span class="ot">&lt;-</span> <span class="fu">makeContrast</span>(</span>
<span id="cb136-12"><a href="sec-advanced.html#cb136-12" tabindex="-1"></a>  allHypotheses,</span>
<span id="cb136-13"><a href="sec-advanced.html#cb136-13" tabindex="-1"></a>  <span class="at">parameterNames =</span> <span class="fu">paste0</span>(<span class="st">"ridgeCondition"</span>, <span class="fu">c</span>(<span class="st">"0.125"</span>, <span class="st">"0.5"</span>, <span class="st">"0.667"</span>, <span class="st">"1"</span>))</span>
<span id="cb136-14"><a href="sec-advanced.html#cb136-14" tabindex="-1"></a>)</span></code></pre></div>
<p>We test our null hypotheses using <code>hypothesisTest()</code> and the estimated
ion-level model stored in <code>proteins_msqrob</code>.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="sec-advanced.html#cb137-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">hypothesisTest</span>(spikein, <span class="at">i =</span> <span class="st">"proteins_msqrob"</span>, <span class="at">contrast =</span> L)</span>
<span id="cb137-2"><a href="sec-advanced.html#cb137-2" tabindex="-1"></a>inferences <span class="ot">&lt;-</span> <span class="fu">rowData</span>(spikein[[<span class="st">"proteins_msqrob"</span>]])[, <span class="fu">colnames</span>(L)]</span></code></pre></div>
<p>We can retrieve the results for the comparison between the 1x and the
0.5x conditions.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="sec-advanced.html#cb138-1" tabindex="-1"></a><span class="fu">head</span>(inferences<span class="sc">$</span><span class="st">"ridgeCondition1 - ridgeCondition0.5"</span>)</span></code></pre></div>
<pre><code>##              logFC           se         df          t        pval    adjPval
## O00151 -0.02552643 2.155344e-02  471.97028 -1.1843321 0.236877704 0.58843430
## O00220  0.01440435 5.774991e-02   94.45529  0.2494264 0.803572571 1.00000000
## O00244  0.00000000 3.772062e-11   84.15880  0.0000000 1.000000000 1.00000000
## O00299 -0.03154412 1.172646e-02 1380.19287 -2.6899957 0.007231448 0.03772405
## O00330 -0.02880903 3.682447e-02  193.93011 -0.7823338 0.434972628 0.87273354
## O00399          NA           NA         NA         NA          NA         NA</code></pre>
<p>The last row is filled with missing values because data modelling
resulted in a <code>fitError</code> (we will explore in a <a href="sec-advanced.html#sec-fiterror">later
section</a> how we can deal with proteins that could not
be fit).</p>
</div>
<div id="volcano-plots-1" class="section level3" number="3.7.2">
<h3>
<span class="header-section-number">3.7.2</span> Volcano plots<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('volcano-plots-1')" onmouseout="reset_tooltip('volcano-plots-1-tooltip')"><span class="tooltiptext" id="volcano-plots-1-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>We generate volcano plots for all pairwise comparison between
conditions. First, we add new columns to the tables and join them in a
single table.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="sec-advanced.html#cb140-1" tabindex="-1"></a>inferences <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">colnames</span>(inferences), <span class="cf">function</span>(i) {</span>
<span id="cb140-2"><a href="sec-advanced.html#cb140-2" tabindex="-1"></a>  inference <span class="ot">&lt;-</span> inferences[[i]]</span>
<span id="cb140-3"><a href="sec-advanced.html#cb140-3" tabindex="-1"></a>  inference<span class="sc">$</span>Protein <span class="ot">&lt;-</span> <span class="fu">rownames</span>(inference)</span>
<span id="cb140-4"><a href="sec-advanced.html#cb140-4" tabindex="-1"></a>  inference<span class="sc">$</span>isUps <span class="ot">&lt;-</span> <span class="fu">grepl</span>(<span class="st">"ups"</span>, inference<span class="sc">$</span>Protein)</span>
<span id="cb140-5"><a href="sec-advanced.html#cb140-5" tabindex="-1"></a>  inference<span class="sc">$</span>Comparison <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"ridgeCondition"</span>, <span class="st">""</span>, i)</span>
<span id="cb140-6"><a href="sec-advanced.html#cb140-6" tabindex="-1"></a>  inference</span>
<span id="cb140-7"><a href="sec-advanced.html#cb140-7" tabindex="-1"></a>})</span>
<span id="cb140-8"><a href="sec-advanced.html#cb140-8" tabindex="-1"></a>inferences <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, inferences) <span class="do">## combine in a single table</span></span></code></pre></div>
<p>Then, we plot the volcano plots with each comparison in a separate facet.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="sec-advanced.html#cb141-1" tabindex="-1"></a><span class="fu">ggplot</span>(inferences) <span class="sc">+</span></span>
<span id="cb141-2"><a href="sec-advanced.html#cb141-2" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> logFC,</span>
<span id="cb141-3"><a href="sec-advanced.html#cb141-3" tabindex="-1"></a>        <span class="at">y =</span> <span class="sc">-</span><span class="fu">log10</span>(pval),</span>
<span id="cb141-4"><a href="sec-advanced.html#cb141-4" tabindex="-1"></a>        <span class="at">color =</span> isUps) <span class="sc">+</span></span>
<span id="cb141-5"><a href="sec-advanced.html#cb141-5" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb141-6"><a href="sec-advanced.html#cb141-6" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="sc">-</span><span class="fu">log10</span>(<span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb141-7"><a href="sec-advanced.html#cb141-7" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(</span>
<span id="cb141-8"><a href="sec-advanced.html#cb141-8" tabindex="-1"></a>      <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"grey20"</span>, <span class="st">"firebrick"</span>), <span class="at">name =</span> <span class="st">""</span>,</span>
<span id="cb141-9"><a href="sec-advanced.html#cb141-9" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"HeLA background"</span>, <span class="st">"UPS standard"</span>)</span>
<span id="cb141-10"><a href="sec-advanced.html#cb141-10" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb141-11"><a href="sec-advanced.html#cb141-11" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> Comparison, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb141-12"><a href="sec-advanced.html#cb141-12" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Statistical inference for all pairwise comparisons"</span>) </span></code></pre></div>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-221-1.png" width="672"></p>
</div>
<div id="fold-change-distributions-1" class="section level3" number="3.7.3">
<h3>
<span class="header-section-number">3.7.3</span> Fold change distributions<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('fold-change-distributions-1')" onmouseout="reset_tooltip('fold-change-distributions-1-tooltip')"><span class="tooltiptext" id="fold-change-distributions-1-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>As this is a spike-in study with known ground truth, we can also plot
the log2 fold change distributions against the expected values, in
this case 0 for the HeLa proteins and 1 for the UPS standards.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="sec-advanced.html#cb142-1" tabindex="-1"></a><span class="fu">ggplot</span>(inferences) <span class="sc">+</span></span>
<span id="cb142-2"><a href="sec-advanced.html#cb142-2" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> logFC,</span>
<span id="cb142-3"><a href="sec-advanced.html#cb142-3" tabindex="-1"></a>        <span class="at">x =</span> isUps,</span>
<span id="cb142-4"><a href="sec-advanced.html#cb142-4" tabindex="-1"></a>        <span class="at">colour =</span> isUps) <span class="sc">+</span></span>
<span id="cb142-5"><a href="sec-advanced.html#cb142-5" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb142-6"><a href="sec-advanced.html#cb142-6" tabindex="-1"></a>    <span class="fu">geom_point</span>( <span class="do">## Adding the expected Log2 fold changes </span></span>
<span id="cb142-7"><a href="sec-advanced.html#cb142-7" tabindex="-1"></a>        <span class="at">data =</span> <span class="fu">group_by</span>(inferences, Comparison, isUps) <span class="sc">|&gt;</span> </span>
<span id="cb142-8"><a href="sec-advanced.html#cb142-8" tabindex="-1"></a>          <span class="fu">summarise</span>(<span class="at">logFC =</span> <span class="fu">ifelse</span>(isUps, <span class="fu">log2</span>(<span class="fu">eval</span>(<span class="fu">parse</span>(<span class="at">text =</span> <span class="fu">sub</span>(<span class="st">"-"</span>, <span class="st">"/"</span>, Comparison)))), <span class="dv">0</span>)),</span>
<span id="cb142-9"><a href="sec-advanced.html#cb142-9" tabindex="-1"></a>        <span class="at">shape =</span> <span class="dv">10</span>, <span class="at">size =</span> <span class="dv">4</span></span>
<span id="cb142-10"><a href="sec-advanced.html#cb142-10" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb142-11"><a href="sec-advanced.html#cb142-11" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(</span>
<span id="cb142-12"><a href="sec-advanced.html#cb142-12" tabindex="-1"></a>        <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"grey20"</span>, <span class="st">"firebrick"</span>), <span class="at">name =</span> <span class="st">""</span>,</span>
<span id="cb142-13"><a href="sec-advanced.html#cb142-13" tabindex="-1"></a>        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"HeLA background"</span>, <span class="st">"UPS standard"</span>)</span>
<span id="cb142-14"><a href="sec-advanced.html#cb142-14" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb142-15"><a href="sec-advanced.html#cb142-15" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> Comparison) <span class="sc">+</span></span>
<span id="cb142-16"><a href="sec-advanced.html#cb142-16" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Distribution of the log2 fold changes"</span>)</span></code></pre></div>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-222-1.png" width="672"></p>
<p>Estimated log2 fold change for HeLa proteins are closely distributed
around 0, as expected. log2 fold changes for UPS standard proteins are
distributed toward 1, although it is underestimated as reported
previously <span class="citation">(<label for="tufte-mn-15" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-15" class="margin-toggle">Savitski et al. 2011<span class="marginnote">Savitski, Mikhail M, Gavain Sweetman, Manor Askenazi, Jarrod A Marto, Manja Lang, Nico Zinn, and Marcus Bantscheff. 2011. <span>“Delayed Fragmentation and Optimized Isolation Width Settings for Improvement of Protein Identification and Accuracy of Isobaric Mass Tag Quantification on Orbitrap-Type Mass Spectrometers.”</span> <em>Anal. Chem.</em> 83 (23): 8959–67.</span>)</span>.</p>
</div>
<div id="detail-plots" class="section level3" number="3.7.4">
<h3>
<span class="header-section-number">3.7.4</span> Detail plots<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('detail-plots')" onmouseout="reset_tooltip('detail-plots-tooltip')"><span class="tooltiptext" id="detail-plots-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>We can explore the PSM intensities for a protein to validate the
statistical inference results. For example, let’s explore the
intensities for the protein with the most significant difference.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="sec-advanced.html#cb143-1" tabindex="-1"></a>(targetProtein <span class="ot">&lt;-</span> inferences<span class="sc">$</span>Protein[<span class="fu">which.min</span>(inferences<span class="sc">$</span>adjPval)])</span></code></pre></div>
<pre><code>## [1] "P02788ups"</code></pre>
<p>To obtain the required data, we perform a <a href="sec-basics.html#sec-detail_plot">data manipulation
pipeline</a>. We plot the log2 normalised intensities
for each sample. Since the protein is modelled at the peptide ion
level, multiple ion intensities are recorded in each sample. Each ion
is linked across samples using a grey line. Samples are colored
according to UPS spike-in condition. Finally, we split the plot in
facets, one for each mixture, to visualise the heterogeneity induced
by sample preparation.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="sec-advanced.html#cb145-1" tabindex="-1"></a>spikein[targetProtein, , <span class="st">"ions"</span>] <span class="sc">|&gt;</span></span>
<span id="cb145-2"><a href="sec-advanced.html#cb145-2" tabindex="-1"></a>    <span class="fu">longForm</span>(<span class="at">colvars =</span> <span class="fu">colnames</span>(<span class="fu">colData</span>(spikein)),</span>
<span id="cb145-3"><a href="sec-advanced.html#cb145-3" tabindex="-1"></a>             <span class="at">rowvars =</span> <span class="fu">c</span>(<span class="st">"Protein.Accessions"</span>, <span class="st">"ionID"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb145-4"><a href="sec-advanced.html#cb145-4" tabindex="-1"></a>    <span class="fu">data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb145-5"><a href="sec-advanced.html#cb145-5" tabindex="-1"></a>    <span class="do">## We reorder the sample identifiers to improve visualisation</span></span>
<span id="cb145-6"><a href="sec-advanced.html#cb145-6" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">colname =</span> <span class="fu">factor</span>(colname, <span class="at">levels =</span> <span class="fu">unique</span>(colname[<span class="fu">order</span>(Condition)]))) <span class="sc">|&gt;</span> </span>
<span id="cb145-7"><a href="sec-advanced.html#cb145-7" tabindex="-1"></a>    <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb145-8"><a href="sec-advanced.html#cb145-8" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> colname,</span>
<span id="cb145-9"><a href="sec-advanced.html#cb145-9" tabindex="-1"></a>        <span class="at">y =</span> value) <span class="sc">+</span></span>
<span id="cb145-10"><a href="sec-advanced.html#cb145-10" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> ionID), <span class="at">linewidth =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb145-11"><a href="sec-advanced.html#cb145-11" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> Condition)) <span class="sc">+</span></span>
<span id="cb145-12"><a href="sec-advanced.html#cb145-12" tabindex="-1"></a>    <span class="fu">facet_grid</span>(<span class="sc">~</span> Mixture, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb145-13"><a href="sec-advanced.html#cb145-13" tabindex="-1"></a>    <span class="fu">ggtitle</span>(targetProtein) <span class="sc">+</span></span>
<span id="cb145-14"><a href="sec-advanced.html#cb145-14" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb145-15"><a href="sec-advanced.html#cb145-15" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-224-1.png" width="960"></p>
</div>
</div>
<div id="protein-level-inference" class="section level2" number="3.8">
<h2>
<span class="header-section-number">3.8</span> Protein-level inference<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('protein-level-inference')" onmouseout="reset_tooltip('protein-level-inference-tooltip')"><span class="tooltiptext" id="protein-level-inference-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>We here show how to perform a two-step approach, where the data are
first summarised then modelled. We perform the same statistical
workflow as above, but starting from the protein level model estimated
in <a href="sec-advanced.html#sec-tmt_protein_model">this section</a><label for="tufte-sn-22" class="margin-toggle sidenote-number">22</label><input type="checkbox" id="tufte-sn-22" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">22</span> Note that the inference
pipeline is exactly the same whether the model was estimated with
<code>msqrob()</code> or <code>msqrobAggregate()</code>, and we don’t need to build a new
contrast matrix.</span>.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="sec-advanced.html#cb146-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">hypothesisTest</span>(spikein, <span class="at">i =</span> <span class="st">"proteins"</span>, <span class="at">contrast =</span> L)</span>
<span id="cb146-2"><a href="sec-advanced.html#cb146-2" tabindex="-1"></a>inferences <span class="ot">&lt;-</span> <span class="fu">rowData</span>(spikein[[<span class="st">"proteins"</span>]])[, <span class="fu">colnames</span>(L)]</span></code></pre></div>
<p>We build the volcano using the same code as above:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="sec-advanced.html#cb147-1" tabindex="-1"></a>inferences <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">colnames</span>(inferences), <span class="cf">function</span>(i) {</span>
<span id="cb147-2"><a href="sec-advanced.html#cb147-2" tabindex="-1"></a>  inference <span class="ot">&lt;-</span> inferences[[i]]</span>
<span id="cb147-3"><a href="sec-advanced.html#cb147-3" tabindex="-1"></a>  inference<span class="sc">$</span>Protein <span class="ot">&lt;-</span> <span class="fu">rownames</span>(inference)</span>
<span id="cb147-4"><a href="sec-advanced.html#cb147-4" tabindex="-1"></a>  inference<span class="sc">$</span>isUps <span class="ot">&lt;-</span> <span class="fu">grepl</span>(<span class="st">"ups"</span>, inference<span class="sc">$</span>Protein)</span>
<span id="cb147-5"><a href="sec-advanced.html#cb147-5" tabindex="-1"></a>  inference<span class="sc">$</span>Comparison <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"ridgeCondition"</span>, <span class="st">""</span>, i)</span>
<span id="cb147-6"><a href="sec-advanced.html#cb147-6" tabindex="-1"></a>  inference</span>
<span id="cb147-7"><a href="sec-advanced.html#cb147-7" tabindex="-1"></a>})</span>
<span id="cb147-8"><a href="sec-advanced.html#cb147-8" tabindex="-1"></a>inferences <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, inferences) <span class="do">## combine in a single table</span></span>
<span id="cb147-9"><a href="sec-advanced.html#cb147-9" tabindex="-1"></a><span class="fu">ggplot</span>(inferences) <span class="sc">+</span></span>
<span id="cb147-10"><a href="sec-advanced.html#cb147-10" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> logFC,</span>
<span id="cb147-11"><a href="sec-advanced.html#cb147-11" tabindex="-1"></a>        <span class="at">y =</span> <span class="sc">-</span><span class="fu">log10</span>(pval),</span>
<span id="cb147-12"><a href="sec-advanced.html#cb147-12" tabindex="-1"></a>        <span class="at">color =</span> isUps) <span class="sc">+</span></span>
<span id="cb147-13"><a href="sec-advanced.html#cb147-13" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb147-14"><a href="sec-advanced.html#cb147-14" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="sc">-</span><span class="fu">log10</span>(<span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb147-15"><a href="sec-advanced.html#cb147-15" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(</span>
<span id="cb147-16"><a href="sec-advanced.html#cb147-16" tabindex="-1"></a>      <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"grey20"</span>, <span class="st">"firebrick"</span>), <span class="at">name =</span> <span class="st">""</span>,</span>
<span id="cb147-17"><a href="sec-advanced.html#cb147-17" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"HeLA background"</span>, <span class="st">"UPS standard"</span>)</span>
<span id="cb147-18"><a href="sec-advanced.html#cb147-18" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb147-19"><a href="sec-advanced.html#cb147-19" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> Comparison, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb147-20"><a href="sec-advanced.html#cb147-20" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Statistical inference for all pairwise comparisons"</span>,</span>
<span id="cb147-21"><a href="sec-advanced.html#cb147-21" tabindex="-1"></a>            <span class="at">subtitle =</span> <span class="st">"Protein-level modelling"</span>) </span></code></pre></div>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-226-1.png" width="672"></p>
<p>We plot the fold change distributions:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="sec-advanced.html#cb148-1" tabindex="-1"></a><span class="fu">ggplot</span>(inferences) <span class="sc">+</span></span>
<span id="cb148-2"><a href="sec-advanced.html#cb148-2" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> logFC,</span>
<span id="cb148-3"><a href="sec-advanced.html#cb148-3" tabindex="-1"></a>        <span class="at">x =</span> isUps,</span>
<span id="cb148-4"><a href="sec-advanced.html#cb148-4" tabindex="-1"></a>        <span class="at">colour =</span> isUps) <span class="sc">+</span></span>
<span id="cb148-5"><a href="sec-advanced.html#cb148-5" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb148-6"><a href="sec-advanced.html#cb148-6" tabindex="-1"></a>    <span class="fu">geom_point</span>( <span class="do">## Adding the expected Log2 fold changes </span></span>
<span id="cb148-7"><a href="sec-advanced.html#cb148-7" tabindex="-1"></a>        <span class="at">data =</span> <span class="fu">group_by</span>(inferences, Comparison, isUps) <span class="sc">|&gt;</span> </span>
<span id="cb148-8"><a href="sec-advanced.html#cb148-8" tabindex="-1"></a>          <span class="fu">summarise</span>(<span class="at">logFC =</span> <span class="fu">ifelse</span>(isUps, <span class="fu">log2</span>(<span class="fu">eval</span>(<span class="fu">parse</span>(<span class="at">text =</span> <span class="fu">sub</span>(<span class="st">"-"</span>, <span class="st">"/"</span>, Comparison)))), <span class="dv">0</span>)),</span>
<span id="cb148-9"><a href="sec-advanced.html#cb148-9" tabindex="-1"></a>        <span class="at">shape =</span> <span class="dv">10</span>, <span class="at">size =</span> <span class="dv">4</span></span>
<span id="cb148-10"><a href="sec-advanced.html#cb148-10" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb148-11"><a href="sec-advanced.html#cb148-11" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(</span>
<span id="cb148-12"><a href="sec-advanced.html#cb148-12" tabindex="-1"></a>        <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"grey20"</span>, <span class="st">"firebrick"</span>), <span class="at">name =</span> <span class="st">""</span>,</span>
<span id="cb148-13"><a href="sec-advanced.html#cb148-13" tabindex="-1"></a>        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"HeLA background"</span>, <span class="st">"UPS standard"</span>)</span>
<span id="cb148-14"><a href="sec-advanced.html#cb148-14" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb148-15"><a href="sec-advanced.html#cb148-15" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> Comparison) <span class="sc">+</span></span>
<span id="cb148-16"><a href="sec-advanced.html#cb148-16" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Distribution of the log2 fold changes"</span>,</span>
<span id="cb148-17"><a href="sec-advanced.html#cb148-17" tabindex="-1"></a>            <span class="at">subtitle =</span> <span class="st">"Protein-level modelling"</span>) </span></code></pre></div>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-227-1.png" width="672"></p>
<p>Exploring the intensities at the protein level is simplified compared
to PSM-level exploration since every sample now contains a single
observation, the protein intensity.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="sec-advanced.html#cb149-1" tabindex="-1"></a>spikein[targetProtein, , <span class="st">"proteins"</span>] <span class="sc">|&gt;</span></span>
<span id="cb149-2"><a href="sec-advanced.html#cb149-2" tabindex="-1"></a>    <span class="fu">longForm</span>(<span class="at">colvars =</span> <span class="fu">colnames</span>(<span class="fu">colData</span>(spikein))) <span class="sc">|&gt;</span></span>
<span id="cb149-3"><a href="sec-advanced.html#cb149-3" tabindex="-1"></a>    <span class="fu">data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb149-4"><a href="sec-advanced.html#cb149-4" tabindex="-1"></a>    <span class="do">## We reorder the sample identifiers to improve visualisation</span></span>
<span id="cb149-5"><a href="sec-advanced.html#cb149-5" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">colname =</span> <span class="fu">factor</span>(colname, <span class="at">levels =</span> <span class="fu">unique</span>(colname[<span class="fu">order</span>(Condition)]))) <span class="sc">|&gt;</span> </span>
<span id="cb149-6"><a href="sec-advanced.html#cb149-6" tabindex="-1"></a>    <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb149-7"><a href="sec-advanced.html#cb149-7" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> colname,</span>
<span id="cb149-8"><a href="sec-advanced.html#cb149-8" tabindex="-1"></a>        <span class="at">y =</span> value) <span class="sc">+</span></span>
<span id="cb149-9"><a href="sec-advanced.html#cb149-9" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> Condition)) <span class="sc">+</span></span>
<span id="cb149-10"><a href="sec-advanced.html#cb149-10" tabindex="-1"></a>    <span class="fu">facet_grid</span>(<span class="sc">~</span> Mixture, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb149-11"><a href="sec-advanced.html#cb149-11" tabindex="-1"></a>    <span class="fu">ggtitle</span>(targetProtein,</span>
<span id="cb149-12"><a href="sec-advanced.html#cb149-12" tabindex="-1"></a>            <span class="at">subtitle =</span> <span class="st">"Summarised protein data"</span>) <span class="sc">+</span></span>
<span id="cb149-13"><a href="sec-advanced.html#cb149-13" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb149-14"><a href="sec-advanced.html#cb149-14" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-228-1.png" width="960"></p>
<p>Notice how the summarisation-based approach hides the variation
associated with the measurement of different peptide ions within the
same protein, as well as discrepancies between peptide identification
rates across mixtures.</p>
</div>
<div id="dealing-with-fiterrors" class="section level2" number="3.9">
<h2>
<span class="header-section-number">3.9</span> Dealing with <code id="sec-fiterror">fitErrors</code>
<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('dealing-with-fiterrors')" onmouseout="reset_tooltip('dealing-with-fiterrors-tooltip')"><span class="tooltiptext" id="dealing-with-fiterrors-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>Missing value patterns in the data may lead to non-estimable
parameters. This is recognised by <code>msqrob2</code> and will lead to
<code>fitError</code>s which is a type of model output where the model could not
be fit. This information is available from the <code>StatModel</code> objects.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="sec-advanced.html#cb150-1" tabindex="-1"></a><span class="fu">rowData</span>(spikein[[<span class="st">"proteins_msqrob"</span>]])[[<span class="st">"msqrobModels"</span>]] <span class="sc">|&gt;</span></span>
<span id="cb150-2"><a href="sec-advanced.html#cb150-2" tabindex="-1"></a>    <span class="fu">sapply</span>(<span class="cf">function</span>(x) x<span class="sc">@</span>type) <span class="sc">|&gt;</span></span>
<span id="cb150-3"><a href="sec-advanced.html#cb150-3" tabindex="-1"></a>    <span class="fu">table</span>()</span></code></pre></div>
<pre><code>## 
## fitError     lmer 
##       94      313</code></pre>
<p>We suggest 3 strategies for dealing with these <code>fitError</code>s.</p>
<div id="sec-msqrob_refit" class="section level3" number="3.9.1">
<h3>
<span class="header-section-number">3.9.1</span> Removing the random effect of sample<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('sec-msqrob_refit')" onmouseout="reset_tooltip('sec-msqrob_refit-tooltip')"><span class="tooltiptext" id="sec-msqrob_refit-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>This strategy only applies for PSM-level models. Some proteins are
difficult to detect and may be quantified by a single peptide ion
species. In these cases, every sample contains a single observation
for the protein and hence no random effect of <code>Run:Label</code> can be
estimated. While the results for such one-hit wonders are
questionable, we provide <code>msqrobRefit()</code> to refit a new model for a
subset of proteins of interest.</p>
<p>In this case, we want to refit a model without a sample effect for
one-hit-wonder proteins. This information can be retrieved from the
aggregation results, using <code>aggcounts()</code>. This getter function
provides the number of features used when performing summarisation for
each protein in each sample.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="sec-advanced.html#cb152-1" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">aggcounts</span>(spikein[[<span class="st">"proteins_msqrob"</span>]])</span>
<span id="cb152-2"><a href="sec-advanced.html#cb152-2" tabindex="-1"></a>counts[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##        161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw_Abundance..127N 161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw_Abundance..127C
## O00151                                                            4                                                            4
## O00220                                                            1                                                            2
## O00244                                                            0                                                            0
## O00299                                                           15                                                           15
## O00330                                                            2                                                            2
##        161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw_Abundance..128N 161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw_Abundance..128C
## O00151                                                            4                                                            4
## O00220                                                            2                                                            1
## O00244                                                            0                                                            0
## O00299                                                           15                                                           15
## O00330                                                            2                                                            2
##        161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.raw_Abundance..129N
## O00151                                                            4
## O00220                                                            2
## O00244                                                            0
## O00299                                                           15
## O00330                                                            2</code></pre>
<p>One-hit wonder proteins are proteins for which the number of feature
used for summarisation does not exceed 1 peptide ion across samples.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="sec-advanced.html#cb154-1" tabindex="-1"></a>oneHitProteins <span class="ot">&lt;-</span> <span class="fu">rownames</span>(counts)[<span class="fu">rowMax</span>(counts) <span class="sc">==</span> <span class="dv">1</span>]</span></code></pre></div>
<p>Using <code>msqrobRefit()</code> is very similar to <code>msqrobAggregate()</code>, see here
however that we adapted the formula to remove the random effect for
label nested within run. We also mention which proteins must be
refit using the <code>subset</code> argument.</p>
<p><strong>TODO</strong>: include msqrobRefit in <code>msqrob2</code>.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="sec-advanced.html#cb155-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">msqrobRefit</span>(</span>
<span id="cb155-2"><a href="sec-advanced.html#cb155-2" tabindex="-1"></a>    spikein, <span class="at">i =</span> <span class="st">"ions"</span>,</span>
<span id="cb155-3"><a href="sec-advanced.html#cb155-3" tabindex="-1"></a>    <span class="at">subset =</span> oneHitProteins,</span>
<span id="cb155-4"><a href="sec-advanced.html#cb155-4" tabindex="-1"></a>    <span class="at">formula =</span> <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> Condition <span class="sc">+</span> <span class="do">## fixed effect for experimental condition</span></span>
<span id="cb155-5"><a href="sec-advanced.html#cb155-5" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Label) <span class="sc">+</span> <span class="do">## fixed effect for label</span></span>
<span id="cb155-6"><a href="sec-advanced.html#cb155-6" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Mixture) <span class="sc">+</span> <span class="do">## random effect for mixture</span></span>
<span id="cb155-7"><a href="sec-advanced.html#cb155-7" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run ) <span class="sc">+</span> <span class="do">## random effect for run</span></span>
<span id="cb155-8"><a href="sec-advanced.html#cb155-8" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run<span class="sc">:</span>ionID), <span class="do">## random effect for PSM nested in MS run</span></span>
<span id="cb155-9"><a href="sec-advanced.html#cb155-9" tabindex="-1"></a>        <span class="do">## random effect for label nested in run has been removed</span></span>
<span id="cb155-10"><a href="sec-advanced.html#cb155-10" tabindex="-1"></a>    <span class="at">fcol =</span> <span class="st">"Protein.Accessions"</span>,</span>
<span id="cb155-11"><a href="sec-advanced.html#cb155-11" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"proteins_msqrob"</span>,</span>
<span id="cb155-12"><a href="sec-advanced.html#cb155-12" tabindex="-1"></a>    <span class="at">robust =</span> <span class="cn">TRUE</span>, <span class="at">ridge =</span> <span class="cn">TRUE</span></span>
<span id="cb155-13"><a href="sec-advanced.html#cb155-13" tabindex="-1"></a>)</span></code></pre></div>
<p>Let’s see how removing the random effect of label within run for
one-hit-wonder proteins reduced the number of <code>fitError</code>s.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="sec-advanced.html#cb156-1" tabindex="-1"></a>fitTypes <span class="ot">&lt;-</span> <span class="fu">rowData</span>(spikein[[<span class="st">"proteins_msqrob"</span>]])[[<span class="st">"msqrobModels"</span>]] <span class="sc">|&gt;</span></span>
<span id="cb156-2"><a href="sec-advanced.html#cb156-2" tabindex="-1"></a>    <span class="fu">sapply</span>(<span class="cf">function</span>(x) x<span class="sc">@</span>type)</span>
<span id="cb156-3"><a href="sec-advanced.html#cb156-3" tabindex="-1"></a><span class="fu">table</span>(fitTypes)</span></code></pre></div>
<pre><code>## fitTypes
## fitError     lmer 
##        1      406</code></pre>
</div>
<div id="manual-inspection" class="section level3" number="3.9.2">
<h3>
<span class="header-section-number">3.9.2</span> Manual inspection<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('manual-inspection')" onmouseout="reset_tooltip('manual-inspection-tooltip')"><span class="tooltiptext" id="manual-inspection-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>One protein is still non-estimable upon refitting and requires
additional data exploration to understand why the model cannot be
estimated. Let us take the protein that cannot be fitted.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="sec-advanced.html#cb158-1" tabindex="-1"></a>proteinError <span class="ot">&lt;-</span> <span class="fu">names</span>(fitTypes[fitTypes <span class="sc">==</span> <span class="st">"fitError"</span>])[[<span class="dv">1</span>]]</span></code></pre></div>
<p>To understand the problem, we plot the data for that protein using the
same <code>QFeatures</code> pipeline described above. We here plot the data in
function of the <code>Label</code> (x-axis), <code>Condition</code> (colour) and <code>Mixture</code>
(shape).</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="sec-advanced.html#cb159-1" tabindex="-1"></a>spikein[proteinError, , <span class="st">"ions"</span>] <span class="sc">|&gt;</span></span>
<span id="cb159-2"><a href="sec-advanced.html#cb159-2" tabindex="-1"></a>    <span class="fu">longForm</span>(<span class="at">colvars =</span> <span class="fu">colnames</span>(<span class="fu">colData</span>(spikein)),</span>
<span id="cb159-3"><a href="sec-advanced.html#cb159-3" tabindex="-1"></a>               <span class="at">rowvars =</span> <span class="fu">c</span>(<span class="st">"Protein.Accessions"</span>, <span class="st">"ionID"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb159-4"><a href="sec-advanced.html#cb159-4" tabindex="-1"></a>    <span class="fu">data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb159-5"><a href="sec-advanced.html#cb159-5" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">colname =</span> <span class="fu">factor</span>(colname, <span class="at">levels =</span> <span class="fu">unique</span>(colname[<span class="fu">order</span>(Condition)]))) <span class="sc">|&gt;</span> </span>
<span id="cb159-6"><a href="sec-advanced.html#cb159-6" tabindex="-1"></a>    <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb159-7"><a href="sec-advanced.html#cb159-7" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> colname,</span>
<span id="cb159-8"><a href="sec-advanced.html#cb159-8" tabindex="-1"></a>        <span class="at">y =</span> value) <span class="sc">+</span></span>
<span id="cb159-9"><a href="sec-advanced.html#cb159-9" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> Condition)) <span class="sc">+</span></span>
<span id="cb159-10"><a href="sec-advanced.html#cb159-10" tabindex="-1"></a>    <span class="fu">facet_grid</span>(<span class="sc">~</span> Mixture, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb159-11"><a href="sec-advanced.html#cb159-11" tabindex="-1"></a>    <span class="fu">ggtitle</span>(targetProtein) <span class="sc">+</span></span>
<span id="cb159-12"><a href="sec-advanced.html#cb159-12" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb159-13"><a href="sec-advanced.html#cb159-13" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="msqrob2book_files/figure-html/unnamed-chunk-234-1.png" width="672"></p>
<p>We can immediately spot that PSM intensities are only present in
mixture 3. Hence, the mixed model cannot be fitted with a random
effect for mixture. However, we don’t want to rely on a result that
has been measured in a single replicate and <code>msqrob2</code> flags these
problematic proteins instead of defining ad-hoc heuristics, avoiding
potentially misleading conclusions.</p>
</div>
<div id="imputation" class="section level3" number="3.9.3">
<h3>
<span class="header-section-number">3.9.3</span> Imputation<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('imputation')" onmouseout="reset_tooltip('imputation-tooltip')"><span class="tooltiptext" id="imputation-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>The last strategy to deal with fit errors is to impute missing values
so that all models can be estimated. <code>QFeatures</code> provides a large
panel of imputation strategies through <code>impute()</code>. Identifying which
imputation strategy is most suited for this data set is outside the
scope of this book, and we here arbitrarily decide to use KNN
imputation.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="sec-advanced.html#cb160-1" tabindex="-1"></a>(spikein <span class="ot">&lt;-</span> <span class="fu">impute</span>(</span>
<span id="cb160-2"><a href="sec-advanced.html#cb160-2" tabindex="-1"></a>    spikein, <span class="at">i =</span> <span class="st">"ions"</span>, <span class="at">name =</span> <span class="st">"ions_imputed"</span>,</span>
<span id="cb160-3"><a href="sec-advanced.html#cb160-3" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"knn"</span>, <span class="at">colmax =</span> <span class="dv">1</span></span>
<span id="cb160-4"><a href="sec-advanced.html#cb160-4" tabindex="-1"></a>))</span></code></pre></div>
<pre><code>## An instance of class QFeatures (type: bulk) with 64 sets:
## 
##  [1] Mixture1_01: SummarizedExperiment with 1719 rows and 8 columns 
##  [2] Mixture1_02: SummarizedExperiment with 1722 rows and 8 columns 
##  [3] Mixture1_03: SummarizedExperiment with 1776 rows and 8 columns 
##  ...
##  [62] proteins: SummarizedExperiment with 407 rows and 120 columns 
##  [63] proteins_msqrob: SummarizedExperiment with 407 rows and 120 columns 
##  [64] ions_imputed: SummarizedExperiment with 4066 rows and 120 columns</code></pre>
<p>The function added a new set <code>ions_imputed</code> which we can use to fit
the ion-level model.</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="sec-advanced.html#cb162-1" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">msqrobAggregate</span>(</span>
<span id="cb162-2"><a href="sec-advanced.html#cb162-2" tabindex="-1"></a>    spikein,  <span class="at">i =</span> <span class="st">"ions_imputed"</span>,</span>
<span id="cb162-3"><a href="sec-advanced.html#cb162-3" tabindex="-1"></a>    <span class="at">formula =</span> <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> Condition <span class="sc">+</span> <span class="do">## fixed effect for experimental condition</span></span>
<span id="cb162-4"><a href="sec-advanced.html#cb162-4" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Label) <span class="sc">+</span> <span class="do">## random effect for label</span></span>
<span id="cb162-5"><a href="sec-advanced.html#cb162-5" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Mixture) <span class="sc">+</span> <span class="do">## random effect for mixture</span></span>
<span id="cb162-6"><a href="sec-advanced.html#cb162-6" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run) <span class="sc">+</span> <span class="do">## random effect for run</span></span>
<span id="cb162-7"><a href="sec-advanced.html#cb162-7" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run<span class="sc">:</span>Label) <span class="sc">+</span> <span class="do">## random effect for PSMs from the same protein in a label of a run</span></span>
<span id="cb162-8"><a href="sec-advanced.html#cb162-8" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run<span class="sc">:</span>ionID), <span class="do">## random effect for ions in the same spectrum of an MS run</span></span>
<span id="cb162-9"><a href="sec-advanced.html#cb162-9" tabindex="-1"></a>    <span class="at">fcol =</span> <span class="st">"Protein.Accessions"</span>,</span>
<span id="cb162-10"><a href="sec-advanced.html#cb162-10" tabindex="-1"></a>    <span class="at">modelColumnName =</span> <span class="st">"msqrob_psm_rrilmm"</span>,</span>
<span id="cb162-11"><a href="sec-advanced.html#cb162-11" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"proteins_msqrob_imputed"</span>,</span>
<span id="cb162-12"><a href="sec-advanced.html#cb162-12" tabindex="-1"></a>    <span class="at">robust =</span> <span class="cn">TRUE</span>, <span class="at">ridge =</span> <span class="cn">TRUE</span></span>
<span id="cb162-13"><a href="sec-advanced.html#cb162-13" tabindex="-1"></a>)</span></code></pre></div>
<p>We here assess how many models have been estimated for all proteins
upon imputation.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="sec-advanced.html#cb163-1" tabindex="-1"></a><span class="fu">rowData</span>(spikein[[<span class="st">"proteins_msqrob_imputed"</span>]])[[<span class="st">"msqrob_psm_rrilmm"</span>]] <span class="sc">|&gt;</span></span>
<span id="cb163-2"><a href="sec-advanced.html#cb163-2" tabindex="-1"></a>    <span class="fu">sapply</span>(<span class="cf">function</span>(x) x<span class="sc">@</span>type) <span class="sc">|&gt;</span></span>
<span id="cb163-3"><a href="sec-advanced.html#cb163-3" tabindex="-1"></a>    <span class="fu">table</span>()</span></code></pre></div>
<pre><code>## 
## fitError     lmer 
##       59      348</code></pre>
<p>Again <code>fitError</code>s were generated for one-hit-wonder proteins.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="sec-advanced.html#cb165-1" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">aggcounts</span>(spikein[[<span class="st">"proteins_msqrob_imputed"</span>]])</span>
<span id="cb165-2"><a href="sec-advanced.html#cb165-2" tabindex="-1"></a>oneHitProteins <span class="ot">&lt;-</span> <span class="fu">rownames</span>(counts)[<span class="fu">rowMax</span>(counts) <span class="sc">==</span> <span class="dv">1</span>]</span>
<span id="cb165-3"><a href="sec-advanced.html#cb165-3" tabindex="-1"></a>spikein <span class="ot">&lt;-</span> <span class="fu">msqrobRefit</span>(</span>
<span id="cb165-4"><a href="sec-advanced.html#cb165-4" tabindex="-1"></a>    spikein, <span class="at">i =</span> <span class="st">"ions_imputed"</span>,</span>
<span id="cb165-5"><a href="sec-advanced.html#cb165-5" tabindex="-1"></a>    <span class="at">subset =</span> oneHitProteins,</span>
<span id="cb165-6"><a href="sec-advanced.html#cb165-6" tabindex="-1"></a>    <span class="at">formula =</span> <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> Condition <span class="sc">+</span> <span class="do">## fixed effect for experimental condition</span></span>
<span id="cb165-7"><a href="sec-advanced.html#cb165-7" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Label) <span class="sc">+</span> <span class="do">## random effect for label</span></span>
<span id="cb165-8"><a href="sec-advanced.html#cb165-8" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Mixture) <span class="sc">+</span> <span class="do">## random effect for mixture</span></span>
<span id="cb165-9"><a href="sec-advanced.html#cb165-9" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run ) <span class="sc">+</span> <span class="do">## random effect for run</span></span>
<span id="cb165-10"><a href="sec-advanced.html#cb165-10" tabindex="-1"></a>        (<span class="dv">1</span> <span class="sc">|</span> Run<span class="sc">:</span>ionID), <span class="do">## random effect for PSM nested in MS run</span></span>
<span id="cb165-11"><a href="sec-advanced.html#cb165-11" tabindex="-1"></a>        <span class="do">## random effect for label nested in run has been removed</span></span>
<span id="cb165-12"><a href="sec-advanced.html#cb165-12" tabindex="-1"></a>    <span class="at">fcol =</span> <span class="st">"Protein.Accessions"</span>,</span>
<span id="cb165-13"><a href="sec-advanced.html#cb165-13" tabindex="-1"></a>    <span class="at">modelColumnName =</span> <span class="st">"msqrob_psm_rrilmm"</span>,</span>
<span id="cb165-14"><a href="sec-advanced.html#cb165-14" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"proteins_msqrob_imputed"</span>,</span>
<span id="cb165-15"><a href="sec-advanced.html#cb165-15" tabindex="-1"></a>    <span class="at">robust =</span> <span class="cn">TRUE</span>, <span class="at">ridge =</span> <span class="cn">TRUE</span></span>
<span id="cb165-16"><a href="sec-advanced.html#cb165-16" tabindex="-1"></a>)</span>
<span id="cb165-17"><a href="sec-advanced.html#cb165-17" tabindex="-1"></a><span class="fu">rowData</span>(spikein[[<span class="st">"proteins_msqrob_imputed"</span>]])[[<span class="st">"msqrob_psm_rrilmm"</span>]] <span class="sc">|&gt;</span></span>
<span id="cb165-18"><a href="sec-advanced.html#cb165-18" tabindex="-1"></a>    <span class="fu">sapply</span>(<span class="cf">function</span>(x) x<span class="sc">@</span>type) <span class="sc">|&gt;</span></span>
<span id="cb165-19"><a href="sec-advanced.html#cb165-19" tabindex="-1"></a>    <span class="fu">table</span>()</span></code></pre></div>
<pre><code>## 
## lmer 
##  407</code></pre>
<p>Upon refit, no <code>fitError</code>s were generated for any proteins, as
expected. Be mindful that although the results upon imputation will be
highly depended on the suitability of the imputation approach.</p>
</div>
</div>
<div id="conclusion-1" class="section level2" number="3.10">
<h2>
<span class="header-section-number">3.10</span> Conclusion<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('conclusion-1')" onmouseout="reset_tooltip('conclusion-1-tooltip')"><span class="tooltiptext" id="conclusion-1-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>In this chapter, we expanded upon the basic concepts with a more
complex analysis. First, we started our analysis from PSM-level data,
showing that our tools are amenable to read both <a href="sec-basics.html#sec-peptide_table">wide
format</a> and <a href="sec-advanced.html#sec-psm_table">long format</a> tables.
Starting from the PSM level data also enabled better control of the
PSM filtering compared to starting with peptide-level data. We
demonstrated how to conduct a comprehensive feature filtering
workflow, with different level of customisation to enable filtering
based on any criterion.</p>
<p>The complexity of the analysis is the reflection of the complexity of
the TMT-based designs, which impose several additional sources of
variation compared to LFQ experiments: effect of treatment of
interest, effect of TMT labelling, effect of the MS acquisition run,
and the effect of replication. We built protein-level models, but we
have also shown that we can build PSM-level models if we also include
a spectrum effect and an effect for TMT label nested within run.</p>
<p>Finally, we have demonstrated how to deal with proteins that cannot be
modelled due to missing values. For PSM-level models, we can remove
the random effects for TMT label within run that cannot be estimated for
one-hit-wonder proteins. We can also manually inspect how missing
values can influence the model design, and refit a simplified model
upon expert’s intervention. Finally, we can impute missing values,
which unlocks model fitting, but imposes strong assumption on the
validity of the imputation approach and the reliability of the
predicted values.</p>

</div>
</div>
<p style="text-align: center;">
<a href="sec-basics.html"><button class="btn btn-default">Previous</button></a>
<a href="sec-benchmarking.html"><button class="btn btn-default">Next</button></a>
</p>
<p class="build-date">Page built: 
2025-11-04
 using 
R version 4.5.1 (2025-06-13)
</p>
</div>
</div>



</body>
</html>
