name: Render and deploy bookdown

on: workflow_dispatch

env:
  cache-version: v1

jobs:
  publish-book:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: TRUE
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CRAN: https://packagemanager.posit.co/cran/__linux__/jammy/latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: Rscript install_deps.R

      # - name: Query dependencies and update old packages
      #   run: |
      #     BiocManager::install(ask=FALSE)
      #     saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
      #   shell: Rscript {0}

      # - name: Cache R packages
      #   if: runner.os != 'Windows'
      #   uses: actions/cache@v4
      #   with:
      #     path: /usr/local/lib/R/site-library
      #     key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ hashFiles('.github/depends.Rds') }}
      #     restore-keys: ${{ env.cache-version }}-${{ runner.os }}-r-

      # - name: Install specific package versions
      #   run: |
      #     BiocManager::install("cvanderaa/QFeatures", ref = "uniquePrecId")
      #     BiocManager::install("statOmics/msqrob2")
      #   shell: Rscript {0}

      # - name: Check
      #   env:
      #     _R_CHECK_CRAN_INCOMING_REMOTE_: false
      #   run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
      #   shell: Rscript {0}

      - name: Build bookdown
        run: |
           PATH=$PATH:$HOME/bin/ Rscript -e 'bookdown::render_book()'

      # deploy needs rsync? Seems so.
      - name: Install deploy dependencies
        run: |
          apt-get update
          apt-get -y install rsync

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
